import {saveSite,listSites,loadSite,type SavedSiteSummary} from './siteLibrary';
import {useEffect,useRef,useState} from "react";
import {Upload,Camera} from "lucide-react";
import {AdjustableTopRow} from "./AdjustableTopRow";
import {inspectSiteFile} from "./siteFile";
import {getRenderAiStatus,requestRenderAi,RENDER_AI_SCHEMA,type RenderAiRequest} from "./assistant/renderTool";
const digest=async(bytes:ArrayBuffer)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",bytes)),b=>b.toString(16).padStart(2,"0")).join("");
type Capture={data:string;width:number;height:number;camera:NonNullable<RenderAiRequest["view"]["camera"]>};
export function SiteImport({projectId}:{projectId:string}) {
 const [address,setAddress]=useState("");
 const [savedSites,setSavedSites]=useState<SavedSiteSummary[]>([]),[libraryStatus,setLibraryStatus]=useState(""),[libraryBusy,setLibraryBusy]=useState(false);
 const mapLink=useRef<{window:Window;origin:string;id:string}|null>(null);
 const [file,setFile]=useState<{bytes:ArrayBuffer;name:string;sha:string;site:ReturnType<typeof inspectSiteFile>}|null>(null);
 const [download,setDownload]=useState<{bytes:ArrayBuffer;url:string}|null>(null);
 useEffect(()=>{if(!file){setDownload(null);return;}const url=URL.createObjectURL(new Blob([file.bytes],{type:"model/gltf-binary"}));setDownload({bytes:file.bytes,url});return()=>URL.revokeObjectURL(url);},[file]);
 const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);const [image,setImage]=useState<string|null>(null);
 const host=useRef<HTMLDivElement>(null);const capture=useRef<(()=>Capture)|null>(null);const request=useRef<AbortController|null>(null);const generation=useRef(0);
 useEffect(()=>{generation.current++;request.current?.abort();setFile(null);setImage(null);setBusy(false);setStatus("");return()=>{generation.current++;request.current?.abort();};},[projectId]);
 const load=async(selected:File)=>{const token=++generation.current;setLibraryBusy(false);request.current?.abort();setBusy(false);setImage(null);setStatus("Reading site…");try{if(selected.size>32*1024*1024)throw Error("Choose a site smaller than 32 MB.");const bytes=await selected.arrayBuffer();const site=inspectSiteFile(bytes);const sha=await digest(bytes);if(token!==generation.current)return false;setFile({bytes,name:selected.name,sha,site});return true;}catch(e){if(token===generation.current){setFile(null);setStatus(e instanceof Error?e.message:"Site import failed.");}return false;}};
 useEffect(()=>{let cancelled=false;setSavedSites([]);setLibraryBusy(false);setLibraryStatus("Loading saved sites…");void listSites(projectId).then(rows=>{if(!cancelled){setSavedSites(rows);setLibraryStatus("");}}).catch(e=>{if(!cancelled)setLibraryStatus(e instanceof Error?e.message:"Saved sites unavailable.");});return()=>{cancelled=true;};},[projectId]);
 const save=async()=>{if(!file||libraryBusy)return;const token=generation.current;setLibraryBusy(true);setLibraryStatus("Saving site…");try{await saveSite(projectId,{bytes:file.bytes,name:file.name});const rows=await listSites(projectId);if(token===generation.current){setSavedSites(rows);setLibraryStatus("Site saved to this project on this device.");}}catch(e){if(token===generation.current)setLibraryStatus(e instanceof Error?e.message:"Site could not be saved.");}finally{if(token===generation.current)setLibraryBusy(false);}};
 const reopen=async(id:string)=>{const token=++generation.current;request.current?.abort();setBusy(false);setLibraryBusy(true);setLibraryStatus("Opening saved site…");try{const stored=await loadSite(projectId,id);if(token!==generation.current)return;setImage(null);setFile({bytes:stored.bytes,name:stored.summary.name,sha:stored.summary.sha256,site:stored.site});setLibraryStatus("Saved site reopened.");}catch(e){if(token===generation.current)setLibraryStatus(e instanceof Error?e.message:"Saved site could not be opened.");}finally{if(token===generation.current)setLibraryBusy(false);}};
 const openMap=()=>{try{const configured=String(import.meta.env.VITE_LOOPLET_MAP_URL??(import.meta.env.DEV?'http://127.0.0.1:5176/index.html':''));if(!configured)throw Error('The mapping connection has not been configured for this installation.');const url=new URL(configured);if(!['https:','http:'].includes(url.protocol))throw Error('Invalid mapping connection.');const id=crypto.randomUUID();url.searchParams.set('q',address.trim());url.searchParams.set('xrayOrigin',window.location.origin);url.searchParams.set('xrayRequest',id);const child=window.open(url.href,'_blank');if(!child)throw Error('Allow this app to open the mapping window.');mapLink.current={window:child,origin:url.origin,id};setStatus('Choose the property and prepare its 3D view, then select Send to X-Ray.');}catch(e){setStatus(e instanceof Error?e.message:'Could not open map.');}};
 useEffect(()=>{const receive=(event:MessageEvent)=>{const link=mapLink.current;if(!link||event.source!==link.window||event.origin!==link.origin||event.data?.type!=='looplet:site-response'||event.data.schema!=='looplet.site-transfer/v1'||event.data.requestId!==link.id)return;if(!(event.data.bytes instanceof ArrayBuffer)||event.data.bytes.byteLength>32*1024*1024)return;
 void load(new File([event.data.bytes],'Looplet site.glb',{type:'model/gltf-binary'})).then(ok=>{if(mapLink.current===link)link.window.postMessage({type:'xray:site-ack',requestId:link.id,status:ok?'accepted':'failed'},link.origin);});};window.addEventListener('message',receive);return()=>{window.removeEventListener('message',receive);mapLink.current=null;};},[projectId]);
 useEffect(()=>{
  if(!file||!host.current)return;let cancelled=false;let cleanup=()=>{};capture.current=null;setStatus("Opening 3D site…");
  void (async()=>{const [T,{GLTFLoader},{OrbitControls}]=await Promise.all([import("three"),import("three/examples/jsm/loaders/GLTFLoader.js"),import("three/examples/jsm/controls/OrbitControls.js")]);if(cancelled)return;
   const model=await new GLTFLoader().parseAsync(file.bytes,"");
   const disposeModel=()=>model.scene.traverse(node=>{if(node instanceof T.Mesh||node instanceof T.Line||node instanceof T.Points){node.geometry.dispose();for(const mat of Array.isArray(node.material)?node.material:[node.material]){for(const value of Object.values(mat))if(value instanceof T.Texture)value.dispose();mat.dispose();}}});
   if(cancelled){disposeModel();return;}const element=host.current!;const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(1);element.appendChild(renderer.domElement);
   const scene=new T.Scene();scene.background=new T.Color(0xdde5e8);scene.add(model.scene,new T.HemisphereLight(0xffffff,0x68745c,2));const light=new T.DirectionalLight(0xffffff,2);light.position.set(30,50,20);scene.add(light);
   const box=new T.Box3().setFromObject(model.scene);if(box.isEmpty()){disposeModel();renderer.dispose();renderer.domElement.remove();throw Error("This site has no visible geometry.");}
   const target=box.getCenter(new T.Vector3());const radius=Math.max(2,box.getSize(new T.Vector3()).length());const camera=new T.PerspectiveCamera(45,1,.1,Math.max(1000,radius*10));camera.position.copy(target).add(new T.Vector3(.6,.5,.6).normalize().multiplyScalar(radius*1.3));const controls=new OrbitControls(camera,renderer.domElement);controls.target.copy(target);controls.update();
   const draw=()=>renderer.render(scene,camera);const resize=()=>{const width=Math.min(1280,Math.max(1,element.clientWidth)),height=360;renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();draw();};const observer=new ResizeObserver(resize);observer.observe(element);controls.addEventListener("change",draw);resize();
   capture.current=()=>{draw();return {data:renderer.domElement.toDataURL("image/png").split(",")[1],width:renderer.domElement.width,height:renderer.domElement.height,camera:{projection:"perspective",position:camera.position.toArray(),target:controls.target.toArray(),zoom:camera.zoom}};};
   cleanup=()=>{observer.disconnect();controls.dispose();disposeModel();renderer.dispose();renderer.domElement.remove();};setStatus("Site ready. Drag to orbit. Use Save site to keep a copy on this device.");
  })().catch(e=>{if(!cancelled)setStatus(e instanceof Error?e.message:"3D preview failed.");});
  return()=>{cancelled=true;capture.current=null;cleanup();};
 },[file]);
 const render=async()=>{if(!file||!capture.current)return;const token=generation.current;const controller=new AbortController();request.current=controller;setBusy(true);setStatus("Checking renderer…");try{const available=await getRenderAiStatus();if(!available.available)throw Error(available.message);if(token!==generation.current)return;const shot=capture.current();const bytes=Uint8Array.from(atob(shot.data),c=>c.charCodeAt(0));const result=await requestRenderAi({schema:RENDER_AI_SCHEMA,requestId:crypto.randomUUID(),projectId,view:{target:"looplet-site",width:shot.width,height:shot.height,frame:1,documentId:file.sha,sourceSha256:file.sha,sheet:1,renderedDesignRevision:null,camera:shot.camera},image:{mimeType:"image/png",data:shot.data,sha256:await digest(bytes.buffer)},brief:{planName:file.name.slice(0,200),scene:"A measured terrain and fence model. Preserve the land contours, panel positions, gates, step heights and camera. Do not invent a building."},materials:{roof:"Unchanged",walls:"Preserve existing fence colours and materials",windows:"Unchanged",landscaping:"Realistic ground matching the model",lighting:"Natural daylight",style:"Photorealistic site visualisation",direction:"Preserve all measured geometry"}},controller.signal);if(token!==generation.current)return;setImage(`data:${result.image.mimeType};base64,${result.image.data}`);setStatus("AI visualisation ready. Geometry and measurements remain in the imported site file.");}catch(e){if(token===generation.current)setStatus(e instanceof Error?e.message:"Rendering failed.");}finally{if(token===generation.current)setBusy(false);}};
 return <section className="rounded-xl border border-border p-3">
  <AdjustableTopRow id="looplet-site" label="Looplet site" minHeight={48}><div className="flex flex-wrap items-center gap-3"><strong>Looplet site</strong><label className="pill inline-flex cursor-pointer items-center gap-2"><Upload className="size-4"/>Import 3D site<input type="file" disabled={libraryBusy} accept=".glb" className="sr-only" onChange={e=>{const next=e.target.files?.[0];e.target.value="";if(next)void load(next);}}/></label>{file&&<button className="pill inline-flex items-center gap-2" disabled={busy||libraryBusy} onClick={()=>void render()}><Camera className="size-4"/>{busy?"Rendering…":"Generate AI visualisation"}</button>}</div></AdjustableTopRow>
  <div className="mt-2 flex flex-wrap items-center gap-2"><input aria-label="Property address for map" value={address} onChange={e=>setAddress(e.target.value)} placeholder="Property address" className="pill"/><button className="pill" disabled={!address.trim()} onClick={openMap}>Open property in map</button></div>
  <div className="mt-3 flex flex-wrap items-center gap-2">{file&&<button className="pill" disabled={libraryBusy||busy} onClick={()=>void save()}>Save site</button>}{file&&download?.bytes===file.bytes&&<a className="pill" href={download.url} download={file.name.replace(/[<>:"/\\|?*\x00-\x1f]/g,"_").replace(/\.glb$/i,"")+".glb"}>Download site backup</a>}<label className="min-w-0 max-w-full">Reopen saved site <select aria-label="Reopen saved site" className="pill max-w-full" value="" disabled={libraryBusy||!savedSites.length} onChange={e=>{if(e.target.value)void reopen(e.target.value);}}><option value="">{savedSites.length?"Choose a saved site":"No saved sites in this project"}</option>{savedSites.map(s=><option key={s.id} value={s.id}>{s.address||s.name} · {new Date(s.savedAt).toLocaleString()}</option>)}</select></label></div><p className="mt-2 text-xs text-muted">Saved on this device for this project. Download a site backup to keep a separate GLB copy or import it on another device.</p><p role="status" className="mt-2 text-sm">{libraryStatus}</p>
  {!file&&<p className="mt-2 text-sm text-muted">In the mapping app’s 3D view, choose Export to X-Ray, then import that site here.</p>}
  {file&&<><p className="my-2 text-sm"><strong>{file.site.address??file.name}</strong> · {file.site.terrain?.source?.label??"Source unreported"} · metres</p><div ref={host} className="w-full overflow-hidden rounded-lg"/><p className="mt-2 text-xs text-muted">Processed terrain estimates; verify elevations before engineering use. The 3D file retains the source data and fence settings.</p></>}
  <p role="status" className="mt-2 text-sm">{status}</p>{image&&<><img src={image} alt="AI visualisation of the imported site" className="mt-3 w-full rounded-lg"/><a className="pill mt-2 inline-block" href={image} download="site-visualisation.png">Download visualisation</a></>}
 </section>;
}
