import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { hostname } from 'node:os';
import { FastCdpBatch } from 'file:///C:/Users/danie/Documents/AtomicLedgerQualification/2026-09-08/qualification/scripts/fast-cdp.mjs';
if(hostname().toLowerCase()!=='dans1') throw Error('Wrong host');
const campaign=process.argv[2];
if(!['roofing','qs'].includes(campaign)) throw Error('Unknown campaign');
const output='live-'+campaign+'-'+new Date().toISOString().replace(/[:.]/g,'-'); await mkdir(output);
const [port,path]=(await readFile(process.argv[3]+'/DevToolsActivePort','utf8')).trim().split(/\r?\n/);
const ws=new WebSocket('ws://127.0.0.1:'+port+path);
await new Promise((yes,no)=>{ws.onopen=yes;ws.onerror=no});
let id=0;const pending=new Map(),errors=[];
ws.onmessage=({data})=>{const m=JSON.parse(data);if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text);const p=pending.get(m.id);if(p){clearTimeout(p.timer);pending.delete(m.id);m.error?p.no(Error(m.error.message)):p.yes(m.result)}};
const socket={call:(method,params={},sessionId)=>new Promise((yes,no)=>{const next=++id,timer=setTimeout(()=>{pending.delete(next);no(Error(method+' deadline'))},330000);pending.set(next,{yes,no,timer});ws.send(JSON.stringify({id:next,method,params,...(sessionId?{sessionId}:{})}))})};
socket.evaluate=async(expression,sessionId)=>{const r=await socket.call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true},sessionId);if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value};
const batch=new FastCdpBatch(socket,output),commands=[];
async function run(ops){commands.push(...ops);await batch.run(ops)}
const ready="document.querySelector('[data-hydration-status]')?.getAttribute('data-hydration-status')==='ready'";
const fixture={hierarchyId:'QA',hierarchyRevision:'A',nodes:[{id:'building',label:'Building',parentId:null},{id:'walls',label:'Walls',parentId:'building'}],items:[{id:'a',quantity:'0.1',unit:'m2',evidence:'sample',source:null},{id:'b',quantity:'0.2',unit:'m2',evidence:'sample',source:null},{id:'c',quantity:'3',unit:'lm',evidence:'sample',source:null},{id:'d',quantity:'4',unit:'m2',evidence:'unverified',source:null}],assignments:[{itemId:'a',nodeId:'building'},{itemId:'b',nodeId:'walls'},{itemId:'c',nodeId:'walls'}]};
const prompt=campaign==='roofing'?"Execute calculate_draft_roof_sheet_coverage for this explicit QA rectangle: developedWidthM='8', developedRunM='9.8', effectiveCoverM='0.8', orderLengthM='5', endLapM='0.2', measurementReference='QA synthetic rectangle', supplierReference='QA supplied sheet specification'. Report the actual tool result, explain course steps and lap policy, and state how many courses a 9.81 m run needs and why. Explain what the excess run does and does not establish. Include a concise Developer review. Use supplied inputs only; do not change project or geometry.":'Execute classify_draft_quantities with this exact synthetic input: '+JSON.stringify(fixture)+'. Explain the actual CSV columns, whether parent labels and parent-direct items are retained, and why report totals are safe while inclusive parent/child totals cannot be added. Include a concise Developer review. Use supplied inputs only; do not change project or worksheet.';
let error,session,archive,reloaded;
const version=await socket.call('Browser.getVersion');
try{
 await run([['context','app']]);session=batch.contexts.get('app').sessionId;
 await socket.call('Runtime.enable',{},session);
 await socket.call('Page.addScriptToEvaluateOnNewDocument',{source:"localStorage.setItem('xray:assistant-provider:v2','minimax')"},session);
 await socket.call('Emulation.setDeviceMetricsOverride',{width:1600,height:1000,deviceScaleFactor:1,mobile:false},session);
 await run([['navigate','app','http://127.0.0.1:8080/'],['wait','app',ready],['eval','app',`(async()=>{const s=await (await fetch('/api/minimax-ai')).json();if(!s.available||s.model!=='MiniMax-M3')throw Error('Provider unavailable');return s})()`],['eval','app',`(()=>{if(localStorage.getItem('xray:assistant-provider:v2')!=='minimax')throw Error('Wrong provider');const b=[...document.querySelectorAll('button')].find(x=>/live assistant/i.test(x.getAttribute('aria-label')||'')||x.textContent.trim()==='Live assistant');if(b)b.click();return true})()`],['wait','app',`!!document.querySelector('textarea[placeholder^="Ask anything"]')`],['eval','app',`(async()=>{const s=await import('/src/studio/store.ts');const h=await import('/src/studio/assistant/chatHistory.ts');window.__qaJob=s.useStudio.getState().job.id;const a=await h.readChatArchive(window.__qaJob);if(a?.threads?.some(t=>t.entries.length))throw Error('Expected isolated empty conversation');return {jobId:window.__qaJob}})()`],['eval','app',`(()=>{const t=document.querySelector('textarea[placeholder^="Ask anything"]');Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(t,${JSON.stringify(prompt)});t.dispatchEvent(new Event('input',{bubbles:true}));return true})()`],['wait','app',`document.querySelector('button[aria-label="Send assistant message"]')?.disabled===false`],['screenshot','app','desktop-composer.png'],['eval','app',`document.querySelector('button[aria-label="Send assistant message"]').click();'sent'`],['eval','app',`(async()=>{const h=await import('/src/studio/assistant/chatHistory.ts');const end=Date.now()+300000;while(Date.now()<end){const a=await h.readChatArchive(window.__qaJob);const t=a?.threads.find(t=>t.id===a.activeId);if(t?.error)throw Error(t.error);if(t&&!t.busy&&t.entries.some(e=>e.kind==='assistant')){window.__qaArchive=a;return {entries:t.entries.length,busy:t.busy,error:t.error}}await new Promise(r=>setTimeout(r,500))}throw Error('No completed assistant reply within deadline')})()`],['screenshot','app','desktop-reply.png']]);
 archive=await socket.evaluate('window.__qaArchive',session);await writeFile(output+'/archive.json',JSON.stringify(archive,null,2));
 const jobId=archive.projectId,expected=archive.threads.find(t=>t.id===archive.activeId).entries;
 await socket.call('Emulation.setDeviceMetricsOverride',{width:1024,height:768,deviceScaleFactor:1,mobile:false},session);
 await run([['navigate','app','http://127.0.0.1:8080/'],['wait','app',ready],['eval','app',`(async()=>{const h=await import('/src/studio/assistant/chatHistory.ts');const a=await h.readChatArchive(${JSON.stringify(jobId)});const entries=a?.threads.find(t=>t.id===${JSON.stringify(archive.activeId)})?.entries;if(JSON.stringify(entries)!==${JSON.stringify(JSON.stringify(expected))})throw Error('Reload archive differs');return {entries:entries.length,identical:true}})()`],['screenshot','app','tablet-reloaded.png']]);
 reloaded=true;if(errors.length)throw Error('Uncaught browser errors');
}catch(e){error=e;await run([['screenshot','app','failure.png']]).catch(()=>{})}
finally{try{await batch.cleanup()}catch(e){error??=e}await socket.call('Browser.close').catch(()=>{});ws.close();const report={host:hostname(),campaign,version,source:JSON.parse(await readFile('verification.json','utf8')),verdict:error?'FAIL':'EXECUTED_REQUIRES_PROSE_REVIEW',error:error?.message,errors,reloaded,cleanup:batch.contexts.size===0,receipts:batch.receipts};await writeFile(output+'/scenario.json',JSON.stringify(commands,null,2));await writeFile(output+'/result.json',JSON.stringify(report,null,2));console.log(JSON.stringify({...report,source:undefined,receipts:undefined}));}
if(error)process.exitCode=1;
