import {chromium} from 'playwright';import fs from 'node:fs';import assert from 'node:assert/strict';
const browser=await chromium.connectOverCDP('http://127.0.0.1:9238'),page=browser.contexts()[0].pages()[0];page.setDefaultTimeout(20000);const pause=ms=>new Promise(r=>setTimeout(r,ms));
const say=async text=>{await page.evaluate(text=>{document.getElementById('sketch-film-caption').textContent='GUIDED DEMO / '+text;},text);await pause(1600);};
await page.getByRole('button',{name:'Sketch',exact:true}).click();await page.getByRole('button',{name:'Fit sheet',exact:true}).click();await say('4. Sketch: select Manual layer');await page.getByRole('button',{name:/^Manual layer/}).click();
const target=page.locator('canvas[aria-label="Plan drawing canvas"]');await target.waitFor();const box=await target.boundingBox(),scale=Math.min((box.width-32)/900,(box.height-32)/680);const point=(x,y)=>({x:box.x+box.width/2+(x-450)*scale,y:box.y+box.height/2+(y-340)*scale});
await say('5. Trace the outside: A, B, C, D, then back to A');
for(const [x,y] of [[210,180],[690,180],[690,500],[210,500],[210,180]]){const p=point(x,y);await page.mouse.move(p.x,p.y,{steps:60});await pause(550);await page.mouse.click(p.x,p.y);await pause(1300);}
await page.screenshot({path:'screenshots/sketch-example/03-outline-in-progress.png'});await say('6. Commit trace: save the 20 metre outline');await page.getByRole('button',{name:/^Commit trace/}).click();await pause(1600);
let job=await page.evaluate(()=>JSON.parse(localStorage.getItem('xray:fencing-job:v2')));assert.equal(job.annotations.length,1);assert.ok(Math.abs(job.annotations[0].value-20)<.06,JSON.stringify(job.annotations[0]));await page.screenshot({path:'screenshots/sketch-example/04-outline-saved.png'});await say('7. A separate trace for the 3 metre divider');
for(const [x,y] of [[450,180],[450,420]]){const p=point(x,y);await page.mouse.move(p.x,p.y,{steps:60});await pause(500);await page.mouse.click(p.x,p.y);await pause(1500);}
await page.getByRole('button',{name:/^Commit trace/}).click();await pause(1300);await page.keyboard.press('Escape');await say('Saved: 20 m outline + 3 m divider. These are annotations, not quantities.');job=await page.evaluate(()=>JSON.parse(localStorage.getItem('xray:fencing-job:v2')));assert.equal(job.annotations.length,2);assert.ok(Math.abs(job.annotations[1].value-3)<.03);fs.writeFileSync('proof/audit/IW-SKETCH-SILVER/demonstrated-job.json',JSON.stringify(job,null,2));await page.screenshot({path:'screenshots/sketch-example/05-finished-on-screen.png'});console.log(JSON.stringify({ok:true,annotations:job.annotations.map(a=>({kind:a.kind,length:a.value,points:a.points.length,source:a.sourceSha256})),runs:job.runs.length}));await browser.close();
