import fs from 'node:fs';
import path from 'node:path';
import net from 'node:net';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
const expected='38c673ae5591c79ffda0fa283c6dc292118cfd2e6c1823b0f4660170ff474f3c';
const exe=path.resolve('proof/growth/2026-09-08-assistant-mcp-r4/release-71f5b012342b/artifacts/src-tauri/target/release/xray-by-looplet.exe');
const sha256=createHash('sha256').update(fs.readFileSync(exe)).digest('hex');assert.equal(sha256,expected,'Final verified EXE identity mismatch');
const base=path.resolve('proof/growth/2026-09-08-assistant-mcp-r4/candidate-workload-shutdown');
const profile=path.resolve('.temp/candidate-workload-shutdown-'+Date.now());
const output=path.join(base,'launch.json');assert(!fs.existsSync(output),'Preserve prior launch evidence');assert(!fs.existsSync(profile),'Fresh isolated profile required');
const port=9276,probe=net.createServer();probe.listen(port,'127.0.0.1');await once(probe,'listening');await new Promise((resolve,reject)=>probe.close(e=>e?reject(e):resolve()));
fs.mkdirSync(profile,{recursive:true});
const child=spawn(exe,[],{windowsHide:true,detached:true,stdio:'ignore',env:{...process.env,WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS:`--remote-debugging-port=${port} --remote-debugging-address=127.0.0.1`,WEBVIEW2_USER_DATA_FOLDER:profile}});
await once(child,'spawn');child.unref();
const result={runId:'71f5b012342b',pid:child.pid,exe,sha256,profile,cdpPort:port,launchedAt:new Date().toISOString(),installed:false,normalProfileUsed:false,comparisonScope:'Final verified binary, fresh isolated profile; 97 successful feature commands then normal close; no viewport emulation.'};
fs.writeFileSync(output,JSON.stringify(result,null,2),{flag:'wx'});console.log(JSON.stringify(result));
fs.writeFileSync(path.join(base,'ready.json'),JSON.stringify([['wait','--fn',"document.querySelector('.workbench')?.dataset.hydrationStatus==='ready'"],['eval',"({title:document.title,tauri:!!window.__TAURI_INTERNALS__,hydration:document.querySelector('.workbench')?.dataset.hydrationStatus})"],['screenshot','screenshots/growth/2026-09-08-shutdown-workload-71f5-ready.png'],['errors']],null,2),{flag:'wx'});
