import {readFileSync,writeFileSync,copyFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {readLedger,inputDigest,sliceStatus,validate,validatePng,render} from '../../../scripts/industry-ledger.mjs';
const hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex'),run=readFileSync('proof/audit/IW022/latest-run.txt','utf8').trim(),result=JSON.parse(readFileSync(`${run}/results.json`,'utf8'));
for(const [p,h]of Object.entries(result.sourceAfter))if(hash(p)!==h)throw Error('Tested input changed '+p);
if(result.failure||!result.sourceUnchanged||result.results.some(r=>!r.passed))throw Error('Runtime checks not passing');
const files=['src/studio/construction/runtime/index.ts','src/studio/construction/runtime/repository.ts','src/studio/construction/runtime/README.md'];let patch='';for(const p of files){const r=spawnSync('git',['diff','--no-index','--','/dev/null',p],{encoding:'utf8',windowsHide:true});if(![0,1].includes(r.status))throw Error(r.stderr);patch+=r.stdout;}writeFileSync('proof/audit/IW022/code.patch',patch);
const manifest={at:new Date().toISOString(),owner:'audit_engine_release',status:'awaiting-independent-verification',inputs:Object.fromEntries([...files,'src/studio/construction/contract.ts','src/studio/construction/lifecycle.ts','package-lock.json','proof/audit/IW022/browser-runtime.mjs'].map(p=>[p,hash(p)])),resultsPath:`${run}/results.json`,resultsSha256:hash(`${run}/results.json`),patchSha256:hash('proof/audit/IW022/code.patch'),typecheckExit:Number(readFileSync('proof/audit/IW022/typecheck-final-exit.txt','utf8').replace(/^\uFEFF/,'').trim())};writeFileSync('proof/audit/IW022/source-manifest.json',JSON.stringify(manifest,null,2));
const alias='proof/audit/IW-VERIFY-01/IW022';mkdirSync(alias,{recursive:true});const aliases=[];
for(const [original,name] of [[`${run}/results.json`,'results.json'],[`${run}/captures.json`,'captures.json'],[`${run}/execution.log`,'execution.log'],['proof/audit/IW022/code.patch','code.patch'],['proof/audit/IW022/source-manifest.json','source-manifest.json']]){const path=`${alias}/${name}`;copyFileSync(original,path);aliases.push({original,path,sha256:hash(path)});}
const captures=JSON.parse(readFileSync(`${run}/captures.json`,'utf8'));for(const c of captures){const path=`${alias}/${c.viewport.name}-execution.png`;copyFileSync(c.path,path);aliases.push({original:c.path,path,sha256:hash(path)});}
writeFileSync(`${alias}/alias-manifest.json`,JSON.stringify({purpose:'Byte-identical aliases for existing approved tracker allowlist; originals remain in IW022 ownership',aliases},null,2));
const d=readLedger(),task=d.tasks.find(t=>t.id==='IW-022');task.inputs=Object.keys(manifest.inputs);task.status='awaiting-verification';task.summary='Real isolated IndexedDB runtime submitted:12 actual browser cases and full typecheck pass; exact source hashes and desktop local execution capture attached. User redirected to full feature testing/Python wireframes; no further runtime expansion. Independent review pending.';
task.evidence=[['patch','code.patch'],['executed','execution.log'],['source-manifest','source-manifest.json'],['alias-manifest','alias-manifest.json']].map(([kind,name])=>({kind,path:`${alias}/${name}`,sha256:hash(`${alias}/${name}`),revision:task.revision,inputDigest:inputDigest(task)}));
for(const c of captures){const path=`${alias}/${c.viewport.name}-execution.png`;task.evidence.push({kind:c.viewport.name==='desktop'?'execution-capture':'historical-optional-mobile',path,sha256:hash(path),revision:task.revision,inputDigest:inputDigest(task),screenshot:{url:c.url,time:c.capturedAt,timeLabel:'captured at',viewport:{width:c.viewport.width,height:c.viewport.height},captureDimensions:validatePng(readFileSync(path)),scenario:`Actual IndexedDB runtime execution · ${c.viewport.name}`,classification:c.viewport.name==='desktop'?'backend report · awaiting independent review':'historical optional mobile capture',result:'12/12 actual browser storage/command checks pass; no app integration or estimating completion claim.',sourceIdentity:`Runtime inputs SHA manifest ${hash('proof/audit/IW022/source-manifest.json')}; exact raw results ${run}/results.json`,reportPath:`${alias}/results.json`,reportSha256:hash(`${alias}/results.json`),featured:c.viewport.name==='desktop'}});}
const gallery=d.tasks.find(t=>t.id==='IW-023');gallery.status='awaiting-verification';gallery.summary='Prior embedded gallery independently approved (review retained). User now requires desktop-only proof: policy delta pending independent review; historical mobile proof optional.';gallery.revision++;
d.proofPolicy={requiredViewport:'desktop',mobile:'optional historical only; no further mobile QA',ui:['before','after-desktop'],nonUi:['execution-capture','executed'],reason:'User explicitly removed mobile requirement and prioritized complicated plan/Python wireframe and all-feature testing.'};
for(const t of d.tasks)t.acceptance.human=t.acceptance.human.replaceAll('desktop/mobile','desktop').replaceAll('before/after desktop/mobile','before/after desktop')+' Current user policy: desktop proof required; historical mobile captures optional, no new mobile testing.';
for(const e of d.tasks.flatMap(t=>t.evidence).filter(e=>e.screenshot?.viewport?.width<600))e.screenshot.featured=false;
d.updatedAt=new Date().toISOString();for(const s of d.slices)s.status=sliceStatus(d.tasks.filter(t=>t.slice===s.id));const validation=validate(d);if(!validation.ok)throw Error(JSON.stringify(validation));writeFileSync('planning/control/ledger.json',JSON.stringify(d,null,2)+'\n');writeFileSync('planning/control/index.html',render(d));writeFileSync('planning/control/dashboard.html',render(d));
writeFileSync('INDUSTRY-WIDE-TODO.md',`# Industry-wide live to-do\n\nCurrent state: [canonical ledger](planning/control/ledger.json). The live HTML embeds actual desktop proof; older mobile captures remain historical optional. No more mobile QA.\n\n- [ ] Current user priority: enumerate every feature, assume unverified for a fresh feature run, test complicated plans and actual Python wireframe output. Preserve earlier bounded approvals historically.\n- [ ] IW-001 tracker composite approval pending; gallery implementation was independently approved separately.\n- [ ] IW-002 historical139features/359acceptance semantic crosswalk in progress.\n- [ ] IW-003 baseline cold-start independent gate remains open; original zoom defect documented.\n- [ ] IW-004 full core/legacy verification waits stable transitive domain/calibration inputs.\n- [ ] IW-005 source/overlay repair under actual SVG/PDF/built proof.\n- [ ] IW-021 original independent verification packet submitted.\n- [ ] IW-022 runtime foundation submitted:12 real browser cases/typecheck pass; independent review pending.\n- [ ] IW-023 gallery prior independent approval preserved; new desktop-only policy delta pending review.\n\nWhole slices and release remain open. Read task handovers and exact source-bound evidence instead of inferring completion from old counts.\n`);
console.log(JSON.stringify({validation,runtimeManifest:manifest,alias},null,2));
