import {writeFile} from 'node:fs/promises';
import {hostname} from 'node:os';
if(hostname().toLowerCase()!=='dans1')throw Error('Wrong host');
const base='C:/Users/danie/XRayBuilds/industry-visible-20260913/hvac-wrap';
const pages=await(await fetch('http://127.0.0.1:9342/json/list')).json();
const page=pages.find(p=>p.id==='C881A561953E464791A17AF4579C59F6');
if(!page||!page.url.startsWith('http://127.0.0.1:8095/'))throw Error('Wrong page');
const ws=new WebSocket(page.webSocketDebuggerUrl);await new Promise((yes,no)=>{ws.onopen=yes;ws.onerror=no});let id=0;const pending=new Map();ws.onmessage=({data})=>{const m=JSON.parse(data),p=pending.get(m.id);if(p){pending.delete(m.id);clearTimeout(p.timer);m.error?p.no(Error(JSON.stringify(m.error))):p.yes(m.result)}};
const call=(method,params={})=>new Promise((yes,no)=>{const n=++id,timer=setTimeout(()=>no(Error('deadline '+method)),20000);pending.set(n,{yes,no,timer});ws.send(JSON.stringify({id:n,method,params}))});
const evaluate=async(expression)=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
const click=async(text)=>evaluate(`(()=>{const b=[...document.querySelectorAll('button,summary')].find(e=>e.textContent.trim()===${JSON.stringify(text)});if(!b)throw Error('missing '+${JSON.stringify(text)});b.click()})()`);
const wait=async(selector)=>evaluate(`new Promise((resolve,reject)=>{if(document.querySelector(${JSON.stringify(selector)}))return resolve(true);const o=new MutationObserver(()=>{if(document.querySelector(${JSON.stringify(selector)})){o.disconnect();resolve(true)}});o.observe(document.body,{subtree:true,childList:true,attributes:true});setTimeout(()=>{o.disconnect();reject(Error('wait timeout'))},10000)})`);
const fill=async(suffix,text)=>{await evaluate(`(()=>{const e=document.querySelector('input[id$="'+${JSON.stringify(suffix)}+'"]');if(!e)throw Error('missing field');e.focus();e.select()})()`);await call('Input.insertText',{text})};
const snapshot=async()=>evaluate(`({at:new Date().toISOString(),text:document.querySelector('.industry-draft-host').innerText,save:document.querySelector('.industry-draft-host').dataset.draftSave,inputs:[...document.querySelectorAll('.industry-form input')].map(e=>({id:e.id,value:e.value,checked:e.checked})),result:document.querySelector('.industry-result')?.innerText})`);
try {
await evaluate(`document.querySelector('textarea').focus()`);
await call('Input.insertText',{text:'Use the actual calculate_draft_duct_wrap tool now for this explicit synthetic worksheet comparison. Supply duct.sections=[{id: "HVAC-UI-1", shape: "rectangular", lengthM: {value:10, sourceReference:"Synthetic UI length supplied by user"}, widthM:{value:0.5,sourceReference:"Synthetic UI width supplied by user"}, heightM:{value:0.3,sourceReference:"Synthetic UI height supplied by user"}}]. Supply wraps=[{sectionId:"HVAC-UI-1",insulationThicknessM:{value:0.025,sourceReference:"Synthetic wrap thickness explicitly supplied"},longitudinalOverlapM:{value:0.05,sourceReference:"Synthetic longitudinal lap explicitly supplied"}}]. These values were observed in the manual worksheet, which displayed 18.5 m² wrap; independently calculate using the supplied operands and compare. Do not claim to have read the stored form. No project edits, saving, importing, drawing or calibration. Report the actual tool receipt, outer area, lap area, total wrap, exclusions and draft/verified quote eligibility. Explain the actual returned calculationSteps substitution faithfully: thickness applies twice to width and twice to height. Verify the working matches the receipt, and include a concise Developer review grounded in this turn.'});
await evaluate(`document.querySelector('button[aria-label="Send assistant message"]').click()`);
console.log('Persistence verified and wrap tool prompt sent');
}finally{ws.close()}