import {readFileSync,writeFileSync,readdirSync,existsSync,statSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
const digest=(bytes,algorithm='sha256')=>createHash(algorithm).update(bytes).digest('hex');
const base='planning/handovers/IW-STAGED-DELIVERY/',own='proof/audit/IW-STAGED-DELIVERY/';
const closure=JSON.parse(readFileSync(base+'06-canonical-closure.json','utf8')),proposal=JSON.parse(readFileSync(base+'06-audit-ledger.json','utf8')),snapshot=JSON.parse(readFileSync('proof/audit/IW-HISTORICAL-SOURCE/manifest.json','utf8'));
const paths=new Set([...proposal.source.map(f=>f.path),...closure.references.filter(r=>r.exists).map(r=>r.path),'.gitignore','planning/control/current-work.json','proof/audit/IW-HISTORICAL-SOURCE/manifest.json',...snapshot.files.map(f=>f.snapshotPath),'scripts/industry-ledger.test.mjs','proof/audit/IW-FULL-FEATURES/feature-gate.test.mjs','proof/audit/IW-FULL-FEATURES/image-csp.test.mjs','proof/audit/IW-FULL-FEATURES/inventory.json']);
for(const file of readdirSync(base))if(/\.(md|json|txt)$/.test(file)&&!['06-stage-manifest.json','06-stage-paths.txt'].includes(file))paths.add(base+file);
for(const file of readdirSync(own))if((file.startsWith('06-')||['historical-scope.test.mjs','historical-browser.mjs','prepare-stage06.mjs'].includes(file))&&statSync(own+file).isFile())paths.add(own+file);
for(const file of readdirSync(own+'browser-2026-09-05T09-04-19-950Z'))paths.add(own+'browser-2026-09-05T09-04-19-950Z/'+file);
for(const name of ['01-neutral-core','02-local-runtime','03-frozen-python-protocol','04-source-viewport-ui','05-bounded-python-geometry','06-audit-ledger'])for(const p of JSON.parse(readFileSync(base+name+'.json','utf8')).textProofCandidates)if(p.startsWith('planning/handovers/')&&existsSync(p))paths.add(p);
function walk(dir){for(const f of readdirSync(dir,{withFileTypes:true})){const p=dir+'/'+f.name;if(f.isDirectory())walk(p);else if(/\.(json|txt|log|patch|png|mjs|md)$/.test(p))paths.add(p);}}
walk('proof/audit/IW-FULL-FEATURES-FINAL-REVIEW');
const head=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),tree=new Map(execFileSync('git',['ls-tree','-r','-z','HEAD'],{encoding:'utf8'}).split('\0').filter(Boolean).map(line=>{const tab=line.indexOf('\t');return[line.slice(tab+1),line.slice(0,tab).split(' ')[2]];}));
const records=[...paths].sort().map(path=>{if(/IW-REAL-3D|npm-cache|python-deps|mcp-deps|legacy-browser|\.exe$|^startup\./.test(path))throw Error('Forbidden candidate '+path);const bytes=readFileSync(path),blob=digest(Buffer.concat([Buffer.from('blob '+bytes.length+'\0'),bytes]),'sha1');return{path,sha256:digest(bytes),bytes:bytes.length,needsStaging:tree.get(path)!==blob};});
const metadataPaths=[base+'06-stage-manifest.json',base+'06-stage-paths.txt'];const report={at:new Date().toISOString(),status:'proposed; parent review required before staging',baseHead:head,canonicalSha256:digest(readFileSync('planning/control/ledger.json')),currentSourceChangesExcluded:true,metadataPaths,files:records};writeFileSync(metadataPaths[0],JSON.stringify(report,null,2)+'\n');writeFileSync(metadataPaths[1],[...records.filter(f=>f.needsStaging).map(f=>f.path),...metadataPaths].join('\n')+'\n');console.log(JSON.stringify({candidateFiles:records.length,stagingFiles:records.filter(f=>f.needsStaging).length+2,bytes:records.filter(f=>f.needsStaging).reduce((n,f)=>n+f.bytes,0),canonicalSha256:report.canonicalSha256}));
