import {chromium} from 'playwright';import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';import {resolve} from 'node:path';
const seed=process.argv.includes('--seed'),phase=seed?'before':'after-final03',url='http://127.0.0.1:8081/',out='screenshots/industry-transform/legacy';mkdirSync(out,{recursive:true});
const report={at:new Date().toISOString(),url,scenario:seed?'Actual old-build saved-source workflow':'Reopen the same browser profile on corrected production build',injection:false,viewport:{width:1280,height:800},ok:false};
const context=await chromium.launchPersistentContext(resolve('proof/audit/IW005/legacy-browser'),{headless:true,channel:'msedge',acceptDownloads:true,viewport:report.viewport});const page=await context.newPage();
try{await page.goto(url);await page.locator('[data-hydration-status="ready"]').waitFor();
 if(seed){const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Open plan',exact:true}).first().click();await(await chooser).setFiles(resolve('engine/fixtures/svg/sample-plan.svg'));await page.getByRole('button',{name:'Measure',exact:true}).click();await page.getByLabel('Known distance',{exact:true}).fill('12');await page.getByRole('button',{name:'Pick two points',exact:true}).click();const c=page.locator('.measure-document-preview canvas');await c.scrollIntoViewIfNeeded();const box=await c.boundingBox();await c.click({position:{x:box.width*.2,y:box.height*.4}});await c.click({position:{x:box.width*.7,y:box.height*.4}});await page.getByRole('button',{name:'Lock scale',exact:true}).click();await page.getByRole('button',{name:/^Run L$/}).click();await c.click({position:{x:box.width*.2,y:box.height*.55}});await c.click({position:{x:box.width*.7,y:box.height*.55}});await page.getByRole('button',{name:'Finish trace',exact:true}).click();}
 else{await page.getByRole('button',{name:'Measure',exact:true}).click();await page.getByText('Saved measurements need source-coordinate recovery',{exact:true}).waitFor();if(!(await page.getByRole('button',{name:/^Run L$/}).isDisabled()))throw Error('Legacy trace tools are enabled');await page.getByText('Legacy coordinates are preserved, but their source alignment is unverified.',{exact:false}).waitFor();}
 const path=`${out}/${phase}.png`;await page.screenshot({path,fullPage:true});report.capture={path,url,capturedAt:new Date().toISOString(),viewport:report.viewport,scenario:report.scenario,verdict:'pass'};
 if(seed)await page.getByRole('button',{name:'Proof',exact:true}).click();else await page.getByRole('button',{name:'Open Proof for export',exact:true}).click();if(!seed){const cdp=await context.newCDPSession(page);await cdp.send('Browser.setDownloadBehavior',{behavior:'deny'});}const event=page.waitForEvent('download');await page.getByRole('button',{name:'Export current manifest',exact:true}).click();const download=await event;const file=`proof/audit/IW005/legacy-${phase}-manifest.json`;const payload=await page.evaluate(async url=>await(await fetch(url)).text(),download.url());writeFileSync(file,payload);report.exportRead='actual UI download blob, read directly because persistent Edge download.saveAs failed';
 if(!seed){const before=JSON.parse(readFileSync('proof/audit/IW005/legacy-before-manifest.json')),after=JSON.parse(readFileSync(file));for(const field of ['runs','gates','calibrations'])if(JSON.stringify(before.job[field])!==JSON.stringify(after.job[field]))throw Error('Legacy evidence mutated: '+field);if(!JSON.stringify(after.readiness).includes('legacy source coordinates'))throw Error('Legacy quantity authority not blocked');report.evidencePreserved=true;}
 report.ok=true;
}catch(error){report.error=String(error);process.exitCode=1;}finally{await context.close();writeFileSync(`proof/audit/IW005/legacy-${phase}.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));}
