import{readFileSync,writeFileSync,readdirSync,statSync}from'node:fs';import{execFileSync}from'node:child_process';import{createHash}from'node:crypto';
const root='proof/audit/IW005/',hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex');
const tracked=['src/studio/CalibrationPanel.tsx','src/studio/DocumentPreview.tsx','src/studio/IsoCanvas.tsx','src/studio/Studio.tsx','src/studio/bomCompiler.test.ts','src/studio/bomCompiler.ts','src/studio/calibration.ts','src/studio/calibrationStore.test.ts','src/studio/documentPreview.test.ts','src/studio/domain.test.ts','src/studio/domain.ts','src/studio/store.ts','src/studio/tracingStore.test.ts','src/styles.css','scripts/preview-built.mjs'];const added=['src/studio/documentViewport.ts','src/studio/documentViewport.test.ts'];
const record=p=>({path:p,bytes:statSync(p).size,sha256:hash(p)});writeFileSync(root+'source-files.json',JSON.stringify({head:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),files:[...tracked,...added].map(record)},null,2));
const newPatch=p=>{const text=readFileSync(p,'utf8').replace(/\r\n/g,'\n');const lines=text.split('\n');if(lines.at(-1)==='')lines.pop();return `diff --git a/${p} b/${p}\nnew file mode 100644\n--- /dev/null\n+++ b/${p}\n@@ -0,0 +1,${lines.length} @@\n`+lines.map(l=>'+'+l).join('\n')+'\n';};
const patch=execFileSync('git',['diff','--',...tracked],{encoding:'utf8',maxBuffer:10e6})+added.map(newPatch).join('');writeFileSync(root+'code.patch',patch);
const walk=p=>readdirSync(p).flatMap(n=>{const q=p+'/'+n;return statSync(q).isDirectory()?(n==='legacy-browser'?[]:walk(q)):[q];});const harness=walk(root.slice(0,-1)).filter(p=>/\.(mjs|svg|dxf)$/.test(p));writeFileSync(root+'submission.patch',patch+[...harness,'planning/handovers/IW005/startup.md','planning/handovers/IW005/completion.md'].map(newPatch).join(''));
const reports=['dev-final01.json','built-sealed01.json','formats-dev-final01.json','formats-built-sealed01.json','loading-dev.json','loading-built.json','svg-root-dev.json','svg-root-built.json','legacy-before.json','legacy-after-final03.json'];let captures=[];for(const p of reports){const r=JSON.parse(readFileSync(root+p));if(!r.ok)throw Error(p+' not passing');captures.push(...(r.captures||[]),...(r.capture?[r.capture]:[]));}
writeFileSync(root+'screenshot-manifest.json',JSON.stringify({task:'IW005',status:'awaiting-verification',createdAt:new Date().toISOString(),note:'Final acceptance desktop only; earlier mobile captures historical. No state injection.',captures:captures.map(c=>({...c,...record(c.path)}))},null,2));
const files=[...tracked,...added,'planning/handovers/IW005/startup.md','planning/handovers/IW005/completion.md',...walk(root.slice(0,-1)).filter(p=>!p.endsWith('submission-manifest.json')),...walk('screenshots/industry-transform')];writeFileSync(root+'submission-manifest.json',JSON.stringify({task:'IW005',status:'awaiting-verification',createdAt:new Date().toISOString(),files:[...new Set(files)].map(record)},null,2));console.log(JSON.stringify({files:files.length,manifestSha256:hash(root+'submission-manifest.json')}));
