export const DEVELOPER_MODE_KEY = 'xray:assistant-developer-mode:v1';
export function readDeveloperMode(storage: Pick<Storage,'getItem'>): boolean {
  try { return storage.getItem(DEVELOPER_MODE_KEY) !== 'false'; } catch { return true; }
}
export const DEVELOPER_REVIEW_INSTRUCTION = `Developer mode is ON. After completing this instruction/task, append a short section titled "Developer review" with at most three bullets: Outcome, Friction, Improvement. Judge the CURRENT USER-VISIBLE RESPONSE against the user's current requested outcome: did it answer clearly, accurately and without unnecessary repetition? Assess the answer actually delivered, not a hidden candidate answer, prior response or prior work packet. Describe the useful answer or actual result, not internal workflow labels such as "discussion route". Assess your own mistakes, verbosity and clarity, not flaws in the user's workflow. Existing supplied evidence is sufficient for an explanation or recording review; absence of new tool calls, fresh evidence, a screenshot or a readback is NOT a shortcoming in those tasks. Recommend verification only when the requested action or a specific unsupported claim actually needs it; never add it as a ritual. An improvement should correct a specific problem in this response, not expand the user's task. If no specific problem is evident, say so briefly rather than manufacturing one. Distinguish context supplied automatically from tools you executed in this turn. Claim current-turn actions only from current-turn execution receipts; prior packet receipts do not prove a new call. read_workbench_structure is a static capability reference, not a fresh project-state readback. Naming a reviewer or decision owner cannot confer verified human authority or unblock review_takeoff_item; respect the current work packet's authority gate and do not recommend a name as its fix. Use only available evidence and actual receipts; do not invent success, user satisfaction, scores or tests. This is your self-assessment, not independent verification. Keep it under 70 words, separate from the answer. Do not call tools or repeat project actions solely to write this review.`;
export function developerReviewInstruction(recordingReview = false): string {
  return DEVELOPER_REVIEW_INSTRUCTION + (recordingReview ? '\nThis task reviews a supplied recording only. Evaluate whether your explanation faithfully describes those events and is concise. The app already supplies the counts and map: do not duplicate them. Do not suggest gathering fresh evidence or citing a readback to establish the current project state; that state is outside this request. Do not fault navigation for not producing drawings or measurements.' : '');
}
export function hasDeveloperReview(text:string):boolean { return /(?:^|\n)\s*(?:#{1,6}\s*)?(?:\*\*)?Developer review(?:\*\*)?\s*:?\s*\n\s*\S/i.test(text); }
