import {writeFileSync} from 'node:fs';
const c=[['open','http://127.0.0.1:8080/'],['set','viewport','1440','900'],['wait','--fn',"document.querySelectorAll('[data-top-row]').length===3"],['eval',"for(const id of ['header','navigation','mode'])localStorage.removeItem('xray:top-row:'+id+':v1')"],['reload'],['wait','--fn',"!!document.querySelector('.live-assistant-launcher')"],['click','.live-assistant-launcher']];
const aligned="Math.abs(document.querySelector('.live-assistant-panel').getBoundingClientRect().top-document.querySelector('.studio-layout').getBoundingClientRect().top)<2";
for(const [id,label]of [['header','header'],['navigation','navigation'],['mode','workspace info']]){
 c.push(['eval',`window.rowBefore=document.querySelector('[data-top-row=${id}]').getBoundingClientRect().height`],['focus',`[aria-label="Resize ${label}"]`],['press','ArrowDown'],['wait','--fn',`document.querySelector('[data-top-row=${id}]').getBoundingClientRect().height>window.rowBefore+6`],['wait','--fn',aligned],['find','role','button','click','--name',`Collapse ${label}`,'--exact'],['wait','--fn',`document.querySelector('[data-top-row=${id}]').getBoundingClientRect().height===18`],['wait','--fn',aligned]);
}
c.push(['screenshot','screenshots/gemini-dubai-capacity/top-menus-collapsed.png'],['reload'],['wait','--fn',"document.querySelectorAll('[data-top-row][data-collapsed=true]').length===3"]);
for(const label of ['header','navigation','workspace info'])c.push(['find','role','button','click','--name',`Expand ${label}`,'--exact']);
c.push(['eval',"for(const e of document.querySelectorAll('[data-top-row]')){const h=JSON.parse(localStorage.getItem('xray:top-row:'+e.dataset.topRow+':v1')).height;if(Math.abs(e.getBoundingClientRect().height-h)>2)throw Error('Saved row height not restored')}"],['screenshot','screenshots/gemini-dubai-capacity/top-menus-desktop.png'],['set','viewport','1024','768'],['find','role','button','click','--name','Model','--exact'],['wait','--fn',"document.querySelector('.workspace-rails').dataset.pane==='model'"],['eval',"for(const b of document.querySelectorAll('.top-row-toggle')){const r=b.getBoundingClientRect();if(r.right>innerWidth||r.left<0||!b.contains(document.elementFromPoint(r.left+r.width/2,r.top+r.height/2)))throw Error('Top collapse button clipped or covered')}"],['screenshot','screenshots/gemini-dubai-capacity/top-menus-tablet.png'],['errors']);
writeFileSync(new URL('./top-menus.scenario.json',import.meta.url),JSON.stringify(c,null,2));
