import {readFileSync,writeFileSync} from 'node:fs';
import {readLedger} from '../../../scripts/industry-ledger.mjs';
let code=readFileSync('scripts/industry-ledger.mjs','utf8');
code=code.replace("['tasks','dependencies','decisions','inventory','external','handover']","['features','tasks','dependencies','decisions','inventory','external','handover']");
code=code.replace('<section data-panel="tasks" aria-label="Tasks">','${featureAuditView(data)}<section data-panel="tasks" aria-label="Tasks" hidden>');
code=code.replace('${screenshotGallery(data)}<nav','${data.fullFeatureAudit?`<p class="notice"><strong>Fresh feature audit: ${data.fullFeatureAudit.features.filter(f=>f.status===\'untested\').length} untested · ${data.fullFeatureAudit.features.filter(f=>f.status===\'fail\').length} failed · ${data.fullFeatureAudit.features.filter(f=>f.status===\'pass\').length} passed.</strong> <a href="#feature-audit">See every feature and its test scenario</a>. Real-PDF wireframe baseline failed; no successful process exit is treated as usable geometry.</p>`:\'\'}${screenshotGallery(data)}<nav');
code=code.replace("const explicit=new Set([...HISTORICAL", "const explicit=new Set([...(data.fullFeatureAudit?.features??[]).flatMap(f=>f.evidence??[]).map(e=>e.path).filter(p=>/^proof\\/audit\\/IW-[A-Z0-9-]+\\//.test(p)),...HISTORICAL");
writeFileSync('scripts/industry-ledger.mjs',code);
let js=readFileSync('planning/control/dashboard.js','utf8');js=js.replace("let active='tasks';","let active=document.querySelector('[data-panel=features]')?'features':'tasks';\nconst taskStatuses=[...status.options].map(o=>({value:o.value,label:o.textContent}));\nconst featureStatuses=['all','untested','running','pass','fail','blocked','notimplemented'];\nfunction statusOptions(){status.replaceChildren(...(active==='features'?featureStatuses.map(value=>({value,label:value==='all'?'All feature states':value})):taskStatuses).map(o=>{const option=document.createElement('option');option.value=o.value;option.textContent=o.label;return option;}));status.disabled=!['tasks','features'].includes(active);}\nstatusOptions();");
js=js.replace("active!=='tasks' || status.value", "!['tasks','features'].includes(active) || status.value");js=js.replace("status.disabled=active!=='tasks';","statusOptions();");writeFileSync('planning/control/dashboard.js',js);
const d=readLedger(),audit=d.fullFeatureAudit;for(const f of audit.features){if(f.id.startsWith('DISC-')){f.id=f.id.replace('DISC-','NEW-');f.group='NEW';}const p=f.id.split('-')[0];f.owner=['UI','SITE','TRACE','TAKE','QUOTE','DATA','LEG'].includes(p)?'iw_sc01_tracker':['ENG','MCP'].includes(p)||f.id==='NEW-009'?'iw_sc02_contract':'audit_engine_release';}
for(const id of ['TRACE-016','DATA-001']){const f=audit.features.find(f=>f.id===id);f.status='fail';f.result='Fresh cross-sheet legacy edit/history bypass reproduced by coordinate owner in4 regressions (move/remove/undo/redo). Narrow guards corrected; exact feature-case rerun and new build proof pending independent review. Aggregate260tests is not this feature approval.';}
audit.groups=Object.fromEntries([...new Set(audit.features.map(f=>f.group))].map(g=>[g,audit.features.filter(f=>f.group===g).length]));audit.assignment={desktopUI:{owner:'iw_sc01_tracker',ids:audit.features.filter(f=>f.owner==='iw_sc01_tracker').map(f=>f.id)},python:{owner:'iw_sc02_contract',ids:audit.features.filter(f=>f.owner==='iw_sc02_contract').map(f=>f.id)},releaseTransportTooling:{owner:'audit_engine_release',ids:audit.features.filter(f=>f.owner==='audit_engine_release').map(f=>f.id)}};d.updatedAt=new Date().toISOString();writeFileSync('planning/control/ledger.json',JSON.stringify(d,null,2)+'\n');writeFileSync('proof/audit/IW-FULL-FEATURES/inventory.json',JSON.stringify(audit,null,2)+'\n');console.log(JSON.stringify({groups:audit.groups,owners:Object.fromEntries(Object.entries(audit.assignment).map(([k,v])=>[k,v.ids.length]))},null,2));
