import {readFileSync,writeFileSync} from 'node:fs';
import {readLedger,validate,render} from '../../../scripts/industry-ledger.mjs';
const d=readLedger(),a=d.fullFeatureAudit,get=id=>a.features.find(f=>f.id===id);
for(const id of ['NEW-010','NEW-011'])Object.assign(get(id),{group:'NEW',kind:'newly-explicit-subfeature',implementationSource:id==='NEW-010'?'engine/python/xray/source_wireframe.py':'src/studio/engine.ts; src-tauri/src/lib.rs; engine/host/src/lib.rs',scopeNote:id==='NEW-010'?'Partial 2D path presentation; no semantic reconstruction':'Product import does not invoke Python extraction'});
for(const id of ['QUOTE-001','QUOTE-002','QUOTE-003','QUOTE-004']){const f=get(id);for(const c of f.cases??[])if(c.id==='UI01-cost-no-recipe-recovery'){c.status='blocked-upstream';c.detail='Empty-job Cost recovery was unavailable. This case did not reach or independently disprove this downstream capability.';}f.status=id==='QUOTE-004'?'notimplemented':'blocked';f.result=id==='QUOTE-004'?'Send to Looplet is intentionally disabled; no transport integration is implemented. The upstream empty-job recipe recovery observation is not a transport execution failure.':'The tested empty-job flow stopped at the unavailable recipe recovery action. This downstream capability was not reached; a populated, prerequisite-satisfied test is still required.';}
const shortcuts=get('TRACE-011');shortcuts.status='running';for(const c of shortcuts.cases??[])if(c.id==='UI02-associated-gate'){c.status='author-pass-activation-only';c.detail='C activated Gate mode. The subsequent click on the run was intercepted by selection; that pointer defect belongs to TRACE-003.';}shortcuts.result='Enter committed actual run and area traces; C activated Gate mode. Pointer placement on the run failed separately under TRACE-003. Other shortcut cases remain unverified.';
const history=get('TRACE-016');history.status='running';history.result='Initial fresh audit reproduced four cross-sheet move/remove/undo/redo failures. A narrow affected-entity sheet guard fixed those reproductions. Root independently reran seven targeted legacy/target/cross/history tests and inspected v2 built proof; all seven passed. Batch02 normal UI undo/redo also passed its author case. Full per-sheet history acceptance remains pending; original failure artifacts are retained.';
get('LEG-004').result+=' External render providers remain not implemented and disabled; local camera/brief actions are distinct working author cases.';
d.updatedAt=new Date().toISOString();const v=validate(d);if(!v.ok)throw Error(JSON.stringify(v));writeFileSync('planning/control/ledger.json',JSON.stringify(d,null,2)+'\n');writeFileSync('proof/audit/IW-FULL-FEATURES/inventory.json',JSON.stringify(a,null,2)+'\n');for(const p of ['index','dashboard'])writeFileSync(`planning/control/${p}.html`,render(d));
const p='proof/audit/IW-FULL-FEATURES/capture-feature-index.mjs';writeFileSync(p,readFileSync(p,'utf8').replace("await row.locator('img').first().evaluate(img=>img.decode());","await row.locator('img').evaluateAll(imgs=>Promise.all(imgs.map(img=>{img.loading='eager';return img.decode();})));"));console.log('Precise direct failures / upstream blockers / unimplemented transport and historical fixes recorded.');
