import {readFileSync,writeFileSync,mkdirSync,existsSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {buildLoopletQuoteLines,pushToLoopletCrm} from '../../../src/studio/crmBridge.ts';
import {queueSyncItem,flushSyncQueue} from '../../../src/studio/sync.ts';
import {importPlanFile} from '../../../src/studio/engine.ts';
import assert from 'node:assert/strict';
const stamp=new Date().toISOString().replaceAll(':','-').replaceAll('.','-'),base=`proof/audit/IW-FULL-FEATURES/release-${stamp}`;mkdirSync(base,{recursive:true});const cases=[],inputs=['src/studio/crmBridge.ts','src/studio/sync.ts','src/studio/engine.ts','src/studio/documents.ts','src/studio/documentContract.ts','src-tauri/src/lib.rs','src-tauri/tauri.conf.json','engine/host/src/lib.rs','vite.config.spa.ts','.github/workflows/ci.yml','scripts/build-sidecar.mjs','.grok/app-env.json'],hashes=Object.fromEntries(inputs.map(p=>[p,createHash('sha256').update(readFileSync(p)).digest('hex')]));
async function record(id,ids,fn){try{cases.push({id,ids,...await fn()});}catch(e){cases.push({id,ids,status:'probe-error',result:String(e)});}}
await record('actual-web-import',['NEW-011'],async()=>{const p=await importPlanFile(new File(['<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><path d="M0 0L100 100"/></svg>'],'plan.svg',{type:'image/svg+xml'}));assert.equal(p.takeoff,null);return{status:'notimplemented',result:'Actual importPlanFile returned inspected original SVG bytes and takeoff:null. Native source independently also returns None; no extraction/wireframe invocation exists in the UI import flow.',actual:p};});
await record('actual-crm-handoff',['CRM-002','CRM-003','INT-001','QUOTE-004'],async()=>{const draft=buildLoopletQuoteLines([],[],'plan.svg',0),result=pushToLoopletCrm(draft);assert.equal(result.success,false);assert.equal(result.url,null);return{status:'notimplemented',result:'Actual bridge call refuses handoff and returns no URL. No authenticated transport or receipt is implemented.',actual:result};});
await record('actual-sync-boundary',['SYNC-001','INT-002'],async()=>{assert.throws(()=>queueSyncItem({jobId:'probe',planName:'plan.svg',action:'save_markup',payload:{}}),/unavailable/);const result=await flushSyncQueue();assert.equal(result.blocked,true);assert.equal(result.synced,0);return{status:'notimplemented',result:'Actual queue creation throws; flush returns blocked with zero synced. This executes the compatibility boundary, not a server request.',actual:result};});
await record('tauri-frontend-entry',['DESK-007'],async()=>{const config=JSON.parse(readFileSync('src-tauri/tauri.conf.json'));assert.equal(existsSync('index.html'),false);return{status:'fail',result:'Tauri beforeBuildCommand selects the legacy Vite SPA config, whose default root index.html does not exist. Exact build execution is deferred to avoid replacing shared output; missing required entry is directly verified.',actual:{command:config.build.beforeBuildCommand,entryExists:false}};});
await record('sidecar-packaging-contract',['DESK-008'],async()=>{const run=spawnSync(process.execPath,['scripts/build-sidecar.mjs','--dry-run'],{encoding:'utf8'});writeFileSync(`${base}/sidecar-dry.log`,run.stdout+run.stderr);assert.equal(run.status,0);const config=JSON.parse(readFileSync('src-tauri/tauri.conf.json'));return{status:'fail',result:'Reviewed dry run exits0 after checking Python entry existence only. Tauri bundle has no externalBin and bundles Python source, not the frozen executable. No packaged sidecar was executed.',actual:{externalBin:config.bundle.externalBin??null,resources:config.bundle.resources,dryExit:run.status}};});
await record('auth-off-contract',['SEC-001','AUTH-001'],async()=>{const env=JSON.parse(readFileSync('.grok/app-env.json'));assert.equal(env.VITE_AUTH_ENABLED,'false');return{status:'notimplemented',result:'Authentication is explicitly off by user-approved project policy. Local actor attribution is not authenticated identity or tenancy.',actual:{authEnabled:env.VITE_AUTH_ENABLED}};});
writeFileSync(`${base}/results.json`,JSON.stringify({at:new Date().toISOString(),inputs:hashes,cases,limits:'Local module calls and source/config contract checks only; no remote service, packaged executable, migration, installer or CI run invoked.'},null,2));writeFileSync(`${base}/execution.log`,cases.map(c=>`${c.id}: ${c.status}\n${c.result}\n${JSON.stringify(c.actual??{})}`).join('\n\n'));console.log(base);console.log(JSON.stringify(cases.map(({id,status,result})=>({id,status,result})),null,2));
