import {readFileSync,writeFileSync,appendFileSync} from 'node:fs';
import {createServer} from 'node:http';
import {chromium} from 'playwright';
import {readLedger,hash,validate,validatePng,render} from '../../../scripts/industry-ledger.mjs';
const base='proof/audit/IW-FULL-FEATURES/lane-2026-09-05T06-27-55-466Z',report=JSON.parse(readFileSync(`${base}/conclusions.json`)),local='proof/audit/IW-FULL-FEATURES/local-gates-2026-09-05T06-29-30-620Z',web='proof/audit/IW-FULL-FEATURES/web-2026-09-05T06-24-53-454Z',sha=p=>hash(readFileSync(p)),esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;');
const map={
'NEW-001':['rejects missing/hash-mismatched/future source identity and out-of-range pages','rejects forged results, stale review, missing evidence, nonfinite coordinates and extra keys','preserves immutable source/evidence/calibration identity','requires rereview after operand or work-package changes','allows review-only transitions and rejects lost history/revision conflicts'],
'NEW-002':['electrical counts need evidence and no calibration or fence fields','rejects count item evidence pointing only to another document','rejects duplicate count items within and across measurements'],
'NEW-003':['measures plumbing polyline length with evidenced deductions','measures flooring area independently of polygon winding','rejects zero/negative/nonfinite/inconsistent or unevidenced scale','rejects self-crossing, overlapping, degenerate and repeated polygon vertices','rejects positive length, area and volume underflow rather than certifying zero'],
'NEW-004':['concrete volume requires explicit cross-document evidenced depth','supports verified native model volume with explicit units/property','rejects absent/zero/negative/unevidenced depth without guessing','binds native volume to the exact measured and evidenced model property'],
'NEW-005':['preserves complete v1 and v2 originals, IDs, revisions, assets and historical snapshots','rejects corrupt and future jobs without writing or accepting partial data']};
for(const r of report.rows){r.auditStatus='concluded';r.testOutcome=['pass','running'].includes(r.status)?'executed scoped checks; remaining acceptance explicit':r.status;r.remaining=[];if(r.id==='DESK-007')r.conclusion='Exact legacy Vite SPA build was executed with an isolated proof outDir and DATABASE_URL removed in the child. Exit 1: Cannot resolve entry module index.html. Shared production output was not changed.';if(r.id==='WEB-002'){r.status='fail';r.conclusion='Actual manifest HTTP200, branding extension injection and desktop tutorial document render succeeded with no uncaught errors. Manifest and tutorial name the product Grok App instead of X-Ray. Physical device installation was not exercised.';}if(map[r.id]){r.independentReviewer='audit_engine_release';r.implementationAuthor='iw_sc02_contract';r.executedCases=map[r.id];r.conclusion=`Independent implementation review reran these specific cases at recorded unchanged source hashes: ${map[r.id].join('; ')}. Transitive domain/calibration hashes included. Module semantics only, no product integration. Formal feature acceptance binding remains pending.`;}if(r.status==='running'){r.status='blocked';r.remaining.push('Full declared feature acceptance or independent source-bound approval remains outstanding; local checks above are completed.');}if(['DESK-001','DESK-002','DESK-003','DESK-004','DESK-009','DESK-010'].includes(r.id))r.remaining.push('Current-source native/package or platform-specific interaction proof.');}
writeFileSync(`${base}/final-conclusions.json`,JSON.stringify(report,null,2));const html=`<!doctype html><html><meta charset="utf-8"><title>Release/tooling audit conclusions</title><style>body{font:17px/1.5 system-ui;margin:36px auto;max-width:1280px;background:#eee8d7;color:#253030}article{padding:15px 22px;margin:10px 0;background:#fffdf6;border:1px solid #c9bfa5}h1{font-size:34px}h2{font-size:20px}p{margin:8px 0}small{color:#665b48}</style><h1>52 release and tooling features: audit conclusions</h1><p>Actual executed tests, browser probes, source checks and explicit blockers. This is a captured execution report, not product UI proof. A completed audit does not mean the feature is complete.</p><p>Fresh runs: 195 script tests; 301 TypeScript tests; 34 Rust host and 24 Tauri tests; independently rerun 24 construction cases; actual empty/populated Python quote mapping. Raw logs and exact source hashes are linked in the main ledger.</p>${report.rows.map(r=>`<article><small>${esc(r.id)} · audit concluded · product ${esc(r.status)}</small><h2>${esc(r.title)}</h2><p>${esc(r.conclusion)}</p>${r.remaining.length?`<p>Still required: ${esc(r.remaining.join(' '))}</p>`:''}</article>`).join('')}</html>`;writeFileSync(`${base}/report.html`,html);const server=createServer((q,s)=>{s.writeHead(200,{'content-type':'text/html; charset=utf-8'});s.end(html);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/`,browser=await chromium.launch({headless:true,channel:'msedge'}),page=await browser.newPage({viewport:{width:1440,height:1000}});let capture;try{await page.goto(url,{waitUntil:'networkidle'});await page.screenshot({path:`${base}/desktop-conclusions.png`,fullPage:true});capture={path:`${base}/desktop-conclusions.png`,url,capturedAt:new Date().toISOString(),viewport:{width:1440,height:1000},scenario:'Actual local execution report for 52 release/tooling conclusions'};writeFileSync(`${base}/capture.json`,JSON.stringify(capture,null,2));}finally{await browser.close();await new Promise(r=>server.close(r));}
const d=readLedger();for(const r of report.rows){const f=d.fullFeatureAudit.features.find(f=>f.id===r.id);if(f.status==='pass')continue;f.status=r.status;f.auditStatus=r.auditStatus;f.testOutcome=r.testOutcome;f.remaining=r.remaining;f.result=r.conclusion;if(r.executedCases)f.independentCaseReview={reviewer:r.independentReviewer,implementationAuthor:r.implementationAuthor,cases:r.executedCases,sourceReport:`${base}/final-conclusions.json`,scope:'Independent implementation review, formal feature gate binding pending'};for(const p of [`${base}/final-conclusions.json`,`${base}/core.log`,`${base}/quote.log`,`${local}/results.json`,`${local}/legacy-build.log`,`${web}/results.json`])if(!f.evidence.some(e=>e.path===p))f.evidence.push({kind:'executed',path:p,sha256:sha(p)});f.evidence.push({kind:'execution-capture',path:capture.path,sha256:sha(capture.path),screenshot:{url,time:capture.capturedAt,timeLabel:'captured at',viewport:capture.viewport,captureDimensions:validatePng(readFileSync(capture.path)),scenario:capture.scenario,result:r.conclusion,classification:'Backend execution report; audit concluded, feature status separate',proofType:'execution-report',sourceIdentity:`Exact tested input hashes and case mapping ${base}/final-conclusions.json`,reportPath:`${base}/final-conclusions.json`,reportSha256:sha(`${base}/final-conclusions.json`),featured:false}});}
d.updatedAt=new Date().toISOString();const v=validate(d);if(!v.ok)throw Error(JSON.stringify(v));writeFileSync('planning/control/ledger.json',JSON.stringify(d,null,2)+'\n');writeFileSync('proof/audit/IW-FULL-FEATURES/inventory.json',JSON.stringify(d.fullFeatureAudit,null,2)+'\n');for(const p of ['index','dashboard'])writeFileSync(`planning/control/${p}.html`,render(d));console.log(JSON.stringify({rows:report.rows.length,capture,verdict:v}));
