import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {readLedger,render,validate} from '../../../scripts/industry-ledger.mjs';
const d=readLedger(),hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex');
const uiPrefixes=['UI','SITE','TRACE','TAKE','QUOTE','WEB'];
const scenario=(id,title,gap)=>{
 if(id==='ENG-033'||id==='MCP-007')return 'Run residential24-page, shed5-page and electrical1-page PDFs through extraction and wireframe_scene; inspect source-linked scene elements, geometry/unit/page identity and roundtrip status. Zero elements with successful roundtrip is failure.';
 if(uiPrefixes.includes(id.split('-')[0]))return `In the actual desktop app, exercise ${title} with an imported real SVG and multi-page PDF; record initial state, perform the named interaction, assert output/state and reload behavior, then capture the outcome. Specific inherited acceptance to challenge: ${gap}`;
 if(id.startsWith('ENG-')||id.startsWith('MCP-'))return `Invoke ${title} directly using a concrete PDF/DXF/SVG/IFC or deterministic adversarial fixture appropriate to its source; assert exact output plus malformed/empty/conflicting input behavior. Capture executed output as local desktop report. Specific gap: ${gap}`;
 if(id.startsWith('DESK-')||id.startsWith('REL-'))return `Exercise ${title} through its real Windows/native/artifact entrypoint only after source/tool review; capture version, actual result and desktop screenshot. If signing/clean machine/artifact is unavailable record blocked, never infer success from unit tests. Specific gap: ${gap}`;
 return `Execute the actual ${title} entrypoint with a valid scenario and an invalid/stale/restart case; compare persisted/returned output, bind current sources and capture desktop executed report. Explicitly test disabled/absent behavior instead of accepting old labels. Specific gap: ${gap}`;
};
const features=d.inventory.features.map(row=>{const cells=row.text.split('|').map(s=>s.trim()),prefix=row.id.split('-')[0];return {id:row.id,title:cells[2],group:prefix,kind:'historical-feature',historicalState:cells[3],source:row.source,sourceLine:row.line,implementationSource:cells[4],scopeNote:cells.slice(5,-1).join(' | '),status:['ENG-033','MCP-007'].includes(row.id)?'fail':'untested',owner:uiPrefixes.includes(prefix)?'iw_sc01_tracker':['ENG','MCP'].includes(prefix)?'audit_engine_release':'audit_engine_release',scenario:scenario(row.id,cells[2],cells.slice(5,-1).join(' | ')),result:['ENG-033','MCP-007'].includes(row.id)?'Fresh baseline:3 real PDFs produced0 scene elements despite successful process/roundtrip. Residential24pages1616entities7quantities; shed5pages229entities13quantities; electrical1page23entities13quantities. Repair/retest pending.':'No fresh feature-level execution accepted in this run.',evidence:['ENG-033','MCP-007'].includes(row.id)?[{path:'proof/audit/IW-PY-WIREFRAME/baseline/results.json',sha256:hash('proof/audit/IW-PY-WIREFRAME/baseline/results.json')}]:[]};});
const extra=[
 ['DISC-001','Strict trade-neutral interchange schemas and semantic validation','DATA-001','src/studio/construction/contract.ts','Parse valid count/length/area/volume jobs; reject unknown/future schemas, duplicate IDs, cross-source/page/hash evidence and unsupported native-property claims.'],
 ['DISC-002','Universal duplicate-safe count quantities','TRACE-004','src/studio/construction/quantity.ts','Count electrical/plumbing fixtures; duplicate item and repeated measurement inputs must reject or de-duplicate explicitly. Verify quantity identity against current job.'],
 ['DISC-003','Universal length and area quantities with evidence-bound scale','TRACE-007','src/studio/construction/quantity.ts','Compute a3-4-5 polyline and10x4 polygon under m/mm/ft/in evidence; reject unapproved revisions, conflicting calibration, invalid topology, underflow and stale operands.'],
 ['DISC-004','Explicit area-depth and native-property volume quantities','ENG-032','src/studio/construction/quantity.ts','Calculate200mm depth over40m2; verify8m3. Native volume must bind exact model element/property in measurement, basis and evidence; missing depth/property must reject.'],
 ['DISC-005','Caller-byte-preserving legacy adapter','DATA-001','src/studio/construction/legacy.ts','Import original v1/v2 JSON and binary assets; compare exact bytes/strings and retained records. Bind transitive domain/calibration hashes; never treat supplied hash as runtime verification.'],
 ['DISC-006','Atomic multi-job construction runtime commands and snapshots','DATA-005','src/studio/construction/runtime/repository.ts','Run fresh real IndexedDB create/open/list/archive,6 command variants, two-tab expected-revision race and transaction abort; verify immutable recovery snapshots and local review attribution.'],
 ['DISC-007','Original source rehash and bounded byte retrieval','DATA-004','src/studio/construction/runtime/repository.ts','Load actual originals, corrupt stored bytes, omit originals and exceed100MiB; reject invalid content without writing heads/snapshots; returned buffers must be defensive copies.'],
 ['DISC-008','Local proof gallery and hash-bound completion gate','CI-007','scripts/industry-ledger.mjs','Open actual desktop8097, decode image thumbnails/full-size links; reject fake/truncated PNG, inaccessible reports, stale hashes, forged/self review and logs-only completion; desktop is required, mobile optional.'],
 ['DISC-009','Frozen job-to-BOM Python CLI protocol','ENG-036','engine/python/xray/cli.py','Run contract-status --json and job-to-bom --request-stdin --result against current valid/invalid fixtures; assert request identity, deterministic artifact, typed rejection and stdout/stderr contract.'],
];
for(const [id,title,parentId,implementationSource,testScenario]of extra)features.push({id,title,parentId,group:'DISC',kind:'newly-explicit-subfeature',surface:'module/CLI/control-tool; do not imply app integration',historicalState:null,source:implementationSource,sourceLine:null,implementationSource,scopeNote:'Explicit subfeature discovered from current implementation, linked to prior broad feature instead of replacing it.',status:'untested',owner:'audit_engine_release',scenario:testScenario,result:'Earlier unit/runtime/gallery proof remains historical; fresh independent feature assertion pending.',evidence:[]});
const groups=Object.fromEntries([...new Set(features.map(f=>f.group))].map(g=>[g,features.filter(f=>f.group===g).length]));
const audit={runId:'IW-FULL-FEATURES-2026-09-05',startedAt:new Date().toISOString(),policy:'Desktop only. Assume every capability unverified until fresh concrete test. Prior approvals retained historically.',baselineFeatures:139,acceptanceRows:359,newExplicitSubfeatures:extra.length,total:features.length,groups,features,assignment:{ui:{owner:'iw_sc01_tracker',ids:features.filter(f=>uiPrefixes.includes(f.group)).map(f=>f.id),packet:'Actual desktop UI interactions and dev/built evidence. No app writes unless parent assigns a reproduced defect.'},engine:{owner:'audit_engine_release',ids:features.filter(f=>!uiPrefixes.includes(f.group)).map(f=>f.id),packet:'Review and run safe existing engine/CLI/storage/negative suites, map exact scenarios to feature IDs, independently review Python wireframe owner output. Native/external unavailable gates remain blocked with reasons.'},pythonWireframe:{owner:'iw_sc02_contract (parent runtime reassignment)',ids:['ENG-003','ENG-033','MCP-007'],packet:'Complicated real PDFs; source-aware nonempty wireframe repair and proof under parent assignment. Do not claim full building reconstruction from presentation geometry.'}}};
writeFileSync('proof/audit/IW-FULL-FEATURES/inventory.json',JSON.stringify(audit,null,2)+'\n');d.fullFeatureAudit=audit;d.updatedAt=new Date().toISOString();const v=validate(d);if(!v.ok)throw Error(JSON.stringify(v));writeFileSync('planning/control/ledger.json',JSON.stringify(d,null,2)+'\n');writeFileSync('planning/control/index.html',render(d));writeFileSync('planning/control/dashboard.html',render(d));console.log(JSON.stringify({total:audit.total,baseline:139,subfeatures:extra.length,groups,status:{untested:features.length-2,fail:2},assignmentCounts:{ui:audit.assignment.ui.ids.length,engine:audit.assignment.engine.ids.length}},null,2));
