import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { spawn } from 'node:child_process';
const runId=process.argv[2];
if(!/^[a-f0-9]{12}$/.test(runId??''))throw Error('Verified run ID required');
const base=path.resolve(`proof/growth/2026-09-08-navigation-release/release-${runId}`);
const record=JSON.parse(fs.readFileSync(path.join(base,'native-completion.json'),'utf8').replace(/^\uFEFF/,''));
if(!record.results.some(s=>s.step==='native-build'&&s.exitCode===0))throw Error('Native build did not pass');
const exe=path.join(base,'artifacts/src-tauri/target/release/xray-by-looplet.exe');
const sha256=createHash('sha256').update(fs.readFileSync(exe)).digest('hex');
if(!record.artifacts.some(a=>a.sha256===sha256&&a.path.endsWith('xray-by-looplet.exe')))throw Error('EXE identity mismatch');
const profile=path.resolve('.temp/growth-native-1788787075705');
if(!fs.existsSync(profile))throw Error('Prior isolated QA profile missing; do not substitute working data');
const output=path.join(base,'qa-launch.json');
if(fs.existsSync(output))throw Error('Prior launch evidence exists; preserve it');
const app=spawn(exe,[],{windowsHide:true,detached:true,stdio:'ignore',env:{...process.env,WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS:'--remote-debugging-port=9266',WEBVIEW2_USER_DATA_FOLDER:profile}});
app.unref();
const result={runId,pid:app.pid,exe,profile,sha256,cdpPort:9266,launchedAt:new Date().toISOString(),note:'Retained isolated QA profile; normal installation and user data untouched.'};
fs.writeFileSync(output,JSON.stringify(result,null,2),{flag:'wx'});
console.log(JSON.stringify(result));
