import fs from 'node:fs';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
const base='proof/growth/2026-09-08-production-pencil/2026-09-08-8093-pencil-01';
const parse=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''));
const prepared=parse(base+'/prepared-manifest.json'),inspection=parse(base+'/download-inspection.json');
const source=parse('proof/growth/2026-09-08-assistant-mcp-r2/transfer/source-manifest.json');
for(const local of prepared.source)assert.equal(source.entries.find(e=>e.path===local.file)?.sha256,local.sha256,local.file+' differs from built snapshot');
const shots=[
  {file:inspection.files[0].file,caption:'Actual immediate PNG download: the complete 2,180-part model is visible despite no intervening animation frame.'},
  ...inspection.pdf.pages.map(p=>({file:p.file,caption:`Downloaded PDF page ${p.page}: ${['all 33 supplied levels retained; unsurveyed model coordinates','lowest level actual triangle projection; triangulation retained','upper level actual triangle projection; no invented layout','X/Y elevation projection; explicitly not a section cut','actual completed model snapshot'][p.page-1]}.`})),
  {file:'screenshots/growth/2026-09-08-8093-pencil-01-tablet-landscape-solid-supplement.png',caption:'1024×768: every drafting button/select reached and measured at least 44×44; assistant launcher clear. Open dock covers much of the model view.'},
  {file:'screenshots/growth/2026-09-08-8093-pencil-01-tablet-portrait-solid-supplement.png',caption:'768×1024: completed model and drafting controls; top settings and assistant launcher remain available.'},
  {file:'screenshots/growth/2026-09-08-8093-pencil-01-tablet-portrait-restored.png',caption:'Known failure retained: after closing drafting, the preview still omits the separate bottom model-navigation dock.'},
];
const logs=['2026-09-08T03-39-25-526Z-growth-pencil-production','2026-09-08T03-40-14-660Z-growth-pencil-production','2026-09-08T03-40-47-194Z-growth-pencil-production-tablet','2026-09-08T03-42-38-574Z-growth-pencil-production-tablet'].map(id=>({file:`proof/growth/runner/${id}.log`,...parse(`proof/growth/runner/${id}.json`)}));
const result={status:'exports-pass-drafting-tablet-pass-bottom-navigation-open',date:new Date().toISOString(),artifactId:'4e6d1ebd3a62',sourceArchiveSha256:'4e6d1ebd3a624e21fa84e9fa03b320e822080d800bb8580fa86470953c5446cc',webArchiveSha256:'30528db440bcc5b7814ecc160aee43212f3d28daec4449c8651dba20a7e52878',sourceFilesMatchBuiltManifest:true,
  scope:'Production Windows browser, desktop1440x900 and tablet1024x768/768x1024. Native and other operating systems are not established here.',
  rapid:{beforeFrame:7,afterFrame:7,phase:'complete',visibleMeshes:2180,totalMeshes:2180,actualPngInspected:true,rapidVsSettledMeanAbsoluteChannelDifference:inspection.rapidVsSettledMeanAbsoluteChannelDifference},
  actualFiles:inspection.files,logs,
  visualReview:{reviewedAt:new Date().toISOString(),png:'Both actual1920x1200 PNGs inspected: completed tower and readable notice. Tiny0.000197 mean channel difference; visually same complete model, no material capture mismatch.',pdf:'All5 parsed/rendered pages inspected.33 actual Crown levels; NTS/illustrative/nonconstruction notices readable, unassigned revision, real generation date. Dense triangles/occluded edges remain deliberately disclosed.',tablet:'All shown drafting controls44x44/reachable, launcher unoccluded in both orientations; completed-state supplemental images inspected.'},
  open:['Real preview defect: Model navigation dock absent because ready excludes previewMode; root preparing a separate source/build correction.','Illustrative raster model projections are not clean cut plans, editable CAD, professional approval, or a newly authored52-storey package.','The expanded tablet drafting dock occupies much of the model viewport; closing it restores the visible model.'],
  harnessNotes:['Initialization JSON initially had a UTF8BOM; parser rejected before anybrowser action. Encoding corrected; noappchange.','Browser retained Downloads as actualdestination despite normal-path configuration. Exact3run-specific originals were copied into proof; SHA256 equality checked; originals preserved.','Filename-only anchor wrapper called original click without substituting bytes; restored aftersuccessful batch.','No phone testing, paid provider calls, normal-user-data changes, installation, or application source edits.'],
  images:shots.map(item=>({...item,sha256:createHash('sha256').update(fs.readFileSync(item.file)).digest('hex')}))};
fs.writeFileSync(base+'/acceptance.json',JSON.stringify(result,null,2)+'\n',{flag:'wx'});
const md=`# Production model export acceptance — 4e6d1ebd3a62\n\n**Exports pass; drafting tablet controls pass; bottom model navigation remains OPEN.**\n\nThe build badge was checked in both isolated browser sessions. Six relevant source hashes match the worker snapshot. Source archive: ${result.sourceArchiveSha256}.\n\n- Rapid Solid Finish → Blueprint happened in one synchronous browser turn: frame7→7, complete,2180/2180 meshes. Both actual PNG downloads were inspected and contain the completed tower.\n- The actual544,559-byte PDF was parsed, allfive A4landscape pages rendered and inspected. All33 supplied CrownWharf levels appear; notices identify NTS, illustrative, notforconstruction, and unassigned revision.\n- Desktop29commands/4.180s; tablets30/3.335s pluscompleted-state15/0.757s. Every draftingbutton/select was at least44×44 and reachedby hit testing at1024×768 and768×1024. Runtimeerror lists wereempty.\n- Download originals remain in the browser Downloads directory; exact run-specific copies and SHA256 hashes are in downloads/ and download-inspection.json.\n\n## Open findings\n\nThe separate bottom Model navigation toolbar is absent from Explore &Draw preview (DOM confirmed). Root identified the ready-only rendering condition and is preparing a new build. This candidate is not accepted for the user's bottom-button requirement.\n\nThe PDF intentionally shows actual triangulation and occludededges. It is a raster illustrative model book, not a clean architecturalcut-plan package or an editable52-storey design. The expanded tablet drafting dock covers partof the model; itscontrols and launcher remain reachable.\n\n## Evidence\n\n- [Self-contained illustrated HTML](acceptance.html)\n- [Machine-readable acceptance](acceptance.json)\n- [Actualfile inspection](download-inspection.json)\n- [Rapid PNG](downloads/${prepared.tag}-01.png)\n- [PDF](downloads/${prepared.tag}-03.pdf)\n\n${logs.map(l=>`- ${l.file}: exit${l.exitCode}, ${l.commands}commands, ${l.seconds.toFixed(3)}s`).join('\n')}\n\nHarness-only BOM correction and actual download-path behavior are recorded in acceptance.json. Historical failed/superseded evidence remains intact. No application source edits were made in this QA task.\n`;
fs.writeFileSync(base+'/acceptance.md',md,{flag:'wx'});
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Production model export proof — 4e6d1ebd3a62</title><style>body{margin:0;background:#edf1f3;color:#192d37;font:16px/1.6 'Segoe UI',sans-serif}main{max-width:1180px;margin:auto;padding:36px;background:white}h1{line-height:1.2}h2{font-size:22px}p{max-width:1000px}.status{border-left:6px solid #9b6924;background:#fff6e6;padding:18px}figure{margin:30px 0;border:1px solid #cbd8dd}img{display:block;width:100%;height:auto}figcaption{padding:16px}small,pre{overflow-wrap:anywhere;white-space:pre-wrap;font-size:12px}summary{cursor:pointer}li{margin-bottom:8px}</style><main><p>X-RAY · PRODUCTION PROOF · 8 SEPTEMBER 2026</p><h1>Real model exports, tested immediately after Solid Finish</h1><p class="status"><strong>Build4e6d1ebd3a62: PNG/PDFexportsPASS; tablet draftingcontrolsPASS. BottommodelnavigationOPEN.</strong><br>The missing preview navigation dock is retained as a release finding; a new build is required for that correction.</p><p>The rapid PNG was requested in the same browser turn as Solid Finish: frame7→7, all2180parts present. Actual downloadedbytes, both PNGs and allfive PDFpages were inspected. The PDF retains33supplied CrownWharf levels.</p><p>Both tablet orientations1024×768 and768×1024 passed44×44 draftingcontrol targets, scrolling and hit tests. These are Windowsbrowser checks; no nativeorotherOS acceptance is implied.</p><h2>Limits and open work</h2><ul>${result.open.map(t=>`<li>${esc(t)}</li>`).join('')}</ul>${shots.map(s=>`<figure><img src="data:image/png;base64,${fs.readFileSync(s.file).toString('base64')}" alt="${esc(s.caption)}"><figcaption>${esc(s.caption)}<br><small>${esc(s.file)}</small></figcaption></figure>`).join('')}<h2>Executed evidence and identity</h2><pre>${esc(JSON.stringify({...result,images:result.images},null,2))}</pre></main></html>`;
fs.writeFileSync(base+'/acceptance.html',html,{flag:'wx'});
fs.writeFileSync(base+'/report-qa.json',JSON.stringify([['open','file:///C:/Users/danie/repo/xray-by-looplet/'+base+'/acceptance.html'],['set','viewport','1440','1000'],['wait','--fn',"Array.from(document.images).every(i=>i.complete&&i.naturalWidth>0)"],['eval',"(()=>{if(document.images.length!==9)throw Error('Missing embedded proof');return {title:document.title,images:document.images.length,openFinding:document.body.textContent.includes('BottommodelnavigationOPEN')};})()"],['screenshot','screenshots/growth/2026-09-08-8093-pencil-01-report-summary.png'],['errors']],null,2),{flag:'wx'});
console.log(JSON.stringify({report:base+'/acceptance.html',images:shots.length,sourceFilesMatch:true}));
