import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {spawn} from 'node:child_process';
const arg=process.argv[2]||'http://127.0.0.1:8080',native=arg.endsWith('.exe'),mode=native?(arg.includes('AppData')?'installed':'native'):(arg.includes('8081')?'built':'dev'),dir=path.resolve('screenshots/rail-recovery',mode);fs.mkdirSync(dir,{recursive:true});let app,browser;
if(native){app=spawn(path.resolve(arg),[],{windowsHide:true,stdio:'ignore',env:{...process.env,WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS:'--remote-debugging-port=9238',WEBVIEW2_USER_DATA_FOLDER:path.resolve('proof/audit/IW-RAIL-RECOVERY/profile-'+Date.now())}});for(let i=0;i<90;i++){try{browser=await chromium.connectOverCDP('http://127.0.0.1:9238');break;}catch{await new Promise(r=>setTimeout(r,500));}}}else browser=await chromium.launch({headless:true,channel:'msedge'});
const page=native?browser.contexts()[0].pages()[0]:await browser.newPage({viewport:{width:1600,height:1100},acceptDownloads:true,...(mode==='built'?{recordVideo:{dir:path.join(dir,'video'),size:{width:1600,height:1100}}}:{})});page.setDefaultTimeout(30000);const report={ok:false,checks:[],errors:[],...(native?{sha256:crypto.createHash('sha256').update(fs.readFileSync(arg)).digest('hex')}: {})};page.on('pageerror',e=>report.errors.push(String(e)));page.on('console',e=>{if(e.type()==='error')report.errors.push(e.text())});const b=n=>page.getByRole('button',{name:n,exact:true}),check=async(n,f)=>{await f();report.checks.push(n);console.log('PASS '+n);},shot=n=>page.screenshot({path:path.join(dir,n+'.png')});
async function drag(side,delta){const handle=b('Expand '+side+' menu');await handle.click({trial:true});const r=await handle.boundingBox();await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await page.mouse.move(r.x+r.width/2+delta,r.y+r.height/2,{steps:12});await page.mouse.up();await b('Collapse '+side+' menu').waitFor();}
try{
if(!native)await page.goto(arg);await page.locator('[data-hydration-status=ready]').waitFor();
await check('Existing Collapse button retains a visible middle-right recovery pill',async()=>{await b('Collapse').click();await b('Expand right menu').waitFor();assert.equal(await page.locator('.studio-right-rail').isVisible(),false);await b('Expand right menu').click({trial:true});const r=await b('Expand right menu').boundingBox();assert.ok(r.x+r.width<=await page.evaluate(()=>innerWidth));await shot('01-collapsed-right');await b('Expand right menu').click();await page.locator('.studio-right-rail').waitFor();});
await check('Both menus collapse together, click reopen and preserve their widths',async()=>{const left=await page.locator('.studio-left-rail').boundingBox(),right=await page.locator('.studio-right-rail').boundingBox();await b('Collapse left menu').click();await b('Collapse right menu').click();await b('Expand left menu').waitFor();await b('Expand right menu').waitFor();assert.equal(await page.locator('.studio-left-rail').isVisible(),false);await b('Expand right menu').click({trial:true});await shot('02-both-collapsed');await b('Expand left menu').click();await b('Expand right menu').click();assert.equal(Math.round((await page.locator('.studio-left-rail').boundingBox()).width),Math.round(left.width));assert.equal(Math.round((await page.locator('.studio-right-rail').boundingBox()).width),Math.round(right.width));});
await check('Drag out both collapsed handles without immediately recollapsing on pointer release',async()=>{await b('Collapse left menu').click();await drag('left',290);await b('Collapse right menu').click();await drag('right',-380);assert.ok((await page.locator('.studio-left-rail').boundingBox()).width>=280);assert.ok((await page.locator('.studio-right-rail').boundingBox()).width>=370);await b('Collapse right menu').focus();await page.keyboard.press('Enter');await b('Expand right menu').focus();await page.keyboard.press('Space');await page.locator('.studio-right-rail').waitFor();});
await page.getByRole('separator',{name:'Resize left menu',exact:true}).press('Home');await page.getByRole('separator',{name:'Resize right menu',exact:true}).press('Home');
await b('Model').click();await b('Open Crown Wharf A4 tower plan in 3D').click();await page.getByRole('img',{name:'Interactive source building model',exact:true}).waitFor();
await check('Model handles recover both menus and the canvas fills reclaimed space',async()=>{const before=await page.locator('.building-stage').boundingBox();await b('Collapse right menu').click();await b('Collapse left menu').click();const after=await page.locator('.building-stage').boundingBox();assert.ok(after.width>before.width+500);await shot('03-model-collapsed');await drag('left',260);await drag('right',-400);await page.locator('.building-inspector').waitFor();});
await check('PNG is inside Visual settings and alternate model controls use neutral grey',async()=>{assert.equal(await b('Download model PNG').count(),0);const wire=await b('Wireframe').evaluate(e=>getComputedStyle(e).backgroundColor),fit=await b('Fit').evaluate(e=>getComputedStyle(e).backgroundColor);assert.notEqual(wire,fit);await b('Visual settings').click();await b('Download model PNG').waitFor();assert.equal(await page.locator('.building-toolbar').getByRole('button',{name:'Download model PNG'}).count(),0);if(!native){const download=page.waitForEvent('download');await b('Download model PNG').click();const d=await download;const target=path.join(dir,'model.png');await d.saveAs(target);assert.equal(fs.readFileSync(target).subarray(0,8).toString('hex'),'89504e470d0a1a0a');}await b('Download model PNG').scrollIntoViewIfNeeded();await shot('04-visual-export');await b('Close visual settings').click();await shot('05-model-handles');});

await check('CRM-style inspection pans smoothly with steady heading, no resize jump and no nearby forward movement',async()=>{
const c=page.getByRole('img',{name:'Interactive source building model',exact:true}),data=()=>c.evaluate(e=>({...e.dataset})),state=(k,v)=>page.waitForFunction(({k,v})=>document.querySelector('[aria-label="Interactive source building model"]')?.dataset[k]===v,{k,v});
await page.getByLabel('Building floor',{exact:true}).selectOption('L18');await b('Fit').click();await page.getByLabel('Building part',{exact:true}).selectOption('L18-column-0');await state('inspectionTransition','moving');await page.waitForFunction(()=>{const d=document.querySelector('[aria-label="Interactive source building model"]')?.dataset;return d?.inspectionTransition==='moving'&&Number(d.inspectionProgress)>.2});const mid=await data();assert.equal(mid.inspectionTransition,'moving');assert.ok(Number(mid.inspectionProgress)>.15&&Number(mid.inspectionProgress)<1);const v=(d,k)=>d[k].split(',').map(Number),f=v(mid,'inspectionFrom'),t=v(mid,'inspectionTo'),pos=v(mid,'cameraPosition'),pr=Number(mid.inspectionProgress),ease=pr<.5?4*pr*pr*pr:1-Math.pow(-2*pr+2,3)/2;assert.ok(Math.hypot(...pos.map((x,i)=>x-(f[i]+(t[i]-f[i])*ease)))>.01);await state('inspectionTransition','idle');report.approachSample=mid;
await b('Walk / cinematic').click();await b('Choose walking start on floor plan').click({position:{x:210,y:130}});await b('Start walking here').click();await state('navigationTransition','idle');await page.keyboard.press('Escape');await state('navigation','orbit');
const d=await data(),camera=v(d,'cameraPosition'),model=JSON.parse(fs.readFileSync('public/models/crown-wharf/source-building.json'));const columns=model.objects.filter(p=>p.storey==='L18'&&p.category==='column').map(p=>{const a=p.positions,centre=[0,1,2].map(j=>a.filter((_,i)=>i%3===j).reduce((x,y)=>x+y,0)/(a.length/3));return {id:p.id,d:Math.hypot(...centre.map((x,i)=>x-camera[i]))}}).sort((a,b)=>a.d-b.d);
await page.getByLabel('Building part',{exact:true}).selectOption('');await page.getByLabel('Building part',{exact:true}).selectOption(columns[0].id);await state('inspectionTransition','moving');const samples=[];for(let i=0;i<3;i++){await page.waitForTimeout(150);const s=await data();assert.equal(s.inspectionMode,'lateral');assert.ok(Number(s.inspectionDistance)<=20);const from=v(s,'inspectionFrom'),position=v(s,'cameraPosition'),forward=v(s,'inspectionForward');assert.ok(Math.abs(position.reduce((sum,x,j)=>sum+(x-from[j])*forward[j],0))<.0001);samples.push(s);}await state('inspectionTransition','idle');const settled=await data();await page.waitForTimeout(450);const afterSettle=await data();for(const key of ['cameraPosition','cameraQuaternion']){const a=v(settled,key),z=v(afterSettle,key);assert.ok(Math.hypot(...a.map((x,i)=>x-z[i]))<.0001,'No snap after inspection: '+key);}const qa=v(samples[0],'cameraQuaternion');for(const row of samples)assert.ok(Math.hypot(...v(row,'cameraQuaternion').map((x,i)=>x-qa[i]))<.0001,'Steady view angle during pan');await b('Collapse right menu').click();await b('Expand right menu').click({trial:true});const resized=await data();assert.ok(Math.hypot(...v(resized,'cameraPosition').map((x,i)=>x-v(afterSettle,'cameraPosition')[i]))<.0001,'Resize must not refit camera');await b('Expand right menu').click();await page.waitForTimeout(100);report.nearbySamples=samples;report.settleStable=true;report.resizePreservesCamera=true;await shot('07-nearby-inspection');
await page.getByLabel('Building part',{exact:true}).selectOption(columns[1].id);await state('inspectionTransition','moving');const box=await c.boundingBox();await page.mouse.move(box.x+box.width*.5,box.y+box.height*.4);await page.mouse.down();await state('inspectionTransition','idle');await page.mouse.up();await page.emulateMedia({reducedMotion:'reduce'});await page.getByLabel('Building part',{exact:true}).selectOption(columns[2].id);await state('selectedPart',columns[2].id);await state('inspectionTransition','idle');await page.emulateMedia({reducedMotion:'no-preference'});
await b('Show Floor in building').click();const style=await page.locator('.location-thumbnail[aria-pressed=true]').evaluate(e=>{const s=getComputedStyle(e);return {border:s.borderWidth,colour:s.borderColor,shadow:s.boxShadow}});assert.ok(parseFloat(style.border)>0&&parseFloat(style.border)<=1);report.thumbnailBorder=style;assert.equal(style.colour,'rgb(69, 72, 76)');assert.equal(style.shadow,'none');await b('Fit').click();await shot('08-thin-thumbnail-edges');
});
await check('Measure inspector and tab switching retain recovery access',async()=>{await b('Measure').click();await b('Collapse right menu').click();assert.equal(await page.locator('.measure-inspector-boundary').isVisible(),false);await b('Expand right menu').click();await page.locator('.measure-inspector-boundary').waitFor();await b('Components').click();await b('Collapse right menu').click();await b('Sheets').click();await b('Expand right menu').click();await page.locator('.studio-right-rail').waitFor();});
await check('Mobile stays usable with no page overflow',async()=>{await page.setViewportSize({width:390,height:844});await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await shot('06-mobile');});
assert.deepEqual(report.errors,[]);report.ok=true;
}catch(e){report.failure=String(e.stack);process.exitCode=1;await shot('failure');}finally{fs.writeFileSync(path.join(dir,'report.json'),JSON.stringify(report,null,2));if(native)fs.writeFileSync('proof/audit/IW-RAIL-RECOVERY/'+mode+'-qa.json',JSON.stringify(report,null,2));if(!native&&page.video()){const video=page.video();await page.context().close();await video.saveAs(path.join(dir,'interaction-proof.webm'));}await browser?.close();app?.kill();console.log(JSON.stringify(report));}
