import {build} from 'rolldown';
import {chromium} from 'playwright';
import {createServer} from 'node:http';
import {once} from 'node:events';
import {mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const stamp=new Date().toISOString().replaceAll(':','-').replaceAll('.','-'),out=`proof/audit/IW022/run-${stamp}`,shots=`screenshots/industry-runtime/${stamp}`;
mkdirSync(out,{recursive:true});mkdirSync(shots,{recursive:true});
const inputs=['src/studio/construction/runtime/index.ts','src/studio/construction/runtime/repository.ts','src/studio/construction/contract.ts','src/studio/construction/lifecycle.ts','package-lock.json'];
const hashes=()=>Object.fromEntries(inputs.map(p=>[p,createHash('sha256').update(readFileSync(p)).digest('hex')]));const sourceBefore=hashes();
await build({input:'src/studio/construction/runtime/index.ts',platform:'browser',output:{format:'es',file:`${out}/runtime.js`},logLevel:'silent'});
const results=[],errors=[];let report='<h1>Construction runtime execution</h1><p>Actual IndexedDB checks starting. No completion claim.</p>';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const html=()=>`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Construction runtime execution evidence</title><style>body{margin:0;padding:32px;background:#eee7d9;color:#211d18;font:16px/1.55 system-ui}main{max-width:1100px;margin:auto}h1{font-size:30px;line-height:1.2}li{padding:12px 0;border-bottom:1px solid #cbbda6}code{overflow-wrap:anywhere;font-size:12px}.notice{padding:16px;background:#f8f4eb;border-left:4px solid #3464a1}@media(max-width:600px){body{padding:20px}h1{font-size:25px}}</style><main>${report}</main></html>`;
const server=createServer((req,res)=>{if(req.url==='/runtime.js'){res.writeHead(200,{'Content-Type':'text/javascript'});res.end(readFileSync(`${out}/runtime.js`));}else if(req.url==='/'){res.writeHead(200,{'Content-Type':'text/html'});res.end(html());}else{res.writeHead(req.url==='/favicon.ico'?204:404);res.end();}});server.listen(0,'127.0.0.1');await once(server,'listening');const url=`http://127.0.0.1:${server.address().port}/`;
const browser=await chromium.launch({headless:true,channel:'msedge'}),context=await browser.newContext({viewport:{width:1280,height:900}}),page=await context.newPage();
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
let failure;
async function check(name,fn){const startedAt=new Date().toISOString();try{const detail=await fn();results.push({name,passed:true,startedAt,completedAt:new Date().toISOString(),detail});}catch(error){results.push({name,passed:false,startedAt,completedAt:new Date().toISOString(),error:String(error)});throw error;}}
try{
 await page.goto(url);await page.screenshot({path:`${shots}/desktop-report-before.png`,fullPage:true});
 await page.evaluate(async dbName=>{
  const m=await import('/runtime.js');window.m=m;window.dbName=dbName;window.repo=new m.ConstructionRepository({databaseName:dbName});window.time='2026-09-05T06:00:00.000Z';
  window.must=(value,message)=>{if(!value)throw Error(message)};
  window.sha=async bytes=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(n=>n.toString(16).padStart(2,'0')).join('');
  window.attr=id=>({commandId:id,actor:'local-estimator',occurredAt:window.time});
  window.fixture=async(id,content='<svg>drawing</svg>')=>{const bytes=new TextEncoder().encode(content).buffer,sha256=await window.sha(bytes);return {job:{schema:'xray.construction-job/v1',id,revision:1,name:`Project ${id}`,createdAt:window.time,updatedAt:window.time,workPackages:[],sources:[{id:'source-1',documentId:'doc-1',revision:1,sha256,name:'source.svg',kind:'svg',importedAt:window.time,assetId:'original-1',pageCount:1}],evidence:[],calibrations:[],measurements:[],extensions:{}},assets:[{assetId:'original-1',bytes}]};};
  window.inspect=async()=>{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open(window.dbName);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});try{const tx=db.transaction(['heads','snapshots','assets','commands'],'readonly');return await Promise.all(['heads','snapshots','assets','commands'].map(name=>new Promise((resolve,reject)=>{const r=tx.objectStore(name).getAll();r.onsuccess=()=>resolve([name,r.result]);r.onerror=()=>reject(r.error)}))).then(Object.fromEntries);}finally{db.close();}};
  window.mutate=async(store,key,fn)=>{const db=await new Promise(resolve=>{const r=indexedDB.open(window.dbName);r.onsuccess=()=>resolve(r.result)});try{await new Promise((resolve,reject)=>{const tx=db.transaction(store,'readwrite'),s=tx.objectStore(store),r=s.get(key);r.onsuccess=()=>s.put(fn(r.result));tx.oncomplete=()=>resolve();tx.onabort=()=>reject(tx.error)});}finally{db.close();}};
 },`IW022-proof-${stamp}`);
 await check('Create/open hashes real original bytes and restores after repository reconnect',()=>page.evaluate(async()=>{window.original=await fixture('alpha');const created=await repo.create(original.job,original.assets,attr('create-alpha'));must(created.ok,'create failed '+JSON.stringify(created));await repo.close();window.repo=new m.ConstructionRepository({databaseName:dbName});const opened=await repo.open('alpha');must(opened.ok&&JSON.stringify(opened.value)===JSON.stringify(created.value),'restore mismatch');const state=await inspect();must(state.snapshots.length===1&&state.assets.length===1&&state.commands[0].actor==='local-estimator','atomic stores missing');return {revision:opened.value.revision,sourceSha256:opened.value.sources[0].sha256,snapshotCount:state.snapshots.length};}));
 await check('Multiple jobs isolate identical asset IDs and list deterministic summaries',()=>page.evaluate(async()=>{const f=await fixture('beta','<svg>other project</svg>');const created=await repo.create(f.job,f.assets,attr('create-beta'));must(created.ok,'beta create');const listed=await repo.list();must(listed.ok&&listed.value.map(j=>j.id).join(',')==='alpha,beta','multi job list');const a=await repo.open('alpha'),b=await repo.open('beta');must(a.ok&&b.ok&&a.value.sources[0].sha256!==b.value.sources[0].sha256,'cross job asset leaked');return {jobs:listed.value.map(j=>j.id)};}));
 await check('All six command kinds execute with local attribution and immutable snapshots',()=>page.evaluate(async()=>{const source=original.job.sources[0],locator={kind:'page',sourceRevisionId:source.id,sha256:source.sha256,pageIndex:0};let revision=1;const run=async command=>{const r=await repo.execute({...attr('command-'+revision),jobId:'alpha',expectedJobRevision:revision,...command},command.assets??[]);must(r.ok,'command failed '+JSON.stringify(r));revision=r.job.revision;return r.job;};
 await run({kind:'put-work-package',workPackage:{id:'electrical',revision:1,trade:'electrical',name:'Outlets',pack:null}});
 await run({kind:'append-evidence',evidence:{id:'drawing-evidence',locator,note:'Original drawing checked'}});
 await run({kind:'append-calibration',calibration:{id:'scale-1',revision:1,locator,metresPerCoordinateUnit:1,method:'declared-unit',inputDistance:{value:1,unit:'m'},coordinateDistance:1,referencePoints:null,evidenceIds:['drawing-evidence'],verifiedBy:'local-estimator',verifiedAt:time}});
 await run({kind:'put-measurement',measurement:{id:'outlets',revision:1,workPackageId:'electrical',label:'Socket outlets',locator,evidenceIds:['drawing-evidence'],review:{status:'draft'},kind:'count',items:[{id:'outlet-a',evidenceIds:['drawing-evidence']}],deductions:[]}});
 const reviewed=await run({kind:'review-measurement',measurementId:'outlets',expectedMeasurementRevision:1,decision:'approved',note:'Actual source reviewed'});must(reviewed.measurements[0].review.decidedBy==='local-estimator','review actor mismatch');
 const bytes=new TextEncoder().encode('Specification original').buffer,sha256=await sha(bytes),command={...attr('append-spec'),jobId:'alpha',expectedJobRevision:revision,kind:'append-source',source:{id:'source-2',documentId:'doc-2',revision:1,sha256,name:'spec.txt',kind:'specification',importedAt:time,assetId:'original-2',pageCount:null}};const appended=await repo.execute(command,[{assetId:'original-2',bytes}]);must(appended.ok,'append source '+JSON.stringify(appended));window.currentRevision=appended.job.revision;const snapshot=await repo.snapshot('alpha',1);must(snapshot.ok&&snapshot.value.measurements.length===0&&snapshot.value.sources.length===1,'snapshot changed');return {revision:currentRevision,reviewActor:reviewed.measurements[0].review.decidedBy,allCommandKinds:6};}));
 await check('Two actual tabs race one expected revision; exactly one commit succeeds',async()=>{const tab=await context.newPage();await tab.goto(url);await tab.evaluate(async db=>{window.m=await import('/runtime.js');window.repo=new m.ConstructionRepository({databaseName:db});},`IW022-proof-${stamp}`);const revision=await page.evaluate(()=>currentRevision);const command=id=>({commandId:`race-${id}`,actor:'second-tab-estimator',occurredAt:'2026-09-05T06:00:00.000Z',jobId:'alpha',expectedJobRevision:revision,kind:'put-work-package',workPackage:{id,revision:1,trade:'plumbing',name:id,pack:null}});const race=await Promise.all([page.evaluate(c=>repo.execute(c),command('race-a')),tab.evaluate(c=>repo.execute(c),command('race-b'))]);assert.equal(race.filter(r=>r.ok).length,1);assert.equal(race.filter(r=>!r.ok&&r.code==='conflict').length,1);await tab.close();return {outcomes:race.map(r=>r.ok?'committed':r.code)};});
 await check('Invalid hash, missing originals, future schema and forged review cannot write',()=>page.evaluate(async()=>{const before=await inspect(),current=await repo.open('alpha');must(current.ok,'open');const revision=current.value.revision;const badSource={...original.job.sources[0],id:'bad-source',assetId:'bad-asset',documentId:'bad-doc'};const mismatch=await repo.execute({...attr('bad-hash'),jobId:'alpha',expectedJobRevision:revision,kind:'append-source',source:badSource},[{assetId:'bad-asset',bytes:new TextEncoder().encode('wrong').buffer}]);must(!mismatch.ok,'hash accepted');const missing=await fixture('missing');must(!(await repo.create(missing.job,[],attr('missing-create'))).ok,'missing bytes accepted');must(!(await repo.create({...missing.job,schema:'xray.construction-job/v999'},missing.assets,attr('future-create'))).ok,'future schema accepted');const forged=await repo.execute({...attr('forged-review'),jobId:'alpha',expectedJobRevision:revision,kind:'put-measurement',measurement:{...current.value.measurements[0],review:{status:'approved',measurementRevision:1,decidedBy:'someone-else',decidedAt:time,note:'forged'}}});must(!forged.ok,'forged actor accepted');const after=await inspect();must(JSON.stringify(before.heads)===JSON.stringify(after.heads)&&before.snapshots.length===after.snapshots.length&&before.commands.length===after.commands.length,'failed operations wrote state');return {rejected:4,preservedRevision:revision};}));
 await check('Real transaction abort rolls back staged head/snapshot/assets/audit atomically',()=>page.evaluate(async()=>{const before=await inspect(),current=await repo.open('alpha'),failing=new m.ConstructionRepository({databaseName:dbName,onWritesStaged:()=> 'abort'});const bytes=new TextEncoder().encode('will rollback').buffer,sha256=await sha(bytes);const r=await failing.execute({...attr('abort-test'),jobId:'alpha',expectedJobRevision:current.value.revision,kind:'append-source',source:{id:'aborted-source',documentId:'aborted-doc',revision:1,sha256,name:'aborted.txt',kind:'specification',importedAt:time,assetId:'aborted-asset',pageCount:null}},[{assetId:'aborted-asset',bytes}]);must(!r.ok&&r.code==='storage','abort not surfaced');const after=await inspect();for(const store of ['heads','snapshots','commands'])must(JSON.stringify(before[store])===JSON.stringify(after[store]),store+' changed after abort');must(before.assets.length===after.assets.length,'aborted asset persisted');await failing.close();return {result:r.code,preservedStores:4};}));
 await check('Corrupt stored bytes reject open/commands while prior snapshot remains immutable',()=>page.evaluate(async()=>{const before=await inspect(),saved=before.assets.find(a=>a.jobId==='alpha'&&a.assetId==='original-1');await mutate('assets',['alpha','original-1'],a=>({...a,bytes:new TextEncoder().encode('corrupted').buffer}));const opened=await repo.open('alpha');must(!opened.ok&&opened.code==='corrupt','corrupt bytes accepted');const r=await repo.execute({...attr('corrupt-command'),jobId:'alpha',expectedJobRevision:before.heads.find(h=>h.job.id==='alpha').job.revision,kind:'put-work-package',workPackage:{id:'bad',revision:1,trade:'other',name:'bad',pack:null}});must(!r.ok,'command accepted corrupt asset');const after=await inspect();must(JSON.stringify(before.snapshots)===JSON.stringify(after.snapshots),'snapshot modified');await mutate('assets',['alpha','original-1'],()=>saved);return {openCode:opened.code,commandCode:r.code,snapshotsPreserved:before.snapshots.length};}));
 await check('Corrupt/future stored head is preserved; explicit earlier snapshot remains readable',()=>page.evaluate(async()=>{const before=await inspect(),saved=before.heads.find(h=>h.job.id==='alpha');await mutate('heads','alpha',h=>({...h,job:{...h.job,schema:'future/v999'}}));const opened=await repo.open('alpha'),snapshot=await repo.snapshot('alpha',1);must(!opened.ok&&opened.code==='corrupt','future head accepted');must(snapshot.ok&&snapshot.value.revision===1,'recovery snapshot unavailable');const after=await inspect();must(after.heads.find(h=>h.job.id==='alpha').job.schema==='future/v999','future head overwritten');await mutate('heads','alpha',()=>saved);return {headCode:opened.code,recoverableSnapshotRevision:snapshot.value.revision};}));
 await check('Archive retains originals/history, hides default list, prevents later commands',()=>page.evaluate(async()=>{const opened=await repo.open('beta');const r=await repo.archive('beta',opened.value.revision,attr('archive-beta'));must(r.ok&&r.value.revision===2,'archive failed');const active=await repo.list(),all=await repo.list(true),snapshot=await repo.snapshot('beta',1);must(active.ok&&active.value.length===1&&all.ok&&all.value.length===2&&all.value.find(j=>j.id==='beta').archived,'archive listing');must(snapshot.ok,'archive deleted history');const blocked=await repo.execute({...attr('after-archive'),jobId:'beta',expectedJobRevision:2,kind:'put-work-package',workPackage:{id:'blocked',revision:1,trade:'other',name:'blocked',pack:null}});must(!blocked.ok,'archived write accepted');return {activeJobs:active.value.length,totalJobs:all.value.length,archiveRevision:r.value.revision};}));
 await check('Revision/actor boundaries, package review invalidation and command identity replay reject safely',()=>page.evaluate(async()=>{let opened=await repo.open('alpha');const initial=opened.value,revision=initial.revision;const stale=await repo.execute({...attr('stale-review'),jobId:'alpha',expectedJobRevision:revision,kind:'review-measurement',measurementId:'outlets',expectedMeasurementRevision:999,decision:'approved',note:'stale'});must(!stale.ok&&stale.code==='conflict','stale measurement approved');const unknown=await repo.execute({...attr('unknown-fields'),jobId:'alpha',expectedJobRevision:revision,kind:'put-work-package',surprise:true,workPackage:{id:'unexpected',revision:1,trade:'other',name:'unexpected',pack:null}});must(!unknown.ok&&unknown.code==='invalid','unknown command fields accepted');const workPackage={...initial.workPackages.find(p=>p.id==='electrical'),revision:2,name:'Changed specification'};const updated=await repo.execute({...attr('package-change'),jobId:'alpha',expectedJobRevision:revision,kind:'put-work-package',workPackage});must(updated.ok&&updated.job.measurements[0].review.status==='draft','package change retained approval');const replay=await repo.execute({...attr('package-change'),jobId:'alpha',expectedJobRevision:updated.job.revision,kind:'put-work-package',workPackage:{id:'replay',revision:1,trade:'other',name:'replay',pack:null}});must(!replay.ok&&replay.code==='conflict','command identity replay accepted');return {staleRevision:stale.code,unknownFields:unknown.code,reviewAfterPackageChange:'draft',replay:replay.code};}));
 await check('Original retrieval returns byte-faithful copies and 100 MiB cap rejects oversized input',()=>page.evaluate(async()=>{const loaded=await repo.original('alpha','original-1');must(loaded.ok&&await sha(loaded.value)===original.job.sources[0].sha256,'original retrieval mismatch');new Uint8Array(loaded.value)[0]^=255;const again=await repo.original('alpha','original-1');must(again.ok&&await sha(again.value)===original.job.sources[0].sha256,'caller mutated stored original');const fixtureJob=await fixture('oversized');const result=await repo.create(fixtureJob.job,[{assetId:'original-1',bytes:new ArrayBuffer(m.MAX_ORIGINAL_BYTES+1)}],attr('oversized-create'));must(!result.ok&&result.code==='invalid','oversized original accepted');return {faithfulOriginal:true,defensiveCopy:true,oversizeCode:result.code,maxOriginalBytes:m.MAX_ORIGINAL_BYTES};}));
 await check('Corrupt previous snapshot fails closed without manufacturing recovery history',()=>page.evaluate(async()=>{const before=await inspect(),current=before.heads.find(h=>h.job.id==='alpha'),saved=before.snapshots.find(s=>s.job.id==='alpha'&&s.job.revision===current.job.revision);await mutate('snapshots',['alpha',current.job.revision],s=>({...s,attribution:{...s.attribution,actor:'tampered'}}));const result=await repo.execute({...attr('snapshot-corrupt'),jobId:'alpha',expectedJobRevision:current.job.revision,kind:'put-work-package',workPackage:{id:'blocked-snapshot',revision:1,trade:'other',name:'blocked',pack:null}});must(!result.ok,'corrupt previous snapshot accepted');const after=await inspect();must(JSON.stringify(before.heads)===JSON.stringify(after.heads)&&before.commands.length===after.commands.length,'corrupt snapshot operation wrote head/audit');await mutate('snapshots',['alpha',current.job.revision],()=>saved);return {rejected:true,preservedRevision:current.job.revision};}));
 assert.deepEqual(errors,[]);
}catch(error){failure=String(error);}finally{
 const sourceAfter=hashes(),sourceUnchanged=JSON.stringify(sourceBefore)===JSON.stringify(sourceAfter);if(!sourceUnchanged)failure=(failure??'')+' Source changed during execution.';
 const evidence={at:new Date().toISOString(),url,databaseName:`IW022-proof-${stamp}`,method:'Actual browser IndexedDB through installed Edge/Playwright fallback; no fake database or application store injection',sourceBefore,sourceAfter,sourceUnchanged,results,errors,failure};
 writeFileSync(`${out}/results.json`,JSON.stringify(evidence,null,2));writeFileSync(`${out}/execution.log`,results.map(r=>`${r.passed?'PASS':'FAIL'} ${r.name}\n${JSON.stringify(r.detail??r.error)}\n`).join('\n')+(failure?`\nFAILURE ${failure}\n`:''));
 report=`<p>IW022 / ACTUAL LOCAL INDEXEDDB EXECUTION</p><h1>${failure?'Checks found an error':'Construction runtime checks passed'}</h1><p class="notice">This is a captured execution report of real browser storage and command tests. It is not the product interface or proof that end-to-end estimating is complete.</p><p>${results.filter(r=>r.passed).length}/${results.length} passed · ${esc(url)}<br>${esc(evidence.at)}<br>Source hashes unchanged: ${sourceUnchanged}</p><ol>${results.map(r=>`<li><strong>${r.passed?'PASS':'FAIL'} · ${esc(r.name)}</strong><br><code>${esc(JSON.stringify(r.detail??r.error))}</code></li>`).join('')}</ol><p>Auth off; local actor attribution. Original source bytes rehashed. Isolated proof database only. No app integration, legacy storage deletion or external service.</p><p><code>Exact source hashes / raw results: ${esc(out)}/results.json</code></p>`;
 writeFileSync(`${out}/execution-report.html`,html());const captures=[];
 for(const viewport of [{name:'desktop',width:1280,height:900}]){await page.setViewportSize(viewport);await page.goto(url,{waitUntil:'networkidle'});const path=`${shots}/${viewport.name}-execution-after.png`;await page.screenshot({path,fullPage:true});captures.push({path,url,capturedAt:new Date().toISOString(),viewport});}
 writeFileSync(`${out}/captures.json`,JSON.stringify(captures,null,2));writeFileSync('proof/audit/IW022/latest-run.txt',out);await browser.close();await new Promise(r=>server.close(r));console.log(JSON.stringify({out,passed:results.filter(r=>r.passed).length,total:results.length,failure},null,2));
}
process.exitCode=failure?1:0;
