import test from "node:test";
import assert from "node:assert/strict";
import { PDFDocument } from "pdf-lib";
import { calculateHvacSchedules, createHvacPackage, hvacPackageCsv, hvacPackagePdf, verifyHvacPackage } from "./hvacSchedules.ts";
const input = () => ({ reference: "M-102", evidence: "declared", occupancy: "residential", nodes: [
  { id: "AHU", zone: "West", kind: "equipment", x: 0, y: 3, z: 0, designAirflowLs: 100, equipmentTag: "=UNSAFE()" },
  { id: "D1", zone: "East", kind: "diffuser", x: 5, y: 3, z: 0, designAirflowLs: null, equipmentTag: "" }],
  edges: [{ id: "S1", from: "AHU", to: "D1", shape: "rectangular", widthM: .2, heightM: .1, insulationM: 0, availablePlenumM: null, airflowLs: 140, pressureAllowancePaPerM: 1.5 }], beams: [] });
test("airflow conversion and occupancy-specific project thresholds", () => { const n = input(); assert.ok(Math.abs(calculateHvacSchedules(n).airflow[0].velocityMs! - 7) < 1e-12); assert.equal(calculateHvacSchedules(n).airflow[0].velocityStatus, "review-noise"); n.occupancy = "commercial"; assert.equal(calculateHvacSchedules(n).airflow[0].velocityStatus, "within-project-threshold"); });
test("commissioning tolerance and unknowns never fabricate measured results", () => { const s = calculateHvacSchedules(input()); assert.equal(s.commissioning[0].minimumLs, 90); assert.ok(Math.abs(s.commissioning[0].maximumLs! - 110) < 1e-10); assert.equal(s.commissioning[1].minimumLs, null); assert.equal(s.commissioning[0].measuredLs, null); assert.equal(s.airflow[0].pressureAllowancePa, 7.5); });
test("missing airflow and pressure operands remain unknown", () => { const n = input(); const s = calculateHvacSchedules({ ...n, edges: [{ ...n.edges[0], airflowLs: null, pressureAllowancePaPerM: null }] }); assert.equal(s.airflow[0].velocityMs, null); assert.equal(s.airflow[0].pressureAllowancePa, null); });
test("sealed draft rejects tampered network, computed schedule and delivery identity", async () => { const p = await createHvacPackage(input(), "project-test", null); await verifyHvacPackage(p); assert.match(p.delivery.contentSha256, /^[a-f0-9]{64}$/); for (const mutate of [(x: typeof p) => { x.content.network.reference = "other"; }, (x: typeof p) => { x.content.schedules.commissioning[0].designLs = 1; }, (x: typeof p) => { x.delivery.projectId = "other"; }]) { const copy = structuredClone(p); mutate(copy); await assert.rejects(verifyHvacPackage(copy)); } });
test("CSV escapes formula prefixes, retains unknown and seal; PDF is readable", async () => { const p = await createHvacPackage(input(), "project-test", null); const csv = await hvacPackageCsv(p); assert.ok(csv.includes("'=UNSAFE()")); assert.ok(csv.includes('"unknown"')); assert.ok(csv.includes(p.delivery.contentSha256)); const pdf = await PDFDocument.load(await hvacPackagePdf(p)); assert.ok(pdf.getPageCount() > 0); });
