import{readFileSync,writeFileSync,mkdirSync}from'node:fs';import{createHash}from'node:crypto';import{validate,readLedger,inputDigest}from'../../../scripts/industry-ledger.mjs';
const dir='proof/audit/IW-FULL-FEATURES-FINAL-REVIEW';mkdirSync(dir,{recursive:true});const run=process.argv[2]||new Date().toISOString().replaceAll(':','-'),hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex');const data=readLedger(),audit=data.fullFeatureAudit,inventory=JSON.parse(readFileSync('proof/audit/IW-FULL-FEATURES/inventory.json'));
const report={at:new Date().toISOString(),hashes:Object.fromEntries(['planning/control/ledger.json','scripts/industry-ledger.mjs','planning/control/dashboard.js','planning/control/dashboard.css','proof/audit/IW-FULL-FEATURES/inventory.json'].map(p=>[p,hash(p)])),checks:[],passing:[],pending:[],failures:[]};
const check=(name,ok,details)=>{report.checks.push({name,ok,details});if(!ok)report.failures.push(name);};
const expected=[...data.inventory.features.map(f=>f.id),...Array.from({length:11},(_,i)=>`NEW-${String(i+1).padStart(3,'0')}`)],ids=audit.features.map(f=>f.id);
check('Exact139 historical and11 explicit IDs',ids.length===150&&new Set(ids).size===150&&expected.every(id=>ids.includes(id))&&ids.every(id=>expected.includes(id)),{actual:ids.length,baseline:data.inventory.features.length,new:ids.filter(id=>id.startsWith('NEW-')).length});
check('Standalone inventory same exact ID set',inventory.features.length===150&&inventory.features.every(f=>ids.includes(f.id))&&new Set(inventory.features.map(f=>f.id)).size===150);
const validation=validate(data);check('Canonical feature gate validates',validation.ok,validation.errors);
for(const f of audit.features){if(['untested','running'].includes(f.status))report.pending.push(f.id);check(f.id+' concrete result',typeof f.scenario==='string'&&f.scenario.length>=20&&typeof f.result==='string'&&f.result.length>=20,{status:f.status,scenarioTemplate:f.scenarioTemplate});if(f.status!=='pass')continue;
 const digest=inputDigest(f);const failedCases=(f.cases??[]).filter(c=>c.status!=='pass');check(f.id+' no declared failed/untested case',failedCases.length===0,failedCases);
 const reviewBytes=readFileSync(f.review.path,'utf8');const review=JSON.parse(reviewBytes);let bindings=review.inputs&&typeof review.inputs==='object'&&!Array.isArray(review.inputs)?Object.entries(review.inputs):[];
 check(f.id+' reviewer source hashes current',bindings.length>0&&bindings.every(([p,h])=>hash(p)===h),bindings.map(([path,sha256])=>({path,sha256,current:hash(path)})));
 report.passing.push({id:f.id,owner:f.owner,reviewer:f.review.reviewer,inputDigest:digest,proofClass:f.proofClass,reviewPath:f.review.path,reviewSha256:hash(f.review.path),evidence:f.evidence.map(e=>({path:e.path,kind:e.kind,sha256:e.sha256,screenshot:e.screenshot?.scenario})),scope:f.result});
}
report.counts=audit.features.reduce((a,f)=>(a[f.status]=(a[f.status]||0)+1,a),{});report.finalReady=report.pending.length===0&&report.failures.length===0;writeFileSync(`${dir}/${run}.json`,JSON.stringify(report,null,2));console.log(JSON.stringify({run,counts:report.counts,failures:report.failures,pending:report.pending,finalReady:report.finalReady}));
