import {chromium} from 'playwright';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const dir='proof/audit/IW-CURRENT-WORK/gallery-'+new Date().toISOString().replaceAll(':','-').replaceAll('.','-');mkdirSync(dir,{recursive:true});
const hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex'),browser=await chromium.launch({channel:'msedge',headless:true}),viewport={width:1440,height:1000},page=await browser.newPage({viewport}),errors=[],captures=[];
page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const capture=async(name,scenario)=>{const path=dir+'/'+name+'.png';await page.screenshot({path});captures.push({path,sha256:hash(path),url:page.url(),capturedAt:new Date().toISOString(),viewport,scenario})};
try{await page.goto('http://127.0.0.1:8097/',{waitUntil:'networkidle',timeout:120000});const gallery=page.getByRole('region',{name:'Current execution proof'});assert.equal(await gallery.locator('img').count(),22);await gallery.scrollIntoViewIfNeeded();for(const img of await gallery.locator('img').all()){await img.scrollIntoViewIfNeeded();await img.evaluate(i=>i.decode());}await gallery.locator('figure').first().scrollIntoViewIfNeeded();await capture('gallery-before-after','Actual author-evidence gallery with before/after images');await gallery.locator('figure').nth(11).scrollIntoViewIfNeeded();await capture('gallery-palettes','Actual built palette and source navigation evidence');const link=gallery.getByRole('link',{name:'Executed source report'}).first();assert.equal((await page.request.get('http://127.0.0.1:8097'+await link.getAttribute('href'))).status(),200);assert.deepEqual(errors,[]);writeFileSync(dir+'/results.json',JSON.stringify({at:new Date().toISOString(),images:22,decoded:22,rawReportLink:200,errors,captures,canonicalSha256:hash('planning/control/ledger.json'),scope:'Actual desktop tracker; bounded current packet independently approved. Product images are existing actual app captures.'},null,2));console.log(dir)}finally{await browser.close()}
