import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
const origin=process.argv[2]??'http://127.0.0.1:8080',target=process.argv[3]??'caroline',id=new Date().toISOString().replaceAll(':','-').replaceAll('.','-');
const out=`proof/audit/IW-REAL-3D-VIEWER/run-${id}`,shots=`screenshots/industry-real-3d-viewer/${id}`;mkdirSync(out,{recursive:true});mkdirSync(shots,{recursive:true});
const model=JSON.parse(readFileSync(`public/models/${target}/source-building.json`)),hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex'),results=[],captures=[],errors=[],downloads=[];
const inputs=['src/studio/SourceBuildingViewer.tsx','src/studio/sourceBuilding.ts','src/studio/sourceBuilding.css','src/studio/Studio.tsx','src/studio/documents.ts','package.json','package-lock.json','vite.config.ts',`public/models/${target}/source-building.json`].map(path=>({path,sha256:hash(path)}));
const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const record=(name,detail)=>results.push({name,status:'pass',detail});
const snap=async(name,scenario,phase='after')=>{await page.waitForTimeout(350);const path=`${shots}/${name}.png`;await page.screenshot({path});captures.push({path,sha256:hash(path),url:page.url(),capturedAt:new Date().toISOString(),viewport:{width:1440,height:1000},scenario,phase,kind:'application-ui',result:'Executed scenario',sourceFiles:inputs});};
const canvas=()=>page.locator('canvas[data-source-sha256]');
const ready=async()=>{await page.locator('[data-model-status="ready"]').waitFor();await canvas().waitFor();assert.equal(await canvas().getAttribute('data-source-sha256'),model.source.sha256);await page.waitForTimeout(400);};
const importFile=async payload=>{const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Open plan',exact:true}).click();await(await chooser).setFiles(payload);};
try{
 await page.goto(`${origin}/?pane=model`,{waitUntil:'networkidle'});await page.locator('[data-hydration-status="ready"]').waitFor();await page.getByLabel('Prepared building',{exact:true}).selectOption(target);await page.getByRole('button',{name:/Open .* plan in 3D/}).waitFor();await snap('01-source-before','Original source preview before actual PDF import','before');
 await page.getByRole('button',{name:/Open .* plan in 3D/}).click();await ready();record('Prepared source imports actual PDF and resolves exact identity',{sha256:model.source.sha256,pages:model.source.pageCount,meshCount:await canvas().getAttribute('data-mesh-count')});await snap('02-building','Actual source-matched building with roof');
 const before=hash(captures.at(-1).path),box=await canvas().boundingBox();await page.mouse.move(box.x+box.width*.75,box.y+box.height*.5);await page.mouse.down();await page.mouse.move(box.x+box.width*.75-box.height*.5,box.y+box.height*.5,{steps:20});await page.mouse.up();await page.waitForTimeout(700);await snap('02b-rear','Rear orbit checks source kitchen and porch additions');record('Rear orbit');await page.getByRole('button',{name:'Fit',exact:true}).click();await page.getByRole('button',{name:'Roof on',exact:true}).click();await snap('02c-angled-roof-off','Whole building roof hidden, upper stair opening visible');await page.getByRole('button',{name:'Roof off',exact:true}).click();await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await page.mouse.down();await page.mouse.move(box.x+box.width*.65,box.y+box.height*.53,{steps:12});await page.mouse.up();await snap('03-orbit','Actual pointer drag changes camera');assert.notEqual(hash(captures.at(-1).path),before);record('Orbit pointer drag changes rendered view');
 await page.getByRole('button',{name:'Fit',exact:true}).click();await page.getByRole('button',{name:'Plan',exact:true}).click();assert.equal(await canvas().getAttribute('data-projection'),'orthographic-plan');await snap('04-plan','Orthographic source building plan');record('Plan projection');
 await page.getByRole('button',{name:'Roof on',exact:true}).click();const roofHidden=model.objects.filter(p=>!['roof','roof-trim','solar','skylight'].includes(p.category)).length;assert.equal(Number(await canvas().getAttribute('data-visible-mesh-count')),roofHidden);await snap('05-roof-off','Roof, trim, solar and skylights hidden as one group');record('Roof group exclusion',{visible:roofHidden});
 if(model.objects.some(p=>p.level)){
  await page.getByLabel('Building floor',{exact:true}).selectOption('ground');assert.equal(await canvas().getAttribute('data-level'),'ground');await snap('06-ground','Ground floor only, upper structure and roof hidden');
  await page.getByLabel('Building floor',{exact:true}).selectOption('upper');assert.equal(await canvas().getAttribute('data-level'),'upper');await snap('07-upper','Upper floor only, ground structure hidden');record('Ground and upper floor isolation');await page.getByLabel('Building floor',{exact:true}).selectOption('all');await page.getByRole('button',{name:'Wall cutaway',exact:true}).click();assert.equal(await canvas().getAttribute('data-level'),'ground');assert.equal(await canvas().getAttribute('data-cutaway'),'true');await snap('07b-whole-cutaway','Whole-building cutaway selects ground and removes upper slab');await page.getByLabel('Building floor',{exact:true}).selectOption('upper');assert.equal(await canvas().getAttribute('data-cutaway'),'true');await snap('07c-upper-cutaway','Upper-floor cutaway uses declared elevation');await page.getByRole('button',{name:'Roof off',exact:true}).click();assert.equal(await canvas().getAttribute('data-level'),'all');assert.equal(await canvas().getAttribute('data-cutaway'),'false');record('Whole/ground/upper cutaway and roof transitions');await page.getByLabel('Building floor',{exact:true}).selectOption('upper');
 }
 await page.getByRole('button',{name:'Orbit',exact:true}).click();await page.getByRole('button',{name:'Wall cutaway',exact:true}).click();assert.equal(await canvas().getAttribute('data-cutaway'),'true');await snap('08-cutaway','Wall clipping exposes source interiors at selected floor datum');record('Wall cutaway');
 if(model.objects.some(p=>p.level))await page.getByLabel('Building floor',{exact:true}).selectOption('all');if(await canvas().getAttribute('data-cutaway')==='true')await page.getByRole('button',{name:'Wall cutaway',exact:true}).click();await page.getByRole('button',{name:'Explode',exact:true}).click();assert.equal(await canvas().getAttribute('data-explode'),'true');await snap('09-explode','Exploded structure, camera refitted');record('Explode');await page.getByRole('button',{name:'Explode',exact:true}).click();
 await page.getByRole('button',{name:'Fit',exact:true}).click();await page.mouse.click(box.x+box.width*.5,box.y+box.height*.5);await page.waitForTimeout(200);assert.ok(await canvas().getAttribute('data-selected-part'));record('Actual canvas raycast selects geometry');
 const part=model.objects.find(p=>p.sourceRefs.some(r=>r.dimension))??model.objects[0];await page.locator('.building-part-picker select').selectOption(part.id);assert.equal(await canvas().getAttribute('data-selected-part'),part.id);await snap('10-source-evidence','Selected part displays exact original sheet region and evidence');record('Source evidence selector',{part:part.id,page:part.sourceRefs[0].page});
 const dl=page.waitForEvent('download');await page.getByRole('button',{name:'Download model PNG'}).click();const download=await dl,png=`${shots}/download.png`;await download.saveAs(png);assert.equal(readFileSync(png).subarray(0,8).toString('hex'),'89504e470d0a1a0a');downloads.push({path:png,sha256:hash(png),suggestedFilename:download.suggestedFilename()});record('Actual PNG download');
 await page.reload({waitUntil:'networkidle'});await ready();await snap('11-reload','Original persisted bytes rehashed after reload');record('Persisted original reload matches scene');
 await importFile({name:'unrelated.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><path d="M0 0L100 100"/></svg>')});await page.locator('[data-model-status="unmatched"]').waitFor();assert.equal(await canvas().count(),0);await snap('12-unrelated','Unrelated real file import removes matching building');record('Different source cannot display prepared building');
 await importFile(`public/models/${target}/source.pdf`);await ready();record('Ordinary Open plan of matching original resolves model');
 await importFile({name:'broken.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\n1 0 obj << /Type /Catalog /Pages 9 0 R >> endobj\n%%EOF')});await page.getByRole('alert').waitFor();assert.equal(await canvas().getAttribute('data-source-sha256'),model.source.sha256);await snap('13-rejected','Malformed PDF rejected; previously verified original remains');record('Malformed page tree does not replace source');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('.building-source-image img').evaluate(e=>e.complete&&e.naturalWidth>0),true);assert.deepEqual(errors,[]);record('Desktop content and console',{errors:0,overflow:false});for(const f of inputs)assert.equal(hash(f.path),f.sha256,`Source changed during browser run: ${f.path}`);record('Tested source hashes unchanged throughout run');
}catch(e){results.push({name:'Harness failure',status:'fail',detail:e.stack});await snap('failure','Failure state');process.exitCode=1;}finally{writeFileSync(`${out}/results.json`,JSON.stringify({origin,target,completedAt:new Date().toISOString(),inputs,results,captures,downloads,errors},null,2));console.log(JSON.stringify({out,passed:results.filter(r=>r.status==='pass').length,failed:results.filter(r=>r.status==='fail'),errors}));await browser.close();}
