import {installTrace,paneReady} from './qa-readiness.mjs';
import {checkPlanIsolation} from './plan-isolation-scenarios.mjs';
import {CURRENT_INPUTS} from '../../../scripts/current-work-proof.mjs';
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
const origin=process.argv[2]??'http://127.0.0.1:8080',mode=process.argv[3]??'diagnostic',id=new Date().toISOString().replaceAll(':','-').replaceAll('.','-');
const out=`proof/audit/IW-REAL-3D-VIEWER/precision-${id}`,shots=`screenshots/industry-real-3d-viewer/precision-${id}`;mkdirSync(out,{recursive:true});mkdirSync(shots,{recursive:true});
const hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex'),inputs=CURRENT_INPUTS.map(path=>({path,sha256:hash(path)})),results=[],captures=[],errors=[],downloads=[],observations={};
const sourceSha='f62cf82411d5343fd67f2c51b9a0092d70c885c147f9e7b417a6204b4edf11eb',original='engine/fixtures/caroline-blueprints-renderings-2025-08-08.pdf';assert.equal(hash(original),sourceSha);
const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.stack));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const events=[];await installTrace(page,events);
const record=(name,detail)=>results.push({name,status:'pass',detail});
async function snap(name,scenario,phase='after'){await page.waitForTimeout(400);const path=`${shots}/${name}.png`;await page.screenshot({path});captures.push({path,sha256:hash(path),url:page.url(),capturedAt:new Date().toISOString(),viewport:{width:1440,height:1000},scenario,phase,kind:'application-ui',result:'Executed interaction; pending independent review',sourceFiles:inputs});}
async function nav(name){await page.locator('nav[aria-label="Panes"]').getByRole('button',{name,exact:true}).click();await paneReady(page,name);}
async function manifest(file){await nav('Proof');const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Export current manifest',exact:true}).click();const dl=await pending,path=`${out}/${file}.json`;await dl.saveAs(path);downloads.push({path,sha256:hash(path)});return JSON.parse(readFileSync(path));}
const camera=()=>page.locator('canvas[data-source-sha256]').evaluate(e=>({position:e.dataset.cameraPosition,target:e.dataset.cameraTarget,zoom:e.dataset.cameraZoom,projection:e.dataset.projection}));
const scroll=()=>page.evaluate(()=>({x:scrollX,y:scrollY,main:document.querySelector('.studio-main')?.scrollTop}));
async function circleWheel(lens,canvas,label){
 const box=await lens.boundingBox(),before=await lens.getAttribute('data-zoom'),image=await page.locator('.document-source-page').count()?await page.locator('.document-source-page').first().boundingBox():null,cam=await canvas.getAttribute('data-source-sha256')?await camera():null,sc=await scroll();
 await page.mouse.move(box.x+box.width/2,box.y+box.height/2);
 await page.waitForFunction(sel=>{const e=document.querySelector(sel);return e&&e.getAttribute('data-sample')&&getComputedStyle(e).display!=='none';},cam?'[data-model-scope]':'[data-plan-scope]');
 const eventState=await page.evaluate(({x,y})=>{const e=document.elementFromPoint(x,y);return {target:e?.tagName,dataset:e?{...e.dataset}:null,pane:document.querySelector('.pane-tab.active')?.textContent,lens:[...document.querySelectorAll('[data-model-scope],[data-plan-scope]')].map(e=>({...e.dataset,rect:e.getBoundingClientRect().toJSON()}))};},{x:box.x+box.width/2,y:box.y+box.height/2});observations[label+'Wheel']={box,before,eventState,cam,sc};
 await page.mouse.wheel(0,-100);
 await page.waitForFunction(({sel,before})=>{const e=document.querySelector(sel);return e&&e.getAttribute('data-zoom')!==before;},{sel:cam?'[data-model-scope]':'[data-plan-scope]',before},{timeout:5000});
 const after=await lens.getAttribute('data-zoom');assert.notEqual(after,before,label+' actual native wheel must magnify inside lens');if(cam)assert.deepEqual(await camera(),cam);if(image)assert.deepEqual(await page.locator('.document-source-page').first().boundingBox(),image);assert.deepEqual(await scroll(),sc);await snap(label+'-inside-wheel',label+': native wheel at measured circle center changes lens only');record(label+' inside circular lens wheel preserves main view',{box,before,after,camera:cam,scroll:sc,eventState});}

async function sourceReady(){await page.locator('.document-preview[data-source-ready="true"]').waitFor();await page.locator('.document-source-page').evaluate(e=>e.decode());}
async function sourcePointAtLens(dx,dy,targetSource=null){
 const lens=page.locator('[data-plan-scope]'),lb=await lens.boundingBox(),canvasElement=page.locator('canvas[aria-label]'),canvas=await canvasElement.boundingBox(),size=await canvasElement.evaluate(e=>({width:e.clientWidth,height:e.clientHeight})),image=await page.locator('.document-source-page').boundingBox(),sample=(await lens.getAttribute('data-sample')).split(',').map(Number),left=lb.x-canvas.x,top=lb.y-canvas.y;
 let x=lb.x+lb.width/2+dx,y=lb.y+lb.height/2+dy;
 if(targetSource){const sourcePixelX=image.x-canvas.x+targetSource.x*image.width/1584,sourcePixelY=image.y-canvas.y+targetSource.y*image.height/1224;x=canvas.x+(left+(sourcePixelX-sample[0])*lb.width/sample[2])*canvas.width/size.width;y=canvas.y+(top+(sourcePixelY-sample[1])*lb.height/sample[2])*canvas.height/size.height;}
 const localX=(x-canvas.x)*size.width/canvas.width,localY=(y-canvas.y)*size.height/canvas.height;
 return {click:{x,y},source:{x:(canvas.x+sample[0]+((localX-left)/lb.width)*sample[2]-image.x)*1584/image.width,y:(canvas.y+sample[1]+((localY-top)/lb.height)*sample[2]-image.y)*1224/image.height},sample,image,canvas,size,lens:lb};}

function nearPoint(actual,expected){assert.ok(Math.abs(actual.x-expected.x)<.15&&Math.abs(actual.y-expected.y)<.15,`point mismatch ${JSON.stringify({actual,expected})}`);}
try{
 await page.goto(`${origin}/?pane=model`,{waitUntil:'networkidle'});await page.locator('[data-hydration-status="ready"]').waitFor();await snap('00-before','Original source not yet imported','before');const chooser=page.waitForEvent('filechooser');await page.locator('.studio-header').getByRole('button',{name:'Open plan',exact:true}).click();await(await chooser).setFiles(original);await paneReady(page,'Model');assert.equal(await page.locator('canvas[data-source-sha256]').getAttribute('data-source-sha256'),sourceSha);await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Wireframe',exact:true}).click();const ordinaryCursor=await page.locator('canvas[data-source-sha256]').evaluate(e=>getComputedStyle(e).cursor);await page.getByRole('button',{name:'Scope zoom',exact:true}).click();const modelCanvas=page.locator('canvas[data-source-sha256]'),mb=await modelCanvas.boundingBox();await page.mouse.move(mb.x+mb.width*.55,mb.y+mb.height*.55);const modelLens=page.locator('[data-model-scope="true"]');await modelLens.waitFor({state:'visible'});await snap('01-three-post-model','Actual source model with left right and bottom reticle; top clear');assert.equal(await modelLens.getAttribute('data-reticle'),'three-post');assert.equal(await modelCanvas.evaluate(e=>getComputedStyle(e).cursor),'none');record('Model visible scope hides native cursor',{ordinaryCursor,visible:'none'});await circleWheel(modelLens,modelCanvas,'02-model');
 await page.mouse.move(mb.x+3,mb.y+3);await page.waitForTimeout(350);const cornerBox=await modelLens.boundingBox(),cornerZoom=await modelLens.getAttribute('data-zoom'),cornerCam=await camera();assert.ok(Math.hypot(mb.x+3-cornerBox.x-cornerBox.width/2,mb.y+3-cornerBox.y-cornerBox.height/2)>cornerBox.width/2);await page.mouse.wheel(0,100);await page.waitForTimeout(500);assert.equal(await modelLens.getAttribute('data-zoom'),cornerZoom);assert.notDeepEqual(await camera(),cornerCam);record('Model outside circular lens corner retains ordinary camera zoom',{cornerBox,point:{x:mb.x+3,y:mb.y+3}});await page.mouse.move(100,50);await modelLens.waitFor({state:'hidden'});assert.equal(await modelCanvas.evaluate(e=>getComputedStyle(e).cursor),ordinaryCursor);await page.mouse.move(mb.x+mb.width*.5,mb.y+mb.height*.5);await modelLens.waitFor({state:'visible'});assert.equal(await modelCanvas.evaluate(e=>getComputedStyle(e).cursor),'none');await page.keyboard.press('Escape');assert.equal(await modelCanvas.evaluate(e=>getComputedStyle(e).cursor),ordinaryCursor);record('Model cursor restores after pointer leave and scope off');await page.getByRole('button',{name:'Fit',exact:true}).click();
 await page.waitForTimeout(1200);const paletteCamera=await camera();await page.getByRole('button',{name:'Visual settings',exact:true}).click();const cycle=page.locator('#building-visual-panel').getByRole('button',{name:'Next visual preset',exact:true});assert.equal(await cycle.count(),1);await cycle.click();await page.waitForTimeout(300);assert.deepEqual(await camera(),paletteCamera);await snap('03-palette-cycle','Palette cycle inside Visual settings preserves camera');record('Cycle lives inside settings and preserves camera');await page.keyboard.press('Escape');
 await nav('Sheets');await page.getByRole('button',{name:'Open source page 5',exact:true}).click();await sourceReady();await nav('Measure');await sourceReady();await page.getByRole('button',{name:'Drawing scope',exact:true}).click();await page.locator('[data-plan-scope]').waitFor();await circleWheel(page.locator('[data-plan-scope]'),page.locator('canvas[aria-label]'),'04-measure');
 const planCanvas=page.locator('canvas[aria-label]'),pb=await planCanvas.boundingBox(),lens=page.locator('[data-plan-scope]'),lb=await lens.boundingBox(),zoomBefore=await lens.getAttribute('data-zoom'),imageBefore=await page.locator('.document-source-page').boundingBox();await page.mouse.move(lb.x+3,lb.y+3);await page.mouse.wheel(0,100);await page.waitForTimeout(350);assert.equal(await lens.getAttribute('data-zoom'),zoomBefore);assert.notDeepEqual(await page.locator('.document-source-page').boundingBox(),imageBefore);record('Measure wheel outside circle retains page zoom');
 await page.getByLabel('Known distance',{exact:true}).fill('10');await page.getByRole('button',{name:'Pick two points',exact:true}).click();await page.getByRole('button',{name:'Place scope',exact:true}).click();await page.mouse.click(pb.x+pb.width*.5,pb.y+pb.height*.45);await page.waitForTimeout(250);assert.ok(await page.getByText('0 of 2 points captured',{exact:true}).isVisible());const calA=await sourcePointAtLens(-55,-10),calB=await sourcePointAtLens(55,-10);observations.calibration={calA,calB,knownDistanceM:10,note:'QA chosen span on actual original sheet; validates mapping, not architectural dimension attestation'};await page.mouse.click(calA.click.x,calA.click.y);await page.mouse.click(calB.click.x,calB.click.y);await page.getByRole('button',{name:'Lock scale',exact:true}).click();await page.getByText('Scale is locked for measurements on this sheet.',{exact:true}).waitFor();await snap('05-calibration','Actual two-point lens source calibration locked');
 await page.getByRole('button',{name:/^Snap S$/}).click();await page.getByRole('button',{name:/^Run L$/}).click();const runA=await sourcePointAtLens(-48,30),runB=await sourcePointAtLens(48,30);await page.mouse.click(runA.click.x,runA.click.y);await page.mouse.click(runB.click.x,runB.click.y);await page.getByRole('button',{name:'Finish trace',exact:true}).click();await snap('06-run','Actual source-coordinate run drawn through magnified lens');let runManifest=await manifest('run-before-reload');observations.run={runA,runB,job:runManifest.job};assert.equal(runManifest.job.runs.length,1);nearPoint(runManifest.job.runs[0].points[0],runA.source);nearPoint(runManifest.job.runs[0].points[1],runB.source);const cal=runManifest.job.calibrations.find(c=>c.sheet===4);assert.ok(cal?.locked);const candidate=cal.candidates.find(c=>c.id===cal.selectedCandidateId);nearPoint(candidate.points[0],calA.source);nearPoint(candidate.points[1],calB.source);assert.ok(Math.abs(runManifest.job.runs[0].lengthM-10*96/110)<.03);observations.calibration.saved=cal;record('Actual calibration and run use inverse lens source coordinates',{run:runManifest.job.runs[0],calibration:cal});
 await nav('Measure');await sourceReady();await page.getByRole('button',{name:'Drawing scope',exact:true}).click();await page.getByRole('button',{name:'Place scope',exact:true}).click();
 const vi=await page.locator('.document-source-page').boundingBox();const oldVertex=runManifest.job.runs[0].points[0];await page.mouse.click(vi.x+oldVertex.x*vi.width/1584,vi.y+oldVertex.y*vi.height/1224);
 await page.getByRole('button',{name:'Select',exact:true}).click();const selectStart=await sourcePointAtLens(0,0),selectEnd=await sourcePointAtLens(25,25);await page.mouse.move(selectStart.click.x,selectStart.click.y);await page.mouse.down();await page.mouse.move(selectEnd.click.x,selectEnd.click.y,{steps:8});await page.mouse.up();const selectedOnly=await manifest('run-select-no-mutation');assert.deepEqual(selectedOnly.job.runs[0].points,runManifest.job.runs[0].points);record('Explicit Select on existing run vertex never moves source geometry');
 async function prepareMove(){await nav('Measure');await sourceReady();await page.getByRole('button',{name:'Drawing scope',exact:true}).click();await page.getByRole('button',{name:'Place scope',exact:true}).click();const mi=await page.locator('.document-source-page').boundingBox();await page.mouse.click(mi.x+oldVertex.x*mi.width/1584,mi.y+oldVertex.y*mi.height/1224);await page.getByRole('button',{name:'Move vertex',exact:true}).click();return {start:await sourcePointAtLens(0,0),end:await sourcePointAtLens(25,25)};}
 const cancelMove=await prepareMove();await page.mouse.move(cancelMove.start.click.x,cancelMove.start.click.y);await page.mouse.down();await page.mouse.move(cancelMove.end.click.x,cancelMove.end.click.y,{steps:8});await page.keyboard.press('Escape');await page.mouse.up();const cancelled=await manifest('run-move-escape-cancelled');assert.deepEqual(cancelled.job.runs[0].points,runManifest.job.runs[0].points);assert.equal(cancelled.job.runs[0].revision,runManifest.job.runs[0].revision);record('Escape cancels actual multi-event Move preview without saved point or revision change');
 const move=await prepareMove(),vertexStart=move.start,vertexEnd=move.end;await page.mouse.move(vertexStart.click.x,vertexStart.click.y);await page.mouse.down();await page.mouse.move(vertexEnd.click.x,vertexEnd.click.y,{steps:8});await page.mouse.up();await snap('06b-vertex-moved','Actual selected run vertex moved through fixed magnified lens as one gesture');
 const moved=await manifest('run-vertex-edited');assert.equal(moved.job.runs[0].revision,runManifest.job.runs[0].revision+1);nearPoint(moved.job.runs[0].points[0],vertexEnd.source);assert.notDeepEqual(moved.job.runs[0].points[0],oldVertex);assert.deepEqual(moved.job.runs[0].points[1],runManifest.job.runs[0].points[1]);record('Actual run vertex drag inverse maps through lens and commits',{before:oldVertex,after:moved.job.runs[0].points[0],expected:vertexEnd.source});await nav('Measure');await page.getByRole('button',{name:'Undo last trace edit',exact:true}).click();const undo=await manifest('run-vertex-undo');assert.deepEqual(undo.job.runs[0].points,runManifest.job.runs[0].points);await nav('Measure');await page.getByRole('button',{name:'Redo trace edit',exact:true}).click();const redo=await manifest('run-vertex-redo');assert.deepEqual(redo.job.runs[0].points,moved.job.runs[0].points);record('Explicit Move vertex gesture undo and redo restores exact coordinates');runManifest=redo;
 await page.reload({waitUntil:'networkidle'});await page.locator('[data-hydration-status="ready"]').waitFor();const restored=await manifest('run-after-reload');assert.deepEqual(restored.job.runs,runManifest.job.runs);record('Lens-created run coordinates persist after reload');
 await nav('Sheets');await page.getByRole('button',{name:'Open source page 5',exact:true}).click();await sourceReady();await nav('Sketch');await sourceReady();await page.getByRole('button',{name:'Drawing scope',exact:true}).click();await page.locator('[data-plan-scope]').waitFor();await circleWheel(page.locator('[data-plan-scope]'),page.locator('canvas[aria-label]'),'07-sketch');const sketchSnap=page.getByTitle('Toggle Vector Snapping (S)',{exact:true});if((await sketchSnap.innerText()).includes('ON'))await sketchSnap.click();await page.getByRole('button',{name:/^Manual layer M$/}).click();const skA=await sourcePointAtLens(-35,35),skB=await sourcePointAtLens(35,35);await page.mouse.click(skA.click.x,skA.click.y);await page.mouse.click(skB.click.x,skB.click.y);await page.getByRole('button',{name:/^Commit trace/}).click();await snap('08-sketch','Manual sketch source line created through actual lens');observations.sketch={skA,skB,text:await page.locator('.studio-main').innerText()};assert.match(observations.sketch.text,/Manual trace/i);record('Actual source Sketch through lens creates line',observations.sketch);
 const skManifest=await manifest('sketch-source-points');const savedSketch=skManifest.job.annotations.find(item=>item.kind==='sketch');nearPoint(savedSketch.points[0],skA.source);nearPoint(savedSketch.points[1],skB.source);assert.equal(savedSketch.sourceSha256,sourceSha);record('Sketch commits exact source coordinates with original hash',savedSketch);
 await nav('Measure');await sourceReady();await page.getByRole('button',{name:'Drawing scope',exact:true}).click();await page.getByRole('button',{name:/^Area A$/}).click();await page.getByRole('button',{name:'Place scope',exact:true}).click();const areaImage=await page.locator('.document-source-page').boundingBox();const overlapVertex=runManifest.job.runs[0].points[0];await page.mouse.click(areaImage.x+overlapVertex.x*areaImage.width/1584,areaImage.y+overlapVertex.y*areaImage.height/1224);await snap('09-area-overlap-before','Area tool starts exactly on existing selected run vertex');
 const areaPoints=await Promise.all([sourcePointAtLens(0,0,overlapVertex),sourcePointAtLens(55,-30),sourcePointAtLens(40,55)]);observations.area={areaPoints,overlapVertex};for(const point of areaPoints)await page.mouse.click(point.click.x,point.click.y);await page.getByRole('button',{name:'Finish trace',exact:true}).click();await snap('09-area','Actual three-point area polygon created through inverse-mapped source lens');
 const areaManifest=await manifest('area-source-points'),savedArea=areaManifest.job.annotations.find(item=>item.kind==='area');assert.ok(savedArea);assert.deepEqual(areaManifest.job.runs[0].points,runManifest.job.runs[0].points);nearPoint(savedArea.points[0],overlapVertex);for(let i=0;i<3;i++)nearPoint(savedArea.points[i],areaPoints[i].source);assert.equal(savedArea.sourceSha256,sourceSha);
 await page.reload({waitUntil:'networkidle'});await page.locator('[data-hydration-status="ready"]').waitFor();const areaRestored=await manifest('area-after-reload');assert.deepEqual(areaRestored.job.annotations,areaManifest.job.annotations);record('Actual lens area polygon and sketch retain exact source points after reload',{area:savedArea,points:areaPoints});
 await checkPlanIsolation({page,nav,snap,record,manifest,sourceReady});
 assert.deepEqual(errors,[]);record('Precision clean console');const changed=inputs.filter(f=>hash(f.path)!==f.sha256);if(mode==='final')assert.deepEqual(changed,[]);record('Source freeze disclosure',{mode,changed});
}catch(e){results.push({name:'Precision harness or product failure',status:'fail',detail:e.stack});await snap('failure','Preserved precision failure');process.exitCode=1;}finally{writeFileSync(`${out}/results.json`,JSON.stringify({origin,target:'caroline',environment:origin.includes('8081')?'built':'dev',mode,completedAt:new Date().toISOString(),inputs,events,results,captures,downloads,errors,observations},null,2));console.log(JSON.stringify({out,shots,passed:results.filter(r=>r.status==='pass').length,failed:results.filter(r=>r.status==='fail'),errors}));await browser.close();}

