import {readFileSync,writeFileSync,existsSync,statSync}from'node:fs';import{createHash}from'node:crypto';import{spawnSync}from'node:child_process';import{CURRENT_INPUTS}from'../../../scripts/current-work-proof.mjs';
const root='proof/audit/IW-REAL-3D-VIEWER',hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex'),input=path=>({path,sha256:hash(path),bytes:statSync(path).size}),files=['src/studio/SourceBuildingViewer.tsx','src/studio/sourceBuilding.ts','src/studio/sourceBuilding.css','src/studio/sourceBuilding.test.ts','src/studio/documentsComplex.test.ts','src/studio/Studio.tsx','src/studio/documents.ts','src/studio/BuildingVisualSettings.tsx','src/studio/buildingAppearance.ts','src/studio/buildingAppearance.test.ts','src/studio/ModelScope.ts','src/studio/ModelScope.test.ts','vite.config.ts','package.json','package-lock.json'];
function git(args){const r=spawnSync('git',args,{encoding:'utf8',maxBuffer:20*1024*1024});if(r.status!==0)throw Error(r.stderr);return r.stdout}
for(const [base,name]of[['6803da9','current-branch-code.patch'],['bf1f20e','cumulative-viewer-code.patch']]){let patch=git(['diff','--binary',base,'--',...files]);for(const p of files){const tracked=git(['ls-files','--',p]).trim();if(!tracked&&existsSync(p)){const text=readFileSync(p,'utf8');patch+=`diff --git a/${p} b/${p}\nnew file mode 100644\n--- /dev/null\n+++ b/${p}\n@@ -0,0 +1,${text.split('\n').length-1} @@\n`+text.trimEnd().split('\n').map(v=>'+'+v).join('\n')+'\n';}}writeFileSync(`${root}/${name}`,patch)}
const names=['run-2026-09-05T10-18-54-717Z','visual-2026-09-05T10-24-00-293Z','detail-2026-09-05T10-22-34-357Z','stairs-2026-09-05T10-25-12-297Z','run-2026-09-05T10-19-51-224Z','visual-2026-09-05T10-24-11-364Z','detail-2026-09-05T10-22-48-311Z','stairs-2026-09-05T10-25-23-578Z'];
const inputs=CURRENT_INPUTS.map(input),reports=names.map(name=>{const path=`${root}/${name}/results.json`,r=JSON.parse(readFileSync(path));if(r.results.some(v=>v.status!=='pass')||r.errors.length)throw Error('Failed report '+path);for(const f of r.inputs)if(hash(f.path)!==f.sha256)throw Error('Stale '+f.path);if(r.inputs.length!==42)throw Error('Wrong inputs');return{...input(path),environment:r.environment,cases:r.results.length,captures:r.captures.length}}),captures=names.flatMap(name=>JSON.parse(readFileSync(`${root}/${name}/results.json`)).captures.map(c=>({...c,report:`${root}/${name}/results.json`})));
writeFileSync(`${root}/final-source-files.json`,JSON.stringify(inputs,null,2));const superseded=captures.filter(c=>c.path.endsWith("/02e-front-stair-closeup.png"));
writeFileSync(`${root}/final-screenshot-manifest.json`,JSON.stringify(captures.filter(c=>!c.path.endsWith("/02e-front-stair-closeup.png")),null,2));
const packet={schema:'xray.viewer-submission/v1',task:'IW-REAL-3D-VIEWER/IW-WIREFRAME/IW-VISUAL-SETTINGS',author:'/root/audit_engine_release',reviewStatus:'awaiting-parent-final-packet-review',sealedAt:new Date().toISOString(),branch:git(['branch','--show-current']).trim(),head:git(['rev-parse','HEAD']).trim(),dirtyDisclosure:'Working tree contains shared task changes; this author did not commit, push or stage.',inputs,reports,proofs:['current-branch-code.patch','cumulative-viewer-code.patch','final-source-files.json','final-screenshot-manifest.json','build-2026-09-05T10-17-06-844Z.json','build-2026-09-05T10-17-06-844Z.log','typecheck-2026-09-05T10-17-07-746Z.json','typecheck-2026-09-05T10-17-07-746Z.log','studio-tests-2026-09-05T10-17-13.641Z.log'].map(p=>input(`${root}/${p}`)),commands:{build:'node proof/audit/IW-REAL-3D-VIEWER/gates.mjs build',typecheck:'node proof/audit/IW-REAL-3D-VIEWER/gates.mjs typecheck',studio:'node proof/audit/IW-REAL-3D-VIEWER/studio-tests.mjs',browser:'node proof/audit/IW-REAL-3D-VIEWER/{browser,visual-browser,detail-browser,stairs-browser}.mjs http://127.0.0.1:{8080,8081}'},results:{studioTests:284,studioFailures:0,rawDevPassEntries:40,rawBuiltPassEntries:40,acceptedScopedDevChecks:39,acceptedScopedBuiltChecks:39,browserErrors:0},limits:['Curated source-linked reconstruction, not automatic arbitrary PDF semantic conversion.','Approximate preliminary dimensions and inferred details remain declared; not construction-ready/BOM-authoritative.','SVG is a fixed Python axonometric/ground/upper X-ray projection; no current camera/cutaway match claim.','Offline claims only running local server without internet, and already-loaded model with all networking off; offline installed restart not tested.','PNG exports main scene and attribution; scope is an inspection overlay, not baked into main model PNG.','Historical Ruffles sample retains known visual limitations.','No mobile QA per user instruction.'],supersededCaptures:superseded.map(c=>({path:c.path,reason:'High-angle selected stair lens showed occluding porch roof; replaced by low-front stairs report03-stair-scope.'})),handover:input('planning/handovers/IW-VISUAL-SETTINGS/completion.md')};
writeFileSync(`${root}/final-writer-packet.json`,JSON.stringify(packet,null,2));console.log(JSON.stringify({packet:input(`${root}/final-writer-packet.json`),reports:reports.map(r=>({path:r.path,cases:r.cases})),captures:captures.length,inputs:inputs.length}));
