import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {CURRENT_INPUTS} from '../../../scripts/current-work-proof.mjs';
const origin=process.argv[2]??'http://127.0.0.1:8080',environment=origin.includes('8081')?'built':'dev',id=new Date().toISOString().replaceAll(':','-').replaceAll('.','-');
const out=`proof/audit/IW-REAL-3D-VIEWER/visual-${id}`,shots=`screenshots/industry-real-3d-viewer/visual-${id}`;mkdirSync(out,{recursive:true});mkdirSync(shots,{recursive:true});
const hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex'),inputs=CURRENT_INPUTS.map(path=>({path,sha256:hash(path)})),results=[],captures=[],errors=[],downloads=[];
const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}});
page.on('pageerror',e=>errors.push(e.stack));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const record=(name,detail)=>results.push({name,status:'pass',detail});
const snap=async(name,scenario,phase='after')=>{await page.waitForTimeout(250);const path=`${shots}/${name}.png`;await page.screenshot({path});captures.push({path,sha256:hash(path),url:page.url(),capturedAt:new Date().toISOString(),viewport:{width:1440,height:1000},scenario,phase,kind:'application-ui',result:'Executed scenario',sourceFiles:inputs});};
const canvas=()=>page.locator('canvas[data-source-sha256]');const settle=()=>page.waitForTimeout(600);
const camera=()=>canvas().evaluate(e=>[e.dataset.cameraPosition,e.dataset.cameraTarget,e.dataset.cameraZoom,e.dataset.projection]);
const appearance=()=>canvas().evaluate(e=>JSON.parse(e.dataset.appearance));
const ready=async()=>{await page.locator('[data-model-status="ready"]').waitFor();await canvas().waitFor();await settle();};
try {
 await page.goto(`${origin}/?pane=model`,{waitUntil:'networkidle'});await page.locator('[data-hydration-status="ready"]').waitFor();await snap('01-before','Before actual Caroline source import and visual controls','before');
 await page.getByRole('button',{name:/Open .* plan in 3D/}).click();await ready();await snap('02-solid','Actual source-matched Caroline solid model with restored left rail');
 const originalCamera=await camera();await page.getByRole('button',{name:'Wireframe',exact:true}).click();await settle();assert.deepEqual(await camera(),originalCamera);assert.equal(await canvas().getAttribute('data-display-mode'),'wireframe');await snap('03-wireframe','Solid to genuine X-ray edge wireframe preserves camera');record('Solid/wireframe toggle preserves actual camera');
 await page.getByRole('button',{name:'Visual settings',exact:true}).click();
 for(const [preset,bg,wire] of [['silver','#737A84','#FFFFFF'],['gold','#090B0E','#D7B96E'],['paper','#FFFFFF','#34383E']]){await page.getByLabel('Visual preset',{exact:true}).selectOption(preset);await settle();assert.equal((await appearance()).background,bg);assert.equal((await appearance()).wire,wire);assert.deepEqual(await camera(),originalCamera);await snap(`04-${preset}`,`Actual ${preset} palette applied without camera or geometry changes`);}
 record('Three required palettes render and preserve camera');
 await page.getByLabel('Background hex',{exact:true}).fill('#18202B');await page.getByLabel('Background hex',{exact:true}).press('Tab');await page.getByLabel('Wire color hex',{exact:true}).fill('#E6BD73');await page.getByLabel('Wire color hex',{exact:true}).press('Tab');
 await page.getByLabel('Wire opacity',{exact:true}).focus();await page.keyboard.press('Home');for(let i=0;i<10;i++)await page.keyboard.press('ArrowRight');
 await page.getByLabel('Lighting intensity',{exact:true}).focus();await page.keyboard.press('Home');for(let i=0;i<12;i++)await page.keyboard.press('ArrowRight');await page.getByRole('checkbox',{name:'Cast shadows in solid view'}).uncheck();await settle();
 const custom=await appearance();assert.equal(custom.background,'#18202B');assert.equal(custom.wire,'#E6BD73');assert.equal(custom.opacity,.6);assert.equal(custom.lighting,1.4);assert.equal(custom.shadows,false);assert.deepEqual(await camera(),originalCamera);await snap('05-custom','Keyboard-edited custom colours, opacity, lighting and shadow state');record('Live custom controls',{custom});
 await page.getByRole('button',{name:'Close visual settings'}).click();
 const svgPromise=page.waitForEvent('download');await page.getByRole('button',{name:/SVG \/ fixed axonometric/}).click();const svg=await svgPromise,svgPath=`${out}/custom-axonometric.svg`;await svg.saveAs(svgPath);const svgText=readFileSync(svgPath,'utf8');assert.ok(svgText.includes('#18202B')&&svgText.includes('#E6BD73'));assert.ok(svgText.includes('viewer-appearance'));assert.ok(!svgText.includes('<image'));downloads.push({path:svgPath,sha256:hash(svgPath)});
 const svgPage=await browser.newPage({viewport:{width:1600,height:1600}});await svgPage.route("**/captured-export.svg", route => route.fulfill({ status: 200, contentType: "image/svg+xml", body: svgText }));await svgPage.goto(`${origin}/captured-export.svg`);await svgPage.screenshot({path:`${shots}/06-svg-download.png`});await svgPage.close();record('Actual SVG download retains vectors, source metadata and selected palette');
 const pngPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download model PNG'}).click();const png=await pngPromise,pngPath=`${shots}/07-wireframe-download.png`;await png.saveAs(pngPath);assert.equal(readFileSync(pngPath).subarray(0,8).toString('hex'),'89504e470d0a1a0a');downloads.push({path:pngPath,sha256:hash(pngPath)});record('Actual wireframe PNG download');
 await page.getByRole('button',{name:'Open source page 5',exact:true}).click();await page.locator('.document-preview[data-source-ready="true"]').waitFor();await page.locator('.document-preview-page').filter({hasText:/^Page 5$/}).waitFor();await page.waitForFunction(()=>{const image=document.querySelector('.document-source-page');return image instanceof HTMLImageElement&&image.complete&&image.naturalWidth>0&&document.querySelector('.document-preview')?.getAttribute('data-source-ready')==='true'});const page5src=await page.locator('.document-source-page').getAttribute('src');await snap('08-sheet5','Persistent left rail opens original page 5');
 await page.getByRole('button',{name:'Open source page 6',exact:true}).click();await page.locator('.document-preview-page').filter({hasText:/^Page 6$/}).waitFor();await page.waitForFunction(old=>{const image=document.querySelector('.document-source-page');return image instanceof HTMLImageElement&&image.src!==old&&image.complete&&image.naturalWidth>0&&document.querySelector('.document-preview')?.getAttribute('data-source-ready')==='true'},page5src);await snap('09-sheet6','Left rail switches to actual original page 6');await page.getByRole('button',{name:'Source building',exact:true}).click();await ready();assert.equal(await canvas().getAttribute('data-display-mode'),'wireframe');assert.deepEqual(await appearance(),custom);record('Page 5 / page 6 / Model round trip preserves original identity and viewer options');
 await page.getByRole('button',{name:'Scope zoom',exact:true}).click();const box=await canvas().boundingBox(),point={x:box.x+box.width*.48,y:box.y+box.height*.53};await page.mouse.move(point.x,point.y);await settle();const scope=page.locator('[data-model-scope="true"]');await scope.waitFor({state:'visible'});const scopeCamera=await camera();
 await page.getByRole('button',{name:'Visual settings',exact:true}).click();const scopeImages=[];
 for(const zoom of ['2','4','8']){await page.getByLabel('Scope magnification',{exact:true}).selectOption(zoom);await page.mouse.move(point.x,point.y);await settle();assert.equal(await scope.getAttribute('data-zoom'),zoom);assert.deepEqual(await camera(),scopeCamera);scopeImages.push(await scope.locator('canvas').evaluate(e=>e.toDataURL()));await snap(`10-scope-${zoom}`,`Actual perspective camera-crop magnifier ${zoom}x, main view unchanged`);}
 assert.equal(new Set(scopeImages).size,3);await page.waitForTimeout(1000);const idle=await canvas().getAttribute('data-frame-count');await page.waitForTimeout(600);assert.equal(await canvas().getAttribute('data-frame-count'),idle);record('Scope demand rendering stops while pointer and controls are idle');record('True scope magnification 2x/4x/8x gives different pixels and preserves main camera');
 for(const key of ['Home','End']){await page.getByLabel('Scope diameter',{exact:true}).focus();await page.keyboard.press(key);await page.mouse.move(point.x,point.y);await settle();assert.equal(Math.round((await scope.boundingBox()).width),key==='Home'?160:360);}record('Scope diameter boundaries');
 await page.mouse.move(20,20);await scope.waitFor({state:'hidden'});await page.mouse.move(point.x,point.y);await scope.waitFor({state:'visible'});await page.keyboard.press('Escape');await scope.waitFor({state:'hidden'});assert.equal(await page.getByRole('button',{name:'Scope zoom'}).getAttribute('aria-pressed'),'false');record('Pointer leave hides scope; Escape disables with matching control state');
 await page.getByRole('button',{name:'Plan',exact:true}).click();await page.getByRole('button',{name:'Scope zoom'}).click();await page.mouse.move(point.x,point.y);await settle();assert.equal(await scope.getAttribute('data-projection'),'OrthographicCamera');await snap('11-scope-plan','Actual orthographic model scope');record('Orthographic scope projection');await page.keyboard.press('Escape');
 await page.reload({waitUntil:'networkidle'});await ready();assert.deepEqual(await appearance(),custom);await snap('12-reload','Saved custom visual preferences restored with original source identity');record('Local preferences reload');
 await page.getByRole('button',{name:'Visual settings',exact:true}).click();await page.getByRole('button',{name:'Reset appearance'}).click();assert.equal((await appearance()).preset,'chrome');await page.getByRole('button',{name:'Next visual preset'}).click();assert.equal((await appearance()).preset,'silver');await page.keyboard.press('Escape');assert.equal(await page.getByRole('button',{name:'Visual settings',exact:true}).getAttribute('aria-expanded'),'false');record('Reset, cycle and keyboard panel dismissal');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);for(const f of inputs)assert.equal(hash(f.path),f.sha256,`Source changed: ${f.path}`);record('No browser errors, desktop overflow, or source mutation');
} catch(e){results.push({name:'Harness failure',status:'fail',detail:e.stack});await snap('failure','Actual failed test state');process.exitCode=1;}finally{writeFileSync(`${out}/results.json`,JSON.stringify({origin,target:"caroline",environment,completedAt:new Date().toISOString(),inputs,results,captures,downloads,errors},null,2));console.log(JSON.stringify({out,results,errors}));await browser.close();}
