import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {resolve} from 'node:path';
const url=process.argv[2]??'http://127.0.0.1:8080/';
const mode=url.includes('8081')?'built':'dev';
const dir=resolve('screenshots/altitude-takeoff',mode);mkdirSync(dir,{recursive:true});
const browser=await chromium.launch({headless:true,channel:'msedge'});
const context=await browser.newContext({viewport:{width:1600,height:1100}});
const page=await context.newPage();page.setDefaultTimeout(30000);
const report={url,checks:[],errors:[],screenshots:[]};
page.on('pageerror',e=>report.errors.push(e.message));
page.on('console',e=>{if(e.type()==='error')report.errors.push(e.text());});
async function shot(name){const path=resolve(dir,name+'.png');await page.screenshot({path,fullPage:true});report.screenshots.push(path);}
async function ready(){await page.waitForFunction(()=>!document.querySelector('.workbench-loading'));}
async function components(){await page.getByRole('button',{name:'Components',exact:true}).click();await page.getByRole('region',{name:'Altitude source takeoff'}).waitFor();}
async function readSaved(){return page.evaluate(()=>{const key=Object.keys(localStorage).find(k=>k.startsWith('xray:source-takeoff:'));return {key,raw:localStorage.getItem(key)};});}
try{
 await page.goto(url,{waitUntil:'domcontentloaded'});await ready();
 const picker=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Open plan',exact:true}).first().click();
 await(await picker).setFiles(resolve('downloads/high_rise_plans/03_Seattle_Altitude_Hotel_and_Residences_50Story_Tower.pdf'));
 await page.locator('.document-preview[data-source-ready="true"]').waitFor({timeout:60000});
 await components();
 await page.getByRole('button',{name:'Save inventory',exact:true}).click();
 const first=await readSaved();assert.ok(first.key);const value=JSON.parse(first.raw);
 assert.deepEqual(value.rows.map(r=>r.countPerFloor),[9,19,null,null,null]);
 assert.equal(await page.getByText('Demonstration Dataset',{exact:true}).count(),0);
 const downloadPromise=page.waitForEvent('download');
 await page.getByRole('button',{name:'Export count',exact:true}).click();
 const exportPath=resolve(dir,'exported-count.json');await(await downloadPromise).saveAs(exportPath);
 const exported=JSON.parse(readFileSync(exportPath,'utf8'));
 assert.deepEqual(exported.groups.map(g=>g.quantity),[252,209,null,null,null]);
 assert.equal(exported.sourceSha256,value.sourceSha256);
 report.checks.push('Actual Altitude PDF selects source-bound inventory; no demonstration count shown. Five persisted groups with unknown quantities retained.');
 await shot('01-source-count');
 await page.getByRole('button',{name:'View source page 48',exact:true}).click();
 await page.locator('.document-preview[data-source-ready="true"]').waitFor();
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('xray:fencing-job:v2')).activeSheet),47);
 await components();
 await page.getByLabel('Count / review note',{exact:true}).fill('QA: reviewed source count only');
 await page.getByLabel('Count reviewed against source',{exact:true}).check();
 await page.getByRole('button',{name:'Save group',exact:true}).click();
 assert.equal(JSON.parse((await readSaved()).raw).rows[0].review,'reviewed');
 await page.getByLabel('Count per typical floor',{exact:true}).fill('8');
 await page.getByRole('button',{name:'Save group',exact:true}).click();
 assert.equal(JSON.parse((await readSaved()).raw).rows[0].review,'pending');
 await page.getByLabel('Count per typical floor',{exact:true}).fill('9');
 for(const [label,v] of [['Counted items per package','10'],['Package length (m)','2'],['Package width (m)','1'],['Package height (m)','.5'],['Specified weight per item (kg)','12']])await page.getByLabel(label,{exact:true}).fill(v);
 await page.getByLabel('Supplier / specification reference',{exact:true}).fill('QA TEST VALUES ONLY - fictional complete assembly package; not project specification');
 await page.getByRole('button',{name:'Save group',exact:true}).click();
 assert.ok((await page.locator('.takeoff-summary').innerText()).includes('26 m³'));
 assert.ok((await page.locator('.takeoff-summary').innerText()).includes('3,024 kg'));
 await shot('02-qa-packaging-calculation');
 await page.reload({waitUntil:'domcontentloaded'});await ready();await components();
 assert.equal(await page.getByLabel('Package length (m)',{exact:true}).inputValue(),'2');
 report.checks.push('Evidence opens original page 48; review invalidated on changed count; QA-only package rounding gives 26 m3 and 3024 kg with 1/5 coverage; inputs survive reload.');
 for(const label of ['Counted items per package','Package length (m)','Package width (m)','Package height (m)','Specified weight per item (kg)'])await page.getByLabel(label,{exact:true}).fill('');
 await page.getByLabel('Supplier / specification reference',{exact:true}).fill('');
 await page.getByLabel('Count / review note',{exact:true}).fill('');
 await page.getByRole('button',{name:'Save group',exact:true}).click();
 await page.getByRole('button',{name:'Windows',exact:true}).click();
 assert.equal(await page.locator('.takeoff-row').count(),2);
 await page.locator('.takeoff-row').first().click();
 assert.equal(await page.getByLabel('Count per typical floor',{exact:true}).inputValue(),'');
 await page.getByRole('button',{name:'All',exact:true}).click();
 await page.locator('.takeoff-row').first().click();
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await shot('03-mobile-count');
 const before=await readSaved();const future=JSON.stringify({...JSON.parse(before.raw),schema:'xray.source-takeoff/v99'});
 await page.evaluate(({key,raw})=>localStorage.setItem(key,raw),{key:before.key,raw:future});
 await page.reload({waitUntil:'domcontentloaded'});await ready();await components();
 assert.equal(await page.getByRole('button',{name:'Save inventory',exact:true}).isDisabled(),true);
 assert.equal(await page.getByRole('button',{name:'Save group',exact:true}).isDisabled(),true);
 await page.getByRole('button',{name:'Retry restore',exact:true}).click();
 assert.equal((await readSaved()).raw,future);
 await shot('04-protected-restore');
 await page.evaluate(({key,raw})=>localStorage.setItem(key,raw),before);
 await page.getByRole('button',{name:'Retry restore',exact:true}).click();
 assert.equal(await page.getByRole('button',{name:'Save inventory',exact:true}).isEnabled(),true);
 report.checks.push('Windows filter keeps unknown quantities; mobile has no horizontal overflow; future schema blocks ordinary saves and retry preserves exact bytes; restored data recovers.');
 await page.setViewportSize({width:1600,height:1100});
 await shot('05-final-inventory');
 const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Open plan',exact:true}).first().click();
 await(await chooser).setFiles(resolve('public/models/caroline/source.pdf'));
 await page.waitForFunction(()=>{const j=JSON.parse(localStorage.getItem('xray:fencing-job:v2'));return j.documents.find(d=>d.id===j.activeDocumentId)?.sha256==='f62cf82411d5343fd67f2c51b9a0092d70c885c147f9e7b417a6204b4edf11eb';});
 await page.getByRole('button',{name:'Sheets',exact:true}).click();
 await page.locator('.document-preview[data-source-ready="true"]').waitFor({timeout:60000});
 await page.getByRole('button',{name:'Components',exact:true}).click();
 assert.equal(await page.getByRole('region',{name:'Altitude source takeoff'}).count(),0);
 assert.equal((await readSaved()).raw,before.raw);
 report.checks.push('Opening Caroline hides Altitude takeoff and preserves its saved bytes.');
 assert.deepEqual(report.errors,[]);
 console.log(JSON.stringify(report,null,2));
}catch(e){report.failure=String(e);await shot('failure');throw e;}
finally{writeFileSync(resolve(dir,'report.json'),JSON.stringify(report,null,2));await browser.close();}
