import fs from 'node:fs';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
const base='proof/growth/2026-09-08-production-pencil/2026-09-08-8095-pencil-final-01';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''));
const manifest=read(base+'/prepared-manifest.json'),inspection=read(base+'/download-inspection.json');
const source=read('proof/growth/2026-09-08-assistant-mcp-r4/transfer/source-manifest.json');
const transfer=read('proof/growth/2026-09-08-assistant-mcp-r4/transfer.json');
const web=read('proof/growth/2026-09-08-assistant-mcp-r4/release-71f5b012342b/web-artifact-manifest.json');
for(const file of manifest.source)assert.equal(source.entries.find(entry=>entry.path===file.file)?.sha256,file.sha256,file.file+' mismatches built snapshot');
const logIds=['2026-09-08T03-56-55-380Z-growth-pencil-production-r4','2026-09-08T03-56-55-556Z-growth-pencil-controls-r4','2026-09-08T03-57-28-179Z-growth-pencil-production-r4'];
const logs=logIds.map(id=>read(`proof/growth/runner/${id}.json`));assert.ok(logs.every(log=>log.exitCode===0));
const shot=(name,caption)=>({file:`screenshots/growth/${manifest.tag}-${name}.png`,caption});
const images=[
  shot('production-controls-landscape-top-scroll','Final build, 1024×768: original top settings, drafting actions, assistant launcher and restored bottom navigation are separately reachable.'),
  shot('production-controls-landscape','Final build, 1024×768: lower scroll state exposes the phase controls while the top settings stay clear.'),
  shot('production-controls-portrait','Final build, 768×1024: all five bottom navigation buttons remain visible and independent of the drafting panel.'),
  shot('production-controls-desktop','Final build, 1440×900: complete model, drafting panel and separate bottom navigation.'),
  {file:inspection.files[0].file,caption:'Actual immediate PNG download: Solid Finish and Blueprint were invoked without yielding to an animation frame. The completed 2,180-part tower is visibly present.'},
  ...inspection.pdf.pages.map((page,i)=>({file:page.file,caption:`Actual downloaded PDF, page ${page.page}: ${['all 33 supplied Crown Wharf levels; model coordinates, no surveyed datum','lowest level triangle projection; triangulation is explicitly retained','upper level model projection; no invented core or partitions','X/Y elevation projection, explicitly not a cut section','actual current model snapshot'][i]}. Every page is illustrative, NTS and not for construction.`})),
  {file:'screenshots/growth/2026-09-08-8093-pencil-01-tablet-portrait-restored.png',caption:'Historical failure, build 4e6d1ebd3a62: preview lacked the separate bottom navigation. Preserved as before evidence, not accepted as the final result.'},
  {file:'screenshots/growth/2026-09-08-dev-bottom-r3-landscape.png',caption:'Historical development finding after restoring the bottom bar: the expanded drafting panel overlapped the lower edge of top settings. The final build dynamically reserves toolbar clearance.'},
].map(item=>({...item,sha256:createHash('sha256').update(fs.readFileSync(item.file)).digest('hex')}));
const checks=[
  {name:'Rapid PNG export',status:'PASS',evidence:'Frame count 8 → 8; Solid Finish applied; 2,180 / 2,180 meshes visible. Actual PNG decoded and visually inspected.'},
  {name:'Actual PDF download',status:'PASS',evidence:'Five real A4 landscape image pages parsed, rendered and visually inspected; 33 supplied levels retained; truthful preview labels.'},
  {name:'Bottom model navigation',status:'PASS',evidence:'Zoom changes camera distance; Front and Rear place the camera on opposite Z sides; Reset restores its original distance.'},
  {name:'Desktop and tablet reachability',status:'PASS',evidence:'1440×900, 1024×768 and 768×1024. All five navigation buttons, drafting buttons/select and assistant launcher meet 44×44 targets and hit tests. No drafting/top-toolbar overlap.'},
];
const result={status:'pass-within-stated-production-browser-scope',artifactId:'71f5b012342b',origin:manifest.origin,reviewedAt:new Date().toISOString(),sourceArchiveSha256:transfer.source.sha256,webArchiveSha256:web.archive.sha256,sourceFilesMatchBuiltManifest:true,sourceFiles:manifest.source,checks,logs,files:inspection.files,images,
  visualReview:{rapidPng:true,settledPng:true,allFivePdfPages:true,allSixControlScreenshots:true,modelPartCount:2180,providedLevelCount:33,rapidFrameBefore:8,rapidFrameAfter:8,rapidVsSettledMeanAbsoluteChannelDifference:inspection.rapidVsSettledMeanAbsoluteChannelDifference},
  limitations:['This is a Windows production browser acceptance. Native package and macOS/Linux checks are separate.','The PDF contains illustrative raster model projections with triangulation and occluded lines, not clean section drawings or editable CAD.','The source fixture has 33 supplied levels. This does not claim a newly authored 52-storey multidisciplinary drawing package.','The tablet drafting panel scrolls internally to preserve top and bottom controls; it still covers part of the model while open.'],
  retainedFindings:['Previous build lacked preview bottom navigation. The final build uses the displayable model state.','The initial development fix exposed a tablet top-toolbar overlap. The final build reserves its measured height.','Earlier development attempts hit unavailable port 8080 and a stale browser channel. They did not establish application failures; isolated session recovery preceded passing checks.'],
  downloadProvenance:'The browser saved these exact run-specific filenames to C:/Users/danie/Downloads. Originals remain intact. Copies in this run downloads directory were verified byte-for-byte by SHA-256. Only anchor filenames were prefixed; original click and bytes were unchanged. The wrapper was restored.',
  appSourceEditsDuringQa:false,normalUserDataChanged:false,phoneTesting:false,livePaidProviderCalls:false};
fs.writeFileSync(base+'/acceptance.json',JSON.stringify(result,null,2)+'\n',{flag:'wx'});
const md=`# Final production export and navigation proof\n\n**PASS within the stated browser scope — build 71f5b012342b.**\n\nThe running build badge was checked in both isolated sessions. All six relevant source files match the exact worker source manifest.\n\n${checks.map(c=>`- **${c.name}: ${c.status}.** ${c.evidence}`).join('\n')}\n\nThe control journey ran 66 commands in 5.222 seconds; the export journey ran 30 commands in 3.311 seconds. Both exited successfully with empty runtime error lists. Actual downloaded PNGs and all five PDF pages were inspected, as were the desktop and both tablet scroll states.\n\n## Evidence\n\n- [Self-contained illustrated HTML](acceptance.html)\n- [Machine-readable acceptance and hashes](acceptance.json)\n- [Actual download inspection](download-inspection.json)\n- [Immediate PNG](downloads/${manifest.tag}-01.png)\n- [PDF](downloads/${manifest.tag}-03.pdf)\n\nSource archive: ${result.sourceArchiveSha256}\n\nWeb archive: ${result.webArchiveSha256}\n\n${logs.map(l=>`- ${l.log}: ${l.commands} commands, ${l.seconds.toFixed(3)} seconds, exit ${l.exitCode}.`).join('\n')}\n\n## Scope limits\n\n${result.limitations.map(s=>`- ${s}`).join('\n')}\n\nEarlier missing-navigation and toolbar-overlap screenshots are retained and labelled historical in the HTML. No app source was changed during final QA; no normal user data, phone testing, installation or paid provider calls were involved.\n`;
fs.writeFileSync(base+'/acceptance.md',md,{flag:'wx'});
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Final production model proof — 71f5b012342b</title><style>body{margin:0;background:#edf1f3;color:#182e3a;font:16px/1.6 'Segoe UI',sans-serif}main{max-width:1180px;margin:auto;padding:36px;background:white}h1{font-size:32px;line-height:1.2}.status{border-left:6px solid #28785f;background:#eaf6ef;padding:18px}figure{margin:30px 0;border:1px solid #ccd9df}img{display:block;width:100%;height:auto}figcaption{padding:16px}pre,small{overflow-wrap:anywhere;white-space:pre-wrap;font-size:12px}li{margin-bottom:12px}table{border-collapse:collapse;width:100%}th,td{text-align:left;vertical-align:top;border-bottom:1px solid #d3dfe3;padding:12px}th{background:#edf4f6}</style><main><p>X-RAY · PRODUCTION PROOF · 8 SEPTEMBER 2026</p><h1>Bottom controls restored. Real model exports verified.</h1><p class="status"><strong>Build 71f5b012342b — PASS within the stated Windows browser scope.</strong><br>Original top settings, drafting actions, assistant launcher and bottom navigation remain independently reachable on desktop and both tablet orientations.</p><table><thead><tr><th>Check</th><th>Result and evidence</th></tr></thead><tbody>${checks.map(c=>`<tr><td>${esc(c.name)}</td><td><strong>${c.status}</strong> — ${esc(c.evidence)}</td></tr>`).join('')}</tbody></table><p>The actual immediate PNG contains the complete model without waiting for another animation frame. The downloaded PDF was parsed and every page was rendered and inspected. Both journeys completed with no uncaught runtime errors.</p><h2>Scope limits</h2><ul>${result.limitations.map(s=>`<li>${esc(s)}</li>`).join('')}</ul>${images.map(item=>`<figure><img src="data:image/png;base64,${fs.readFileSync(item.file).toString('base64')}" alt="${esc(item.caption)}"><figcaption>${esc(item.caption)}<br><small>${esc(item.file)} · SHA-256 ${item.sha256}</small></figcaption></figure>`).join('')}<h2>Executed checks and exact identity</h2><pre>${esc(JSON.stringify({...result,images:undefined},null,2))}</pre></main></html>`;
fs.writeFileSync(base+'/acceptance.html',html,{flag:'wx'});
const qa=[['open','file:///C:/Users/danie/repo/xray-by-looplet/'+base+'/acceptance.html'],['set','viewport','1440','1000'],['wait','--fn',"Array.from(document.images).every(i=>i.complete&&i.naturalWidth>0)"],['eval',"(()=>{if(document.images.length!==12)throw Error('Missing embedded images');if(!document.body.textContent.includes('Build 71f5b012342b'))throw Error('Report identity absent');return {title:document.title,embeddedImages:document.images.length};})()"],['screenshot',`screenshots/growth/${manifest.tag}-report-summary.png`],['errors']];
fs.writeFileSync(base+'/report-qa.json',JSON.stringify(qa,null,2),{flag:'wx'});
console.log(JSON.stringify({report:base+'/acceptance.html',embeddedImages:images.length,sourceFilesMatchBuiltManifest:true}));
