import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync, unlinkSync } from 'node:fs';
import { request } from 'node:http';
import { once } from 'node:events';
import { ROOT, readLedger, validate, safePath, hash, inputDigest, render, serve, artifactAllowed, sliceStatus } from './industry-ledger.mjs';
const fresh=()=>structuredClone(readLedger());
const rejects=(mutate,pattern)=>{const d=fresh();mutate(d);const v=validate(d);assert.equal(v.ok,false);assert.match(v.errors.join('\n'),pattern);};
test('canonical inventory preserves 139 features and 359 acceptance rows',()=>{const result=validate(fresh());assert.equal(result.ok,true,JSON.stringify(result));assert.equal(result.counts.features,139);assert.equal(result.counts.acceptance,359);assert.equal(result.counts.verified,1);});
test('missing historical row and stale source text fail',()=>{rejects(d=>d.inventory.features.pop(),/139 unique/);rejects(d=>d.inventory.acceptance[0].text='invented',/stale source row/);});
test('feature cannot be replaced by a real acceptance row with equal counts',()=>rejects(d=>{d.inventory.features[0]=structuredClone(d.inventory.acceptance[0]);},/exact source-derived ID set required/));
test('duplicate manifest path cannot replace a required source with equal counts',()=>rejects(d=>{d.inventory.sources[d.inventory.sources.length-1]=structuredClone(d.inventory.sources[0]);},/each exact source path once/));
test('status misuse and dependency bypass fail',()=>{rejects(d=>d.tasks[0].status='done',/invalid status/);rejects(d=>d.tasks[1].status='ready',/dependency not verified/);rejects(d=>d.tasks[0].status='blocked',/blocked requires reason/);rejects(d=>d.tasks[0].status='intentional-off',/disposition required/);rejects(d=>d.tasks[0].status='superseded',/replacement required/);});
test('cycles fail closed',()=>rejects(d=>{d.tasks[0].dependsOn=['IW-002'];},/Dependency cycle/));
test('missing verified evidence and independent review fail',()=>rejects(d=>{d.tasks[0].status='verified';d.tasks[0].evidence=[];d.tasks[0].review=null;},/missing patch evidence[\s\S]*fresh independent approval/));
test('stale evidence and self-review fail',()=>rejects(d=>{const t=d.tasks[0];t.status='verified';t.inputs=['scripts/industry-ledger.mjs'];t.evidence=[{kind:'patch',path:'scripts/industry-ledger.mjs',sha256:'stale',revision:0,inputDigest:'stale'}];t.review={reviewer:t.owner,decision:'approved'};},/stale evidence[\s\S]*fresh independent approval/));
test('valid attachment structure accepts independent nonvisual verification',()=>{const d=fresh(),t=d.tasks[0];const path='scripts/industry-ledger.mjs';t.visual=false;t.inputs=[path];t.startupHandover=path;t.completionHandover=path;t.status='verified';for(const s of d.slices)s.status=sliceStatus(d.tasks.filter(t=>t.slice===s.id));const digest=inputDigest(t);const sha256=hash(readFileSync(safePath(ROOT,path)));t.evidence=['patch','executed'].map(kind=>({kind,path,sha256,revision:t.revision,inputDigest:digest}));t.review={reviewer:'independent-test-fixture',decision:'approved',reviewedAt:new Date().toISOString(),path,sha256,revision:t.revision,inputDigest:digest};const capture=structuredClone(d.tasks.find(t=>t.id==='IW-004').evidence.find(e=>e.kind==='execution-capture'));capture.revision=t.revision;capture.inputDigest=digest;t.evidence.push(capture);assert.equal(validate(d).ok,true,JSON.stringify(validate(d)));t.review.inputDigest='old';assert.equal(validate(d).ok,false);});
test('malformed task collections fail cleanly rather than crash',()=>{rejects(d=>delete d.tasks[0].scope,/scope/);rejects(d=>delete d.tasks[0].evidence,/evidence/);rejects(d=>delete d.coverage,/Coverage/);});
test('zero-byte independently attributed review cannot verify a task',()=>{const reviewPath='proof/audit/IW-SC01/empty-review-test.txt';writeFileSync(reviewPath,'');try{rejects(d=>{const t=d.tasks[0],path='scripts/industry-ledger.mjs';t.visual=false;t.inputs=[path];t.startupHandover=path;t.completionHandover=path;t.status='verified';const digest=inputDigest(t);t.evidence=['patch','executed'].map(kind=>({kind,path,sha256:hash(readFileSync(path)),revision:t.revision,inputDigest:digest}));t.review={reviewer:'independent-test-fixture',decision:'approved',reviewedAt:new Date().toISOString(),path:reviewPath,sha256:hash(''),revision:t.revision,inputDigest:digest};for(const s of d.slices)s.status=sliceStatus(d.tasks.filter(t=>t.slice===s.id));},/empty, non-file or stale review attachment/);}finally{unlinkSync(reviewPath);}});
test('path traversal and alternate encodings are rejected',()=>{for(const p of ['../package.json','/package.json','C:/secret','planning\\control\\ledger.json','planning/control/../../.env','planning/%2e%2e/.env','planning//control'])assert.throws(()=>safePath(ROOT,p));rejects(d=>d.tasks[0].inputs=['../secret'],/unsafe path/);});
test('artifact allowlist excludes repo source and secrets',()=>{const d=fresh();assert.equal(artifactAllowed('package.json',d),false);assert.equal(artifactAllowed('.env',d),false);assert.equal(artifactAllowed('planning/control/README.md',d),true);d.tasks[0].evidence.push({path:'package.json'});assert.equal(artifactAllowed('package.json',d),false);});
test('HTML escapes ledger strings and avoids localStorage state',()=>{const d=fresh();d.tasks[0].title='<script>alert(1)</script>';const html=render(d);assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('<script>alert'));assert.ok(!readFileSync(safePath(ROOT,'planning/control/dashboard.js'),'utf8').includes('localStorage'));});
test('read-only HTTP server rejects traversal, unknown files, wrong host/origin and writes',async()=>{
 const server=serve(ROOT,0);await once(server,'listening');const port=server.address().port;
 const get=(path,method='GET',headers={})=>new Promise((resolve,reject)=>{const req=request({host:'127.0.0.1',port,path,method,headers},res=>{let body='';res.on('data',x=>body+=x);res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,body}));});req.on('error',reject);req.end();});
 try{assert.equal((await get('/')).status,200);assert.equal((await get('/ledger.json')).status,200);assert.equal((await get('/','POST')).status,405);assert.equal((await get('/','GET',{Host:'evil.test'})).status,403);assert.equal((await get('/','GET',{Origin:'https://evil.test'})).status,403);assert.equal((await get('/artifact?path=..%2Fpackage.json')).status,400);assert.equal((await get('/artifact?path=package.json')).status,404);assert.equal((await get('/.env')).status,404);const file=await get('/artifact?path=planning%2Fcontrol%2FREADME.md');assert.equal(file.status,200);assert.match(file.headers['content-security-policy'],/frame-ancestors 'none'/);assert.equal(file.headers['x-content-type-options'],'nosniff');}finally{await new Promise(r=>server.close(r));}
});
