import fs from 'node:fs';
import path from 'node:path';
import net from 'node:net';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
const expected='14db2b026c8a8aaaf75c54f47be9405db0f5e81a1cb9ee455582d9646bfe72ca';
const exe=path.resolve('proof/growth/2026-09-08-walkthrough-polish/release-38a64f0b8c2b/artifacts/src-tauri/target/release/xray-by-looplet.exe');
const sha256=createHash('sha256').update(fs.readFileSync(exe)).digest('hex');assert.equal(sha256,expected,'Previous verified EXE identity mismatch');
const base=path.resolve('proof/growth/2026-09-08-assistant-mcp-r4/baseline-shutdown-38a64');
const profile=path.resolve('.temp/baseline-shutdown-38a64-'+Date.now());
const output=path.join(base,'launch.json');assert(!fs.existsSync(output),'Preserve prior launch evidence');assert(!fs.existsSync(profile),'Fresh isolated profile required');
const port=9274,probe=net.createServer();probe.listen(port,'127.0.0.1');await once(probe,'listening');await new Promise((resolve,reject)=>probe.close(e=>e?reject(e):resolve()));
fs.mkdirSync(profile,{recursive:true});
const child=spawn(exe,[],{windowsHide:true,detached:true,stdio:'ignore',env:{...process.env,WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS:`--remote-debugging-port=${port} --remote-debugging-address=127.0.0.1`,WEBVIEW2_USER_DATA_FOLDER:profile}});
await once(child,'spawn');child.unref();
const result={runId:'38a64f0b8c2b',pid:child.pid,exe,sha256,profile,cdpPort:port,launchedAt:new Date().toISOString(),installed:false,normalProfileUsed:false,comparisonScope:'Previous verified binary, fresh isolated profile; startup and normal close only.'};
fs.writeFileSync(output,JSON.stringify(result,null,2),{flag:'wx'});console.log(JSON.stringify(result));
fs.writeFileSync(path.join(base,'ready.json'),JSON.stringify([['wait','--fn',"document.querySelector('.workbench')?.dataset.hydrationStatus==='ready'"],['eval',"({title:document.title,tauri:!!window.__TAURI_INTERNALS__,hydration:document.querySelector('.workbench')?.dataset.hydrationStatus})"],['screenshot','screenshots/growth/2026-09-08-shutdown-baseline-38a64-ready.png'],['errors']],null,2),{flag:'wx'});
