import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {spawn} from 'node:child_process';
const arg=process.argv[2]||'http://127.0.0.1:8080',native=arg.endsWith('.exe'),mode=native?(arg.includes('AppData')?'installed':'native'):(arg.includes('8081')?'built':'dev'),dir=path.resolve('screenshots/connection-count',mode);fs.mkdirSync(dir,{recursive:true});let app,browser;
if(native){app=spawn(path.resolve(arg),[],{windowsHide:true,stdio:'ignore',env:{...process.env,WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS:'--remote-debugging-port=9238',WEBVIEW2_USER_DATA_FOLDER:path.resolve('proof/audit/IW-CONNECTION-COUNT/profile-'+Date.now())}});for(let i=0;i<90;i++){try{browser=await chromium.connectOverCDP('http://127.0.0.1:9238');break;}catch{await new Promise(r=>setTimeout(r,500));}}}else browser=await chromium.launch({headless:true,channel:'msedge'});
const page=native?browser.contexts()[0].pages()[0]:await browser.newPage({viewport:{width:1600,height:1100},acceptDownloads:true});page.setDefaultTimeout(60000);const report={ok:false,checks:[],errors:[],...(native?{sha256:crypto.createHash('sha256').update(fs.readFileSync(arg)).digest('hex')}:{})};page.on('pageerror',e=>report.errors.push(String(e)));page.on('console',e=>{if(e.type()==='error')report.errors.push(e.text())});const b=n=>page.getByRole('button',{name:n,exact:true}),check=async(n,f)=>{await f();report.checks.push(n);console.log('PASS '+n);},shot=n=>page.screenshot({path:path.join(dir,n+'.png')});
try{
if(!native)await page.goto(arg,{waitUntil:"domcontentloaded"});await page.locator('[data-hydration-status=ready]').waitFor();await b('Components').click();
await check('Open verified official PDF and trace sixteen physical ends',async()=>{await b('Open structural bolt-count trial').click();await page.getByRole('heading',{name:'Follow every bolt to the drawing'}).waitFor();assert.equal(await page.locator('.connection-beam-grid button').count(),16);assert.equal(await page.locator('.connection-marker').count(),16);await page.locator('.connection-image img').evaluate(im=>im.decode());assert.match(await page.locator('.takeoff-summary').innerText(),/32/);await shot('01-count-overview');});
await check('Connection selection, review save and JSON physical count export',async()=>{await b('Beam I3 · S').click();await page.getByRole('heading',{name:'Beam I3 · south end'}).waitFor();await page.getByLabel('Review note',{exact:true}).fill('Checked S2.2 beam end, S5.1 detail 1 and S0.6 D=10 schedule.');assert.equal(await b('Export connection count').isDisabled(),true);await page.getByRole('checkbox').check();await b('Save connection review').click();await page.getByText('Review saved to this project. It will survive reload.',{exact:true}).waitFor();assert.match(await page.locator('.takeoff-summary').innerText(),/1 \/ 16/);
{if(native){const cdp=await page.context().newCDPSession(page);await cdp.send('Page.setDownloadBehavior',{behavior:'allow',downloadPath:dir});}const pending=page.waitForEvent('download');await b('Export connection count').click();const download=await pending,target=path.join(dir,'export.json');if(native){assert.equal(await download.failure(),null);assert.equal(download.suggestedFilename(),'thornton-roof-connection-count.json');fs.copyFileSync(path.join(dir,download.suggestedFilename()),target);}else await download.saveAs(target);const value=JSON.parse(fs.readFileSync(target));assert.equal(value.boltCount,32);assert.equal(value.connectionCount,16);assert.equal(value.nuts,null);assert.equal(value.packedVolumeM3,null);assert.equal(new Set(value.bolts.map(b=>b.stableIdentifier)).size,32);assert.equal(value.reviews.filter(r=>r.reviewed).length,1);}
await shot('02-reviewed');});
await check('Review persists through page reload',async()=>{await page.reload({waitUntil:"domcontentloaded"});await page.locator('[data-hydration-status=ready]').waitFor();await b('Components').click();await page.getByRole('heading',{name:'Follow every bolt to the drawing'}).waitFor();await b('Beam I3 · S ✓').click();await page.waitForFunction(()=>document.querySelector('.connection-trial input[type=checkbox]')?.checked);assert.equal(await page.getByRole('checkbox').isChecked(),true);assert.match(await page.getByLabel('Review note',{exact:true}).inputValue(),/Checked S2.2/);});
await check('Evidence gallery displays actual schedule and navigates original page',async()=>{await b('Bolted connection schedule').click();await page.getByRole('img',{name:'S0.6: Bolted connection schedule',exact:true}).evaluate(im=>im.decode());await shot('03-schedule');await b('Open full source sheet').click();await page.locator('.document-preview[data-source-ready=true]').waitFor();assert.equal(await page.locator('.document-preview-page').innerText(),'Page 6');await shot('04-original-sheet');await b('Components').click();await b('Wide-flange beam to beam').click();await page.getByRole('img',{name:'S5.1 · detail 1: Wide-flange beam to beam',exact:true}).evaluate(im=>im.decode());await shot('05-detail');});
await check('Unreadable restore preserves saved bytes and disables ordinary edits and export',async()=>{const keys=await page.evaluate(()=>Object.keys(localStorage).filter(k=>k.startsWith('xray:connection-trial:')));assert.equal(keys.length,1);const raw=await page.evaluate(k=>localStorage.getItem(k),keys[0]);await page.evaluate(k=>localStorage.setItem(k,'{"schema":"future-version","valuable":"preserve"}'),keys[0]);await page.reload({waitUntil:"domcontentloaded"});await page.locator('[data-hydration-status=ready]').waitFor();await b('Components').click();await page.getByRole('alert').filter({hasText:'Original data is preserved'}).waitFor();assert.equal(await b('Save connection review').isDisabled(),true);assert.equal(await b('Export connection count').isDisabled(),true);await b('Beam I2 · N').click();assert.equal(await page.evaluate(k=>localStorage.getItem(k),keys[0]),'{"schema":"future-version","valuable":"preserve"}');await shot('06-recovery-block');await page.evaluate(({k,raw})=>localStorage.setItem(k,raw),{k:keys[0],raw});await b('Retry restore').click();assert.equal(await b('Export connection count').isDisabled(),false);});
await check(native?'Native window has no page overflow':'Mobile count and inspector remain usable without page overflow',async()=>{if(!native)await page.setViewportSize({width:390,height:844});await b('Physical beam locations').click();await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await shot('07-mobile');});
assert.deepEqual(report.errors,[]);report.ok=true;
}catch(e){report.failure=String(e.stack);process.exitCode=1;await shot('failure');}finally{fs.writeFileSync(path.join(dir,'report.json'),JSON.stringify(report,null,2));if(native)fs.writeFileSync('proof/audit/IW-CONNECTION-COUNT/'+mode+'-qa.json',JSON.stringify(report,null,2));await browser?.close();app?.kill();console.log(JSON.stringify(report));}
