/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiArchitectAiRouteImport } from './routes/api.architect-ai'
import { Route as ApiAssistantAiRouteImport } from './routes/api.assistant-ai'
import { Route as ApiMaterialAiRouteImport } from './routes/api.material-ai'
import { Route as ApiVoiceRouteImport } from './routes/api.voice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArchitectAiRoute = ApiArchitectAiRouteImport.update({
  id: '/api/architect-ai',
  path: '/api/architect-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantAiRoute = ApiAssistantAiRouteImport.update({
  id: '/api/assistant-ai',
  path: '/api/assistant-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMaterialAiRoute = ApiMaterialAiRouteImport.update({
  id: '/api/material-ai',
  path: '/api/material-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceRoute = ApiVoiceRouteImport.update({
  id: '/api/voice',
  path: '/api/voice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/architect-ai': typeof ApiArchitectAiRoute
  '/api/assistant-ai': typeof ApiAssistantAiRoute
  '/api/material-ai': typeof ApiMaterialAiRoute
  '/api/voice': typeof ApiVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/architect-ai': typeof ApiArchitectAiRoute
  '/api/assistant-ai': typeof ApiAssistantAiRoute
  '/api/material-ai': typeof ApiMaterialAiRoute
  '/api/voice': typeof ApiVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/architect-ai': typeof ApiArchitectAiRoute
  '/api/assistant-ai': typeof ApiAssistantAiRoute
  '/api/material-ai': typeof ApiMaterialAiRoute
  '/api/voice': typeof ApiVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/architect-ai'
    | '/api/assistant-ai'
    | '/api/material-ai'
    | '/api/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/architect-ai'
    | '/api/assistant-ai'
    | '/api/material-ai'
    | '/api/voice'
  id:
    | '__root__'
    | '/'
    | '/api/architect-ai'
    | '/api/assistant-ai'
    | '/api/material-ai'
    | '/api/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiArchitectAiRoute: typeof ApiArchitectAiRoute
  ApiAssistantAiRoute: typeof ApiAssistantAiRoute
  ApiMaterialAiRoute: typeof ApiMaterialAiRoute
  ApiVoiceRoute: typeof ApiVoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/architect-ai': {
      id: '/api/architect-ai'
      path: '/api/architect-ai'
      fullPath: '/api/architect-ai'
      preLoaderRoute: typeof ApiArchitectAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant-ai': {
      id: '/api/assistant-ai'
      path: '/api/assistant-ai'
      fullPath: '/api/assistant-ai'
      preLoaderRoute: typeof ApiAssistantAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/material-ai': {
      id: '/api/material-ai'
      path: '/api/material-ai'
      fullPath: '/api/material-ai'
      preLoaderRoute: typeof ApiMaterialAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice': {
      id: '/api/voice'
      path: '/api/voice'
      fullPath: '/api/voice'
      preLoaderRoute: typeof ApiVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiArchitectAiRoute: ApiArchitectAiRoute,
  ApiAssistantAiRoute: ApiAssistantAiRoute,
  ApiMaterialAiRoute: ApiMaterialAiRoute,
  ApiVoiceRoute: ApiVoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
