import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawn} from 'node:child_process';
const arg=process.argv[2]||'http://127.0.0.1:8080',native=arg.endsWith('.exe'),mode=native?(arg.includes('AppData')?'installed':'native'):(arg.includes('8081')?'built':'dev'),dir=path.resolve('screenshots/ai-materials',mode);fs.mkdirSync(dir,{recursive:true});let app,browser;
if(native){app=spawn(path.resolve(arg),[],{windowsHide:true,stdio:'ignore',env:{...process.env,WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS:'--remote-debugging-port=9238',WEBVIEW2_USER_DATA_FOLDER:path.resolve('proof/audit/IW-AI-MATERIALS/profile-'+Date.now())}});for(let i=0;i<90;i++){try{browser=await chromium.connectOverCDP('http://127.0.0.1:9238');break;}catch{await new Promise(r=>setTimeout(r,500));}}}else browser=await chromium.launch({headless:true,channel:'msedge'});
const page=native?browser.contexts()[0].pages()[0]:await browser.newPage({viewport:{width:1600,height:1100},acceptDownloads:true});page.setDefaultTimeout(60000);
const report={nativeScope:native?'Real native configuration IPC; imported recorded fixtures for UI/persistence. Live native interpretation unverified without a provider key.':null,ok:false,method:'Automated Playwright UI checks with explicitly labeled deterministic AI fixtures. Real PDF rendering and source hashes; NO live provider or measured plan accuracy.',checks:[],errors:[],requests:[],...(native?{sha256:crypto.createHash('sha256').update(fs.readFileSync(arg)).digest('hex')}:{})};page.on('pageerror',e=>report.errors.push(String(e)));page.on('console',e=>{if(e.type()==='error')report.errors.push(e.text())});const b=n=>page.getByRole('button',{name:n,exact:true}),check=async(n,f)=>{await f();report.checks.push(n);console.log('PASS '+n);},shot=n=>page.screenshot({path:path.join(dir,n+'.png')}),openPanel=async()=>{await page.locator('[data-hydration-status=ready]').waitFor();await b('Components').click();await b('Project material takeoff').click();await page.getByRole('heading',{name:'Every material. Every source.',exact:true}).waitFor();};
async function inventory(){return await page.evaluate(async()=>{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('xray-project-materials-v1',1);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return await new Promise((resolve,reject)=>{const r=db.transaction('inventories').objectStore('inventories').getAll();r.onsuccess=()=>{db.close();resolve(r.result.map(x=>{try{return JSON.parse(x)}catch{return x}}).sort((a,b)=>(b.aiRuns?.length||0)-(a.aiRuns?.length||0)))};r.onerror=()=>reject(r.error)});});}
async function exported(button,name){if(native){const cdp=await page.context().newCDPSession(page);await cdp.send('Page.setDownloadBehavior',{behavior:'allow',downloadPath:dir});}const wait=page.waitForEvent('download');await b(button).click();const d=await wait,target=path.join(dir,name);if(native){assert.equal(await d.failure(),null);fs.copyFileSync(path.join(dir,d.suggestedFilename()),target);}else await d.saveAs(target);return fs.readFileSync(target,'utf8');}
const fixture=JSON.parse(fs.readFileSync('proof/audit/IW-AI-MATERIALS/fixture-result.json','utf8'));let behavior='valid',release;
const fixtureStatus={provider:'Gemini',model:'QA-fixture-not-live',available:true,configured:true,message:'TEST FIXTURE: deterministic UI adapter, no live AI provider.'};
async function fixtureReply(raw){const request=JSON.parse(raw);assert.equal(request.images.length,5);for(const i of request.images){const data=Buffer.from(i.jpegBase64,'base64');assert.equal(data[0],255);assert.equal(data[1],216);assert.equal(crypto.createHash('sha256').update(data).digest('hex'),i.sha256);assert.ok(i.box.x+i.box.width<=1);}assert.equal(request.sourceSha256,'28fe1e51d38cbb1347e5875870b60bcd4ed9a9a0b9dc66e1bf5a611ce3f693f6');report.requests.push({id:request.requestId,page:request.page,imageCount:request.images.length,bytes:raw.length,imageHashes:request.images.map(i=>i.sha256),behavior});
if(behavior==='delayed')await new Promise(r=>release=r);
return {schema:'xray.ai-materials/v1',id:request.requestId,sourceSha256:behavior==='wrong-source'?'f'.repeat(64):request.sourceSha256,page:request.page,inventoryRevision:request.inventoryRevision,provider:'QA fixture',model:'NOT LIVE AI',createdAt:new Date().toISOString(),requestDigest:crypto.createHash('sha256').update(raw).digest('hex'),imageHashes:request.images.map(i=>i.sha256),result:fixture,decisions:[]};}
async function enableFixtures(){if(native)return;await page.route('**/api/material-ai',async route=>{if(route.request().method()==='GET')return route.fulfill({json:fixtureStatus});const run=await fixtureReply(route.request().postData());await route.fulfill({json:{run}}).catch(()=>{});});}
try{
if(!native)await page.goto(arg,{waitUntil:'domcontentloaded'});await openPanel();
await check('Unconfigured provider is truthful and cannot send drawings',async()=>{await b('AI review').click();await page.getByText('AI not connected',{exact:true}).waitFor();assert.equal(await b('Send selected sheet to Gemini').isDisabled(),true);await shot('01-not-connected');});
if(native)await check('Native session key configuration and disconnect use real IPC without persisting credentials',async()=>{await b('Connection').click();await page.getByLabel('Gemini API key',{exact:true}).fill('qa-session-key-not-a-real-credential');await b('Use for this session').click();await page.getByText('Gemini configured',{exact:true}).waitFor();assert.equal(JSON.stringify(await inventory()).includes('qa-session-key-not-a-real-credential'),false);await b('Connection').click();assert.equal(await page.getByLabel('Gemini API key',{exact:true}).inputValue(),'');await b('Disconnect').click();await page.getByText('AI not connected',{exact:true}).waitFor();});
await enableFixtures();await b('Materials').click();await page.getByText('Public project library · Thornton Fire Station 8 · 1,260 pages',{exact:true}).click();await b('Open structural source').click();await b('Scan all source sheets').waitFor();await b('AI review').click();
if(native)await check('Recorded fixture backup imports the review queue without counting materials',async()=>{const backup=JSON.parse(fs.readFileSync('screenshots/ai-materials/dev/ai-backup.json','utf8'));backup.inventory.projectId=(await inventory())[0].projectId;backup.inventory.materials=[];backup.inventory.aiRuns[0].decisions=[];const file=path.join(dir,'imported-fixture.json');fs.writeFileSync(file,JSON.stringify(backup));await page.locator('.material-import input').setInputFiles(file);await page.getByRole('checkbox',{name:'I have reviewed this backup and want to replace this material register',exact:true}).check();await b('Restore reviewed backup').click();await page.getByText('Backup restored. Previous raw inventory archived atomically for recovery.',{exact:true}).waitFor();await page.locator('[data-ai-proposal="0"]').waitFor();assert.equal((await inventory()).find(v=>v.aiRuns?.length).materials.length,0);await shot('02-proposal-queue');});
if(!native)await check('Actual PDF renders five hashed image views; fixture proposals save separately from stock',async()=>{await b('Send selected sheet to Gemini').click();await page.getByText('2 AI proposals saved for review. No quantities were approved automatically.',{exact:true}).waitFor();const v=(await inventory())[0];assert.equal(v.aiRuns.length,1);assert.equal(v.materials.length,0);assert.equal(v.aiRuns[0].imageHashes.length,5);await page.locator('.material-ai-heading').first().scrollIntoViewIfNeeded();await shot('02-proposal-queue');});
await check('Evidence modal renders the matching source with a thin correctly bounded overlay',async()=>{await page.locator('[data-ai-proposal="0"]').getByRole('button',{name:'View drawing region'}).click();await page.locator('.project-material-preview[data-source-ready=true]').waitFor();const box=page.locator('[data-ai-evidence-region]');await box.waitFor();const rect=await box.boundingBox();assert.ok(rect.width>10&&rect.height>3);const border=await box.evaluate(e=>parseFloat(getComputedStyle(e).borderTopWidth));assert.ok(border>0&&border<=1);await shot('03-evidence-region');await b('Close source preview').click();});
await check('Proposal becomes a pending physical material only after the review form is saved',async()=>{await page.locator('[data-ai-proposal="0"]').getByRole('button',{name:'Review material draft'}).click();assert.equal(await page.getByLabel('Quantity',{exact:true}).inputValue(),'2');assert.equal(await page.getByLabel('Quantity and source checked',{exact:true}).isChecked(),false);await b('Save physical material').click();await page.waitForFunction(()=>!document.querySelector('button')||![...document.querySelectorAll('button')].some(b=>b.textContent.trim()==='Save physical material'));const v=(await inventory())[0];assert.equal(v.materials.length,1);assert.equal(v.materials[0].review,'pending');assert.equal(v.aiRuns[0].decisions[0].action,'material');await b('AI review').click();});
await check('Linking another proposal preserves quantity and records the reason',async()=>{const v=(await inventory())[0];await page.getByLabel('Decision reason',{exact:true}).fill('QA fixture: same physical material, no additional units');await page.getByLabel('Existing physical material',{exact:true}).selectOption(v.materials[0].stock.id);await page.locator('[data-ai-proposal="1"]').getByRole('button',{name:'Link evidence'}).click();await page.getByText('Evidence linked. Existing quantity preserved.',{exact:true}).waitFor();assert.equal((await inventory())[0].materials[0].stock.quantity,2);});
await check('Benchmark scores actual saved fixture predictions, penalizing unresolved quantity',async()=>{await page.getByText('Measure this run against checked quantities',{exact:true}).click();const truth=[{key:'QA-D01',quantity:2,unit:'each'},{key:'QA-D02',quantity:1,unit:'each'}];await page.getByLabel('AI benchmark ground truth').setInputFiles({name:'QA-fixture-truth.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(truth))});await page.locator('[data-ai-benchmark]').waitFor();assert.match(await page.locator('[data-ai-benchmark]').innerText(),/50.0%/);const proof=JSON.parse(await exported('Download benchmark evidence','fixture-benchmark.json'));assert.equal(proof.score.exactQuantityRecall,.5);assert.equal(proof.run.provider,'QA fixture');await shot('04-benchmark-fixture');});
await check('Backup download preserves AI provenance and decisions across reload',async()=>{const backup=JSON.parse(await exported('Backup & report','ai-backup.json'));assert.equal(backup.inventory.aiRuns[0].decisions.length,2);await page.reload({waitUntil:'domcontentloaded'});await openPanel();await b('AI review').click();await page.locator('[data-ai-proposal="0"]').waitFor();const v=(await inventory())[0];assert.equal(v.aiRuns.length,1);assert.equal(v.materials[0].stock.quantity,2);});
// Reopen the original registered binary after a reload, then restore fixture transport.
if(native)await enableFixtures();await b('Materials').click();await page.getByText('Public project library · Thornton Fire Station 8 · 1,260 pages',{exact:true}).click();await b('Open structural source').click();await b('Scan all source sheets').waitFor();await b('AI review').click();
if(!native)await check('Wrong source response is rejected without changing saved inventory',async()=>{behavior='wrong-source';await b('Send selected sheet to Gemini').click();await page.getByText('AI response does not match the requested drawing page.',{exact:true}).waitFor();assert.equal((await inventory())[0].aiRuns.length,1);});
if(!native)await check('Cancellation discards a late fixture response and preserves inventory',async()=>{behavior='delayed';const before=report.requests.length;await b('Send selected sheet to Gemini').click();while(report.requests.length===before)await new Promise(r=>setTimeout(r,100));await b('Cancel').click();release();await page.getByText('AI interpretation cancelled. Saved inventory preserved.',{exact:true}).waitFor();assert.equal((await inventory())[0].aiRuns.length,1);behavior='valid';});
await check('Backup restore retains the AI queue with its physical-material links',async()=>{await page.locator('.material-import input').setInputFiles(path.join(dir,'ai-backup.json'));await page.getByRole('checkbox',{name:'I have reviewed this backup and want to replace this material register',exact:true}).check();await b('Restore reviewed backup').click();await page.getByText('Backup restored. Previous raw inventory archived atomically for recovery.',{exact:true}).waitFor();const v=(await inventory()).find(x=>x.materials?.length===1);assert.equal(v.aiRuns[0].decisions.length,2);});
await check(native?'Native AI review fits the app viewport':'Mobile AI review fits without horizontal overflow',async()=>{if(!native)await page.setViewportSize({width:390,height:844});await b('AI review').click();await page.locator('.material-ai-heading').first().scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await shot('05-mobile');});
await check('AI tools replaces canned chat results and does not claim an MCP connection',async()=>{await b('Render').click();await b('AI drawing tools').click();const dialog=page.getByRole('dialog');await dialog.getByText('Conversational tool control',{exact:false}).waitFor();assert.equal((await dialog.innerText()).includes('FastMCP connected'),false);assert.equal((await dialog.innerText()).includes('\uFFFD'),false);await dialog.getByText('Conversational tool control (planned)',{exact:true}).waitFor();await shot('06-ai-tools');await b('Close AI tools').click();});
assert.deepEqual(report.errors,[]);report.ok=true;
}catch(e){report.failure=String(e.stack);report.failureText=await page.locator('body').innerText().catch(()=>null);process.exitCode=1;await shot('failure').catch(()=>{});}finally{release?.();fs.writeFileSync(path.join(dir,'report.json'),JSON.stringify(report,null,2));fs.writeFileSync('proof/audit/IW-AI-MATERIALS/'+mode+'-qa.json',JSON.stringify(report,null,2));await browser?.close();app?.kill();console.log(JSON.stringify(report));}
