import {readFileSync,writeFileSync,existsSync,readdirSync,statSync} from 'node:fs';
import {createHash} from 'node:crypto';
const base='proof/audit/IW-UI-AUDIT/',read=n=>JSON.parse(readFileSync(base+n+'.json'));
const report={at:new Date().toISOString(),sourceFiles:read('remaining03').sourceFiles,cases:[],captures:[],limits:['Desktop browser only, no host injection and no mobile tests. Case pass is not whole-feature verification.','takeoff02.json was inadvertently overwritten by a copied harness finalizer. Use preserved batch02.json for original takeoff02 cases, and specifically named remaining/edit/industry-gap reports for later executions.','Expected browser desktop-engine boundary is blocked-host, not a failed quantity calculation. No downstream quote failure is inferred from an empty Cost screen.']};
function add(run,names,overrides={}){const x=read(run);for(const c of x.cases.filter(c=>names.includes(c.name))){const d={...c,...overrides[c.name],evidence:base+run+'.json',scope:'Only the named normal UI scenario. Not blanket feature approval.'};delete d.body;report.cases.push(d);const capture=x.captures.find(s=>s.path===c.screenshot);if(capture)report.captures.push({...capture,verdict:d.status});}}
add('remaining03',['run-specification','review-attributed-ready','recipe-assumption-acceptance','desktop-engine-boundary','recipe-reopen-after-reload'],{'review-attributed-ready':{ids:['TAKE-003','TAKE-005'],scope:'Attributed run review removes evidence blockers; not commercial quote readiness.'},'recipe-assumption-acceptance':{ids:['TAKE-004'],scope:'Four project assumptions accepted; does not test quote summary or pricing.'},'desktop-engine-boundary':{ids:['QUOTE-001','DATA-002'],status:'blocked-host'}});
add('remaining02',['camera-pan-zoom-reset','escape-m-numeric-shortcuts','missing-lifecycle-site-controls','no-fabricated-commercial-output','web-engine-result-boundary'],{'missing-lifecycle-site-controls':{status:'not-implemented-ui'},'no-fabricated-commercial-output':{status:'removed-or-unavailable'},'web-engine-result-boundary':{status:'blocked-host'}});
add('edit02',['split-merge-run','snap-to-manual-endpoint']);
add('edit01',['photo-order-links','photo-order-links-reload','vertex-drag-and-undo'],{'vertex-drag-and-undo':{ids:['TRACE-016'],status:'fail',details:'One pointer drag generated multiple history entries: length 19.20m -> 18.20m, one Undo only restored 18.36m. Subsequent edit01 split/snap failures were dependent harness expectations, superseded by isolated edit02.'}});
add('resize02',['landmark-before-list-resize','landmark-after-area-list-resize']);
add('industry-gap01',['arbitrary-count-unavailable','neutral-runtime-ui-unintegrated'],{'arbitrary-count-unavailable':{ids:['TRACE-003'],status:'not-implemented-universal-count'},'neutral-runtime-ui-unintegrated':{ids:['DATA-002','TAKE-001'],status:'module-only-unintegrated'}});
const formats=read('formats-built-audit01');report.cases.push({ids:['UI-006','UI-007','TRACE-001','TRACE-007'],name:'pdf-crop-rotation-page-return-dxf-unavailable',status:'pass',details:formats.scenarios,evidence:base+'formats-built-audit01.json',scope:'Named actual source import, page, calibration and unavailable scenarios only.'});report.captures.push(...formats.captures);
const hash=p=>({path:p,bytes:statSync(p).size,sha256:createHash('sha256').update(readFileSync(p)).digest('hex')});
const scripts=readdirSync('scripts').filter(n=>/verify|audit|sweep|autopilot/.test(n));
const legacy={at:report.at,removedEntries:['index.html','src/main.tsx'].map(path=>({path,exists:existsSync(path)})),historicalScripts:scripts.map(n=>hash('scripts/'+n)),note:'Read-only inventory. Historical verifiers were not executed; they cannot certify current UI. Historical mindmap/ledger truth reconciliation belongs to canonical writer.'};writeFileSync(base+'legacy-surface-snapshot.json',JSON.stringify(legacy,null,2));
report.cases.push({ids:['LEG-007'],name:'historical-verifiers-preserved-untrusted',status:'superseded',evidence:base+'legacy-surface-snapshot.json',details:'Files exist; not executed. Current fresh browser harnesses replace their UI claims.'},{ids:['LEG-008'],name:'historical-ledger-reconciliation',status:'pending-writer-review',evidence:'planning/control/ledger.json',details:'Canonical writer owns reconciliation, old completion labels are not proof.'},{ids:['LEG-009'],name:'duplicate-spa-entry-absence',status:'removed',evidence:base+'legacy-surface-snapshot.json',details:'Neither index.html nor src/main.tsx exists; current built TanStack UI exercised in browser.'});
report.artifacts=[...new Set(report.cases.map(c=>c.evidence).filter(p=>p&&p!== 'planning/control/ledger.json').concat(report.captures.map(c=>c.path)))].map(hash);
writeFileSync(base+'batch03.json',JSON.stringify(report,null,2));console.log(JSON.stringify({cases:report.cases.length,captures:report.captures.length,missingArtifacts:report.artifacts.filter(x=>!x.bytes).length}));
