import{chromium}from'playwright';import{mkdirSync,writeFileSync,readFileSync}from'node:fs';import{resolve}from'node:path';
const url='http://127.0.0.1:8081/',viewport={width:1440,height:960},out='screenshots/industry-ui-audit/edit01';mkdirSync(out,{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport,acceptDownloads:true});page.setDefaultTimeout(4000);const report={url,viewport,at:new Date().toISOString(),injection:false,sourceFiles:JSON.parse(readFileSync('proof/audit/IW005/source-files-v2.json')),cases:[],captures:[],errors:[]};page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});const check=(v,m)=>{if(!v)throw Error(m);},click=name=>page.getByRole('button',{name,exact:true}).first().click();
const shot=async(name,verdict)=>{const path=`${out}/${String(report.captures.length+1).padStart(2,'0')}-${name}.png`;await page.screenshot({path,fullPage:true});report.captures.push({path,url,viewport,capturedAt:new Date().toISOString(),scenario:name,verdict});return path;};const test=async(ids,name,fn)=>{const c={ids,name,status:'pass',at:new Date().toISOString()};try{c.details=await fn();}catch(e){c.status='fail';c.error=String(e);}c.screenshot=await shot(name,c.status);c.body=await page.locator('body').innerText();report.cases.push(c);writeFileSync('proof/audit/IW-UI-AUDIT/edit01.json',JSON.stringify(report,null,2));};
const open=async file=>{const e=page.waitForEvent('filechooser');await click('Open plan');await(await e).setFiles(file);};const exportJob=async name=>{await click('Proof');const e=page.waitForEvent('download');await click('Export current manifest');const d=await e,p=`proof/audit/IW-UI-AUDIT/${name}-manifest.json`;await d.saveAs(p);return JSON.parse(readFileSync(p));};const measure=async()=>{await click('Measure');await page.locator('.measure-document-preview[data-source-ready="true"]').waitFor();};const canvas=page.locator('.measure-document-preview canvas'),source=page.locator('.measure-document-preview img');const point=async(x,y)=>{const b=await source.boundingBox(),c=await canvas.boundingBox();return{x:b.x+x/12000*b.width-c.x,y:b.y+y/8000*b.height-c.y};};const mark=async(x,y)=>{await canvas.scrollIntoViewIfNeeded();await canvas.click({position:await point(x,y)});};
try{await page.goto(url);await page.locator('[data-hydration-status="ready"]').waitFor();
await test(['UI-007'],'invalid-plan-import',async()=>{await open({name:'invalid.pdf',mimeType:'application/pdf',buffer:Buffer.from('not a PDF')});await page.getByRole('alert').first().waitFor();return await page.getByRole('alert').first().innerText();});
await test(['UI-006','SITE-001','TRACE-001'],'source-import-svg',async()=>{await open(resolve('engine/fixtures/svg/sample-plan.svg'));await page.locator('.document-preview[data-source-ready="true"]').waitFor();check(await page.locator('.document-preview img').count()===1,'Actual source image missing');return{source:'engine/fixtures/svg/sample-plan.svg',hash:await page.locator('.document-preview-hash').first().innerText()};});await measure();await page.getByTitle('Zoom Out',{exact:true}).click();
await test(['TRACE-007'],'calibration-zero-negative',async()=>{await page.getByLabel('Known distance',{exact:true}).fill('0');check(await page.getByRole('button',{name:'Pick two points',exact:true}).isDisabled(),'Zero distance allowed capture');return'Zero distance blocked';});
await test(['TRACE-007'],'calibrate-mm',async()=>{await page.getByLabel('Known distance',{exact:true}).fill('11600');await page.locator('.calibration-distance-row select').selectOption('mm');await click('Pick two points');await mark(200,200);await mark(11800,200);await click('Lock scale');await page.getByText('Scale is locked for measurements on this sheet.',{exact:true}).waitFor();return'Known11600mm actualsource landmarks locked';});
await test(['TRACE-002','TRACE-011','TRACE-014','TAKE-001'],'polyline-keyboard-commit',async()=>{await page.locator('body').click({position:{x:170,y:70}});await page.keyboard.press('l');await mark(200,200);await mark(11800,200);await mark(11800,7800);await page.keyboard.press('Enter');await page.getByText('19.20 m',{exact:false}).first().waitFor();return'Three actualsource points; Enter commits19.20m';});

await test(['TRACE-002','TRACE-015'],'vertex-drag-and-undo',async()=>{await click('Move vertex');const a=await point(11800,7800),b=await point(11800,6800),box=await canvas.boundingBox();await page.mouse.move(box.x+a.x,box.y+a.y);await page.mouse.down();await page.mouse.move(box.x+b.x,box.y+b.y,{steps:6});await page.mouse.up();await page.getByText('18.20 m',{exact:false}).first().waitFor();await page.getByRole('button',{name:'Undo last trace edit',exact:true}).click();await page.getByText('19.20 m',{exact:false}).first().waitFor();return'Actualpointerdragchangedlengthandundorestored';});
await test(['TRACE-002','TRACE-015'],'split-merge-run',async()=>{await page.locator('.trace-vertex-editor select').selectOption('1');await click('Split here');const options=await page.locator('.trace-merge-editor select').first().locator('option').evaluateAll(es=>es.filter(e=>e.value).map(e=>e.value));check(options.length===1,'Splitdidnotproduce2runs');await page.locator('.trace-merge-editor select').first().selectOption(options[0]);await click('Merge selected endpoints');await page.getByText('19.20 m',{exact:false}).first().waitFor();const m=await exportJob('edit01-merged');check(m.job.runs.length===1,'Mergedidnotproduceonecanonicalrun');await measure();return{runs:m.job.runs.length,length:m.job.runs[0].lengthM};});
await test(['TRACE-009','TRACE-010'],'snap-to-manual-endpoint',async()=>{await page.getByRole('button',{name:/^Run L$/}).click();await mark(11500,7800);await mark(8000,7800);await page.keyboard.press('Enter');const m=await exportJob('edit01-snap');check(m.job.runs.length===2,'Snapjourneydidnotcommitsecondrun');const first=m.job.runs[0].points.at(-1),next=m.job.runs[1].points[0];check(Math.hypot(first.x-next.x,first.y-next.y)<.001,'Newrunfirstpointdidnotsnapexistingendpoint');await measure();return{existingEndpoint:first,newStart:next,length:m.job.runs[1].lengthM};});
await click('Proof');await test(['SITE-004','TAKE-002'],'photo-order-links',async()=>{await page.locator('input[type=file][accept*=image]').setInputFiles([resolve('screenshots/industry-ui-audit/navigation01/03-sheets.png'),resolve('screenshots/industry-ui-audit/navigation01/09-review.png')]);await page.getByRole('button',{name:'Move 03-sheets.png later',exact:true}).waitFor();await page.getByRole('button',{name:'Move 03-sheets.png later',exact:true}).click();const cards=page.locator('.photo-evidence-card');const names=await page.getByRole('button',{name:/Move .* earlier/}).allTextContents();const checkbox=page.locator('input[type=checkbox]').first();await checkbox.check();const m=await exportJob('edit01-photo-links');check(m.job.photos.length===2,'Twooriginalsnotretained');check(m.job.photos.some(p=>p.runIds.length>0),'Photolinknotrecorded');return{photoOrder:m.job.photos.map(p=>({name:p.name,order:p.order,runIds:p.runIds})),names};});
await test(['SITE-004','DATA-001'],'photo-order-links-reload',async()=>{const before=await exportJob('edit01-photos-before-reload');await page.reload();await page.locator('[data-hydration-status="ready"]').waitFor();const after=await exportJob('edit01-photos-after-reload');check(JSON.stringify(before.job.photos)===JSON.stringify(after.job.photos),'Photorecordschangedonreload');return'Twooriginals,order,reciprocallinksretained';});
}catch(e){report.fatal=String(e);}finally{report.finishedAt=new Date().toISOString();await browser.close();writeFileSync('proof/audit/IW-UI-AUDIT/takeoff02.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report.cases.map(({ids,name,status,error})=>({ids,name,status,error}))));}
