import {chromium} from 'playwright';import {mkdirSync,writeFileSync} from 'node:fs';import {resolve} from 'node:path';
const built=process.argv.includes('--built'),run=process.argv.find(a=>a.startsWith('--run='))?.slice(6)||'attempt01';if(!/^[a-z0-9-]+$/.test(run))throw Error('Invalid run');
const url=`http://127.0.0.1:${built?8081:8080}/`,out=`screenshots/industry-ui-audit/formats/${built?'built':'dev'}/${run}`;mkdirSync(out,{recursive:true});
const report={consoleErrors:[],at:new Date().toISOString(),url,built,injection:false,scenarios:[],captures:[],ok:false};const browser=await chromium.launch({headless:true,channel:'msedge'});
try{for(const viewport of [{width:1280,height:800,name:'desktop'}]){const context=await browser.newContext({viewport}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());if(m.type()==='error')report.consoleErrors.push(m.text());});
 const shot=async name=>{const path=`${out}/${viewport.name}-${name}.png`;await page.screenshot({path,fullPage:true});report.captures.push({path,url,viewport,capturedAt:new Date().toISOString(),scenario:name,verdict:'pass'});};
 const open=async file=>{const event=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Open plan',exact:true}).first().click();await(await event).setFiles(resolve(file));};
 await page.goto(url);await page.locator('[data-hydration-status="ready"]').waitFor();await page.getByRole('button',{name:'Measure',exact:true}).click();await page.getByText('Plan preview unavailable',{exact:true}).waitFor();if(!(await page.getByRole('button',{name:/^Run L$/}).isDisabled()))throw Error('No-source measurement enabled');await shot('no-source');
 await open('proof/audit/IW005/fixtures/rotated-cropped.pdf');await page.locator('.measure-document-preview[data-source-ready="true"]').waitFor();const image=page.locator('.measure-document-preview img');let box=await image.boundingBox();if(Math.abs(box.width/box.height-2/3)>.01 || await image.getAttribute('data-source-rotation')!=='90' || await image.getAttribute('data-source-crop')!=='10,20,310,220')throw Error('PDF crop/rotation page bounds mismatch');await shot('pdf-rotated-crop');
 await page.getByTitle('Zoom Out',{exact:true}).click();await page.getByTitle('Zoom Out',{exact:true}).click(); // reveal lower landmarks above floating mobile controls
 const overlay=page.locator('.measure-document-preview canvas');
 const point=async(x,y)=>{const b=await image.boundingBox(),c=await overlay.boundingBox();return{x:b.x+x/200*b.width-c.x,y:b.y+y/300*b.height-c.y};};
 await page.getByLabel('Known distance',{exact:true}).fill('2400');await page.locator('.calibration-distance-row select').selectOption('mm');await page.getByRole('button',{name:'Pick two points',exact:true}).click();await overlay.scrollIntoViewIfNeeded();await overlay.click({position:await point(30,30)});await overlay.click({position:await point(30,270)});await page.getByRole('button',{name:'Lock scale',exact:true}).click();
 await page.getByRole('button',{name:/^Run L$/}).click();await overlay.click({position:await point(30,30)});await overlay.click({position:await point(30,270)});await page.getByRole('button',{name:'Finish trace',exact:true}).click();await page.getByText('2.40 m',{exact:false}).first().waitFor();await shot('pdf-landmark-measured');
 await page.getByTitle('Next Page',{exact:true}).click();await page.getByText('Page 2',{exact:true}).waitFor();await page.locator('.measure-document-preview[data-source-ready="true"]').waitFor();box=await image.boundingBox();if(Math.abs(box.width/box.height-3)>.01)throw Error('PDF second page aspect mismatch');await shot('pdf-page-two');
 await page.getByTitle('Previous Page',{exact:true}).click();await page.getByText('Page 1',{exact:true}).waitFor();await page.locator('.measure-document-preview[data-source-ready="true"]').waitFor();if(await image.getAttribute('data-source-rotation')!=='90')throw Error('PDF page return mismatch');await page.getByText('2.40 m',{exact:false}).first().waitFor();await shot('pdf-measurement-page-return');report.scenarios.push({viewport:viewport.name,pdfCropRotationAndPageSwitch:true,landmarkLengthM:2.4,unitInput:'2400 mm',ok:true});
 await open('proof/audit/IW005/fixtures/linework.dxf');await page.locator('.measure-document-preview[data-source-ready="true"] svg.document-source-page').waitFor();await shot('dxf-source-bounds');
 await open('proof/audit/IW005/fixtures/unavailable.svg');await page.getByText('This SVG has no finite viewBox or absolute page dimensions.',{exact:false}).waitFor();if(!(await page.getByRole('button',{name:/^Run L$/}).isDisabled()))throw Error('Unavailable dimensions permit measurement');await shot('unavailable-dimensions');
 if(errors.length)throw Error(errors.join('; '));report.scenarios.push({viewport:viewport.name,noSourceAndUnavailableBlocked:true,dxfRendered:true,consoleErrors:errors,ok:true});await context.close();}
 report.ok=true;
}catch(error){report.error=String(error);for(const context of browser.contexts())for(const p of context.pages()){report.failureText=await p.locator('body').innerText();await p.screenshot({path:out+'/failure.png',fullPage:true});}process.exitCode=1;}finally{await browser.close();writeFileSync(`proof/audit/IW-UI-AUDIT/formats-${built?'built':'dev'}-${run}.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));}
