import{chromium}from'playwright';import{mkdirSync,writeFileSync,readFileSync}from'node:fs';import{resolve}from'node:path';
const url='http://127.0.0.1:8081/',viewport={width:1440,height:960},out='screenshots/industry-ui-audit/industry-gap01';mkdirSync(out,{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport,acceptDownloads:true});page.setDefaultTimeout(4000);const report={url,viewport,at:new Date().toISOString(),injection:false,sourceFiles:JSON.parse(readFileSync('proof/audit/IW005/source-files-v2.json')),cases:[],captures:[],errors:[]};page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});const check=(v,m)=>{if(!v)throw Error(m);},click=name=>page.getByRole('button',{name,exact:true}).first().click();
const shot=async(name,verdict)=>{const path=`${out}/${String(report.captures.length+1).padStart(2,'0')}-${name}.png`;await page.screenshot({path,fullPage:true});report.captures.push({path,url,viewport,capturedAt:new Date().toISOString(),scenario:name,verdict});return path;};const test=async(ids,name,fn)=>{const c={ids,name,status:'pass',at:new Date().toISOString()};try{c.details=await fn();}catch(e){c.status='fail';c.error=String(e);}c.screenshot=await shot(name,c.status);c.body=await page.locator('body').innerText();report.cases.push(c);writeFileSync('proof/audit/IW-UI-AUDIT/industry-gap01.json',JSON.stringify(report,null,2));};
const open=async file=>{const e=page.waitForEvent('filechooser');await click('Open plan');await(await e).setFiles(file);};const exportJob=async name=>{await click('Proof');const e=page.waitForEvent('download');await click('Export current manifest');const d=await e,p=`proof/audit/IW-UI-AUDIT/${name}-manifest.json`;await d.saveAs(p);return JSON.parse(readFileSync(p));};const measure=async()=>{await click('Measure');await page.locator('.measure-document-preview[data-source-ready="true"]').waitFor();};const canvas=page.locator('.measure-document-preview canvas'),source=page.locator('.measure-document-preview img');const point=async(x,y)=>{const b=await source.boundingBox(),c=await canvas.boundingBox();return{x:b.x+x/12000*b.width-c.x,y:b.y+y/8000*b.height-c.y};};const mark=async(x,y)=>{await canvas.scrollIntoViewIfNeeded();await canvas.click({position:await point(x,y)});};
try{await page.goto(url);await page.locator('[data-hydration-status="ready"]').waitFor();
await test(['UI-007'],'invalid-plan-import',async()=>{await open({name:'invalid.pdf',mimeType:'application/pdf',buffer:Buffer.from('not a PDF')});await page.getByRole('alert').first().waitFor();return await page.getByRole('alert').first().innerText();});
await test(['UI-006','SITE-001','TRACE-001'],'source-import-svg',async()=>{await open(resolve('engine/fixtures/svg/sample-plan.svg'));await page.locator('.document-preview[data-source-ready="true"]').waitFor();check(await page.locator('.document-preview img').count()===1,'Actual source image missing');return{source:'engine/fixtures/svg/sample-plan.svg',hash:await page.locator('.document-preview-hash').first().innerText()};});await measure();await page.getByTitle('Zoom Out',{exact:true}).click();
await test(['TRACE-007'],'calibration-zero-negative',async()=>{await page.getByLabel('Known distance',{exact:true}).fill('0');check(await page.getByRole('button',{name:'Pick two points',exact:true}).isDisabled(),'Zero distance allowed capture');return'Zero distance blocked';});
await test(['TRACE-007'],'calibrate-mm',async()=>{await page.getByLabel('Known distance',{exact:true}).fill('11600');await page.locator('.calibration-distance-row select').selectOption('mm');await click('Pick two points');await mark(200,200);await mark(11800,200);await click('Lock scale');await page.getByText('Scale is locked for measurements on this sheet.',{exact:true}).waitFor();return'Known11600mm actualsource landmarks locked';});

await test(['TRACE-003','TRACE-004'],'arbitrary-count-unavailable',async()=>{await page.getByRole('button',{name:/^Gate C$/}).click();await mark(6000,4000);await page.getByText('Select a fence run before placing a gate.',{exact:true}).waitFor();const buttons=await page.getByRole('button').allTextContents();return{status:'not-implemented-universal-count',visibleTools:buttons.filter(n=>/Run|Area|Gate|Count|Volume/.test(n)),message:'CountshortcutCisassociatedfencegateonly;cannotcountanindependentconstructionitem'};});
await test(['DATA-002','TAKE-001'],'neutral-runtime-ui-unintegrated',async()=>{const m=await exportJob('industry-gap01');return{status:'module-only-unintegrated',jobSchema:m.job.schemaVersion,trade:m.job.trade,entityCollections:Object.keys(m.job),runs:m.job.runs.length,gates:m.job.gates.length,note:'NormalUIstillfencingjob;noneutralcount,length,area,volumeentityeditororruntimecollectionexposed'};});
}catch(e){report.fatal=String(e);}finally{report.finishedAt=new Date().toISOString();await browser.close();writeFileSync('proof/audit/IW-UI-AUDIT/takeoff02.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report.cases.map(({ids,name,status,error})=>({ids,name,status,error}))));}
