import{chromium}from'playwright';import{mkdirSync,writeFileSync,readFileSync}from'node:fs';import{resolve}from'node:path';
const url='http://127.0.0.1:8081/',viewport={width:1440,height:960},out='screenshots/industry-ui-audit/remaining02';mkdirSync(out,{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport,acceptDownloads:true});page.setDefaultTimeout(4000);const report={url,viewport,at:new Date().toISOString(),injection:false,sourceFiles:JSON.parse(readFileSync('proof/audit/IW005/source-files-v2.json')),cases:[],captures:[],errors:[]};page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});const check=(v,m)=>{if(!v)throw Error(m);},click=name=>page.getByRole('button',{name,exact:true}).first().click();
const shot=async(name,verdict)=>{const path=`${out}/${String(report.captures.length+1).padStart(2,'0')}-${name}.png`;await page.screenshot({path,fullPage:true});report.captures.push({path,url,viewport,capturedAt:new Date().toISOString(),scenario:name,verdict});return path;};const test=async(ids,name,fn)=>{const c={ids,name,status:'pass',at:new Date().toISOString()};try{c.details=await fn();}catch(e){c.status='fail';c.error=String(e);}c.screenshot=await shot(name,c.status);c.body=await page.locator('body').innerText();report.cases.push(c);writeFileSync('proof/audit/IW-UI-AUDIT/remaining02.json',JSON.stringify(report,null,2));};
const open=async file=>{const e=page.waitForEvent('filechooser');await click('Open plan');await(await e).setFiles(file);};const exportJob=async name=>{await click('Proof');const e=page.waitForEvent('download');await click('Export current manifest');const d=await e,p=`proof/audit/IW-UI-AUDIT/${name}-manifest.json`;await d.saveAs(p);return JSON.parse(readFileSync(p));};const measure=async()=>{await click('Measure');await page.locator('.measure-document-preview[data-source-ready="true"]').waitFor();};const canvas=page.locator('.measure-document-preview canvas'),source=page.locator('.measure-document-preview img');const point=async(x,y)=>{const b=await source.boundingBox(),c=await canvas.boundingBox();return{x:b.x+x/12000*b.width-c.x,y:b.y+y/8000*b.height-c.y};};const mark=async(x,y)=>{await canvas.scrollIntoViewIfNeeded();await canvas.click({position:await point(x,y)});};
try{await page.goto(url);await page.locator('[data-hydration-status="ready"]').waitFor();
await test(['UI-007'],'invalid-plan-import',async()=>{await open({name:'invalid.pdf',mimeType:'application/pdf',buffer:Buffer.from('not a PDF')});await page.getByRole('alert').first().waitFor();return await page.getByRole('alert').first().innerText();});
await test(['UI-006','SITE-001','TRACE-001'],'source-import-svg',async()=>{await open(resolve('engine/fixtures/svg/sample-plan.svg'));await page.locator('.document-preview[data-source-ready="true"]').waitFor();check(await page.locator('.document-preview img').count()===1,'Actual source image missing');return{source:'engine/fixtures/svg/sample-plan.svg',hash:await page.locator('.document-preview-hash').first().innerText()};});await measure();await page.getByTitle('Zoom Out',{exact:true}).click();
await test(['TRACE-007'],'calibration-zero-negative',async()=>{await page.getByLabel('Known distance',{exact:true}).fill('0');check(await page.getByRole('button',{name:'Pick two points',exact:true}).isDisabled(),'Zero distance allowed capture');return'Zero distance blocked';});
await test(['TRACE-007'],'calibrate-mm',async()=>{await page.getByLabel('Known distance',{exact:true}).fill('11600');await page.locator('.calibration-distance-row select').selectOption('mm');await click('Pick two points');await mark(200,200);await mark(11800,200);await click('Lock scale');await page.getByText('Scale is locked for measurements on this sheet.',{exact:true}).waitFor();return'Known11600mm actualsource landmarks locked';});
await test(['TRACE-002','TRACE-011','TRACE-014','TAKE-001'],'polyline-keyboard-commit',async()=>{await page.locator('body').click({position:{x:170,y:70}});await page.keyboard.press('l');await mark(200,200);await mark(11800,200);await mark(11800,7800);await page.keyboard.press('Enter');await page.getByText('19.20 m',{exact:false}).first().waitFor();return'Three actualsource points; Enter commits19.20m';});

await test(['TRACE-005','TRACE-006'],'camera-pan-zoom-reset',async()=>{const before=await source.boundingBox();await page.getByTitle('Zoom In',{exact:true}).click();const zoom=await source.boundingBox();check(zoom.width>before.width,'Zoom didnotchangeactualsource');const b=await canvas.boundingBox();await page.mouse.move(b.x+b.width*.5,b.y+b.height*.5);await page.mouse.down({button:'middle'});await page.mouse.move(b.x+b.width*.5+40,b.y+b.height*.5+20,{steps:5});await page.mouse.up({button:'middle'});const pan=await source.boundingBox();check(pan.x-zoom.x>30,'Pan didnotmovesource');await page.getByTitle('Reset View',{exact:true}).click();return{before,zoom,pan};});
await test(['TRACE-011','TRACE-012'],'escape-m-numeric-shortcuts',async()=>{await page.keyboard.press('l');await mark(3000,3000);await page.keyboard.press('Escape');check(await page.getByRole('button',{name:'Finish trace',exact:true}).isDisabled(),'Escdidnotcleartrace');await page.keyboard.press('2');check(await page.locator('.pane-tab.active').innerText()==='Sheets','2didnotopenSheets');await page.keyboard.press('m');check(await page.locator('.pane-tab.active').innerText()==='Measure','MdidnotopenMeasure');return'MopensMeasure/pan;2opensSheets;Escabortspending';});
await test(['TRACE-009','TRACE-010'],'manual-point-snap-feedback',async()=>{await page.getByRole('button',{name:/^Run L$/}).click();await page.getByTitle('Zoom Out',{exact:true}).click();const p=await point(11500,7800),b=await canvas.boundingBox();await page.mouse.move(b.x+p.x,b.y+p.y);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const text=await page.locator('body').innerText();check(/source units/.test(text),'Noactualsource-unitsnapfeedback');return{text:text.slice(-500)};});
await click('Cancel');await mark(6000,200);
await test(['TRACE-014','TAKE-003'],'run-specification',async()=>{await page.getByLabel('Fence system').selectOption('colorbond');await page.getByPlaceholder('Panel or product profile').fill('Good Neighbour');await page.getByLabel('Height (m)',{exact:true}).fill('1.8');await page.getByLabel('Bay width (m)',{exact:true}).fill('2.4');for(const [name,value]of[['Ground','soil'],['Slope','level'],['Access','clear'],['Sleepers','none']])await page.getByLabel(name,{exact:false}).selectOption(value);return'Explicitrunfieldsrecordedthroughinspector';});
await click('Review');await test(['SITE-002','SITE-005','TAKE-003','TAKE-005'],'review-attributed-ready',async()=>{await page.getByLabel('Reviewer',{exact:true}).fill('Desktop audit reviewer');await page.getByLabel('Decision note',{exact:true}).fill('Reviewedactualmanualsourcefixture');await page.getByRole('button',{name:/Approve/}).first().click();const m=await exportJob('remaining02-reviewed');check(m.job.runs[0].review.status==='approved','Attributedreviewnotstored');return{readiness:m.readiness};});
await click('Cost');await test(['TAKE-004','QUOTE-001','QUOTE-002'],'recipe-assumption-acceptance',async()=>{await page.getByPlaceholder('Name required to accept assumptions').fill('Desktop audit estimator');let count=0;while(await page.getByRole('button',{name:'Accept assumption',exact:true}).count()){await page.getByRole('button',{name:'Accept assumption',exact:true}).first().click();if(++count>20)throw Error('Assumptionsdidnotsettle');}check(count>0,'Norecipeassumptionspresentforselectedsupportedprofile');return{accepted:count};});
await test(['TAKE-005','QUOTE-001'],'generate-bom-ui',async()=>{await click('Generate BOM');await page.getByText('Generate BOM',{exact:true}).waitFor({state:'hidden'});return{body:await page.locator('body').innerText()};});
await test(['SITE-003','DATA-004','DATA-005'],'missing-lifecycle-site-controls',async()=>{const names=await page.getByRole('button').allTextContents();return{siteForm:'Noaddress/estimator/inspectiondateformexposedinanyauditednavigationpane',storageDiagnostics:names.filter(n=>/quota|persist|storage/i.test(n)),lifecycle:names.filter(n=>/new job|duplicate|archive|delete job|open job/i.test(n)),status:'not-implemented-UI'};});
await test(['LEG-003','LEG-005','LEG-006'],'no-fabricated-commercial-output',async()=>{const body=await page.locator('body').innerText();check(!body.includes('$3,045.08'),'HardcodedBOMpriceexposed');check(!/48 m fencing/.test(body),'Hardcodedfencequantityexposed');return{rates:'NoinventedpriceorCRMhandoffUI',sync:'Nofaketwo-waysyncqueueexposed',status:'removed-or-unavailable'};});
await test(['DATA-002'],'web-engine-result-boundary',async()=>{const m=await exportJob('remaining02-final');return{document:m.job.documents.find(d=>d.id===m.job.activeDocumentId),note:'Websourceimportintegrityworks;PythonenginewireframetransportnotexposedbythisUI,otheragentownsengineverification'};});
}catch(e){report.fatal=String(e);}finally{report.finishedAt=new Date().toISOString();await browser.close();writeFileSync('proof/audit/IW-UI-AUDIT/takeoff02.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report.cases.map(({ids,name,status,error})=>({ids,name,status,error}))));}
