import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
const base='proof/growth/2026-09-23-industry-closeout';
const [name,input,build='c56ad63e9ee7']=process.argv.slice(2);
if(!/^[a-z0-9-]+$/.test(name)||!/^[a-f0-9]{12}$/.test(build)||!input)throw Error('name input build required');
const id=`closeout-${name}-${build}`;
const scenario=JSON.parse(fs.readFileSync(input,'utf8').replace(/^\uFEFF/,''));
const serialized=JSON.stringify(scenario,null,2).replaceAll('http://127.0.0.1:8080','http://127.0.0.1:8081')+'\n';
const local=`${base}/scenarios/${id}.json`;
fs.writeFileSync(local,serialized,{flag:'wx'});
const sha=createHash('sha256').update(serialized).digest('hex');
const remote=`C:/Users/danie/XRayFastCdp/${id}.json`;
const output=`C:/Users/danie/XRayFastCdp/runs/${id}`;
const workspace=`C:/Users/danie/XRayBuilds/runs/${build}/source`;
function run(cmd,args){const r=spawnSync(cmd,args,{encoding:'utf8',windowsHide:true,maxBuffer:8e6});process.stdout.write(r.stdout??'');process.stderr.write(r.stderr??'');return r.status;}
if(run('scp',['-q',local,`tonys-test-pc:${remote}`])!==0)throw Error('scenario transfer failed');
const code=`$ErrorActionPreference='Stop';$ProgressPreference='SilentlyContinue';if($env:COMPUTERNAME -ne 'DANS1'){throw 'Wrong worker'};if((Get-FileHash -LiteralPath '${remote}').Hash.ToLowerInvariant() -ne '${sha}'){throw 'Scenario hash differs'};& '${workspace}/scripts/run-fast-cdp.ps1' -Scenario '${remote}' -Output '${output}' -Workspace '${workspace}' -RunId '${id}' -PreviewMode built -PreviewPort 8081 -CdpPort 9351 -Chrome 'C:/Program Files/Google/Chrome/Application/chrome.exe'`;
const status=run('ssh',['tonys-test-pc','powershell','-NoProfile','-ExecutionPolicy','Bypass','-EncodedCommand',Buffer.from(code,'utf16le').toString('base64')]);
const copied=run('scp',['-q','-r',`tonys-test-pc:${output}`,`${base}/`]);
if(status||copied)throw Error(`journey=${status}, evidence-copy=${copied}; failures retained`);
